### ISSUE TITLE
Small imperfections on Rectify11

### ISSUE THREAD

**Issue by Etern-34520** [Rectify11/Installer#146]
### Description

Small imperfections on Rectify11

### Steps To Reproduce

easyly

### Rectify11 Version

3.0 rp3

### Windows Version

Windows11 22H2 22621.1555

### Logs

![image](https://github.com/MishaProductions/Rectify11Installer/assets/93083287/3aa37884-ef06-4b31-b954-29ca6a709425)

Black and white inversion in Excel

![image](https://github.com/MishaProductions/Rectify11Installer/assets/93083287/9fcf3b1e-4130-4349-8e41-029382a61115)

Gray fragments

![image](https://github.com/MishaProductions/Rectify11Installer/assets/93083287/e4ec848e-070c-4f8c-8af0-2f0682c648d7)

The gray border of the on-screen keyboard

![image](https://github.com/MishaProductions/Rectify11Installer/assets/93083287/614a98a6-ded3-4fbe-9af2-cb795daf3870)

......

**Comment by Etern-34520** [comment]
The color of the font is too light

**Comment by SmirbYrneh420** [comment]
The Excel color inversion can be fixed with an unofficial plugin. It's not perfect, but it'll work.
https://github.com/matafokka/ExcelDarkThemeFix

As for the light font in Bing, use a force dark theme extension or go to edge://flags, search "force dark" and enable the flag. I'm not sure about Chrome but the flag should be similar if not the same.

**Comment by SmirbYrneh420** [comment]
The grey border could be MicaForEveryone. I'm looking for a fix for you

**Comment by ooTruffle** [comment]
There is a user made CSS theme to fix the chromeium force msstyles codechange

https://github.com/MishaProductions/Rectify11Installer/issues/127#issuecomment-1537418783

**Comment by vhick** [comment]
Hello,

Sorry for bumping this. I also have the same problem when update to Rectify11 v3.0 RC3, although on RC2, the text is gray to I still see the text even if still hard to see it. but now, its all black.

Many thanks!

**Comment by ooTruffle** [comment]
Text is black on what?

**Comment by vhick** [comment]
> Text is black on what?

The backdrop and text is black Sir, same as image above.
