### ISSUE TITLE
Issue with Coloring in Legacy File Transfer Box

### ISSUE THREAD

**Issue by Vipin2003** [Rectify11/Installer#154]
### Description

There is a coloring issue in Latest Rectify11 (3.0.35.0) that it completely invert the colors in Legacy File Transfer Dialog Box, which completely ruins its look. The old version (3.0.0.0) keeps it as it is. I've patched Icons only. I think that DEV's should fix this in upcoming action releases.

### Steps To Reproduce

Just Patch icons (both basic and advanced) and Use EP with Legacy File Transfer Enabled and Copy any file (big files for better view) and see the Issue.

### Rectify11 Version

3.0.35.0

### Windows Version

Win11 22H2 22621.1776

### Logs

![2023-05-23_19h10_59](https://github.com/MishaProductions/Rectify11Installer/assets/93650504/b6011dec-4cfa-4234-9f06-aea280937aeb)

**Comment by rounk-ctrl** [comment]
it looks good on dark mode
