### ISSUE TITLE
(enhancement) Installer should create a restore point

### ISSUE THREAD

**Issue by es1228** [Rectify11/Installer#162]
I think the rectify11 installer should make a restore point before installing, lots of users install this just to find the theme broken and realize they are unable to uninstall, however creating a restore point will rectify this issue, also it should be stated that to run said restore point the restore must be run from the recovery environnment, as running from within the os will output a fail.

**Comment by Typical0** [comment]
Well, restore points should be added as a protection in case of something breaking in uninstaller. Also, most of the themes issue are caused by using outdated versions, and we do not have time and patience to provide support for RP3 and below.

**Comment by evansidhu** [comment]
Yeah, maybe it can be added in a future build such as the next release preview or final

**Comment by es1228** [comment]
No point in making a restore point if sfc /scannow and manually uninstalling extras and deleting theme files and rectify11 folder can fix this anyways.

**Comment by es1228** [comment]
Fixed as of RC2
