### ISSUE TITLE
The black and white problem on MS Excel also does on MS Word

### ISSUE THREAD

**Issue by PhucTan-IT** [Rectify11/Installer#175]
### Description

The black and white problem on MS Excel also does on MS Word

### Steps To Reproduce

idk pls help

### Rectify11 Version

latest

### Windows Version

Windows 11 22H2 22631.1906

### Logs

![image](https://github.com/MishaProductions/Rectify11Installer/assets/87054949/03a26f80-44e3-48dc-9888-81a898f99b81)

here is the image

**Comment by broeringvictor** [comment]
I also don't know what to do. I work with Office 365 and I'm desperate.

**Comment by SavvyTech11** [comment]
I also work with Office 365 and this problem has left me frustrated...

**Comment by rounk-ctrl** [comment]
Excel: https://github.com/matafokka/ExcelDarkThemeFix
Powerpoint: https://github.com/matafokka/PowerPointDarkThemeFix
Word: https://github.com/Rectify11/Installer/issues/200#issuecomment-1668170778

**Comment by hoaug-tran** [comment]
@rounk-ctrl hello. with word. i try enable never change the document page color but it doesnt working. any ideas? thanks

![image](https://github.com/Rectify11/Installer/assets/92006941/4886c67c-3596-4017-b4ce-2b6dc9d73d79)
![image](https://github.com/Rectify11/Installer/assets/92006941/6500f3e6-84bf-4ed1-9d31-2a71ced551d0)

**Comment by rounk-ctrl** [comment]
go to view and select switch modes

**Comment by hoaug-tran** [comment]
> go to view and select switch modes

thank you but i dont see switch modes in View panel..

![image](https://github.com/Rectify11/Installer/assets/92006941/d332a43c-71a6-401f-b81b-d82f28a15bd0)

**Comment by Aizzat92** [comment]
> ### Description
> The black and white problem on MS Excel also does on MS Word
> 
> ### Steps To Reproduce
> idk pls help
> 
> ### Rectify11 Version
> latest
> 
> ### Windows Version
> Windows 11 22H2 22631.1906
> 
> ### Logs
> ![image](https://user-images.githubusercontent.com/87054949/248547214-03a26f80-44e3-48dc-9888-81a898f99b81.png)
> 
> here is the image

**Comment by TiagoRibeiro25** [comment]
> > go to view and select switch modes
> 
> thank you but i dont see switch modes in View panel..
> 
> ![image](https://user-images.githubusercontent.com/92006941/266284322-d332a43c-71a6-401f-b81b-d82f28a15bd0.png)

The Dark/Light Toggle feature seems to be available exclusively when your theme is set to BLACK. I initially had my theme set to Dark Gray and couldn't find the switch mode option. However, as soon as I changed my theme to BLACK, the toggle feature became accessible.

**Comment by SmirbYrneh420** [comment]
Any ideas for fixing OneNote? I get white page with white text in dark mode
@rounk-ctrl

**Comment by ApartTUSITU** [comment]
Also on WPS Office

**Comment by Blue-Star-Technology** [comment]
have you got micaforeveryone installed?

**Comment by ApartTUSITU** [comment]
> have you got micaforeveryone installed?

Problems caused by ExplorerFrame?

**Comment by ApartTUSITU** [comment]
I installed it, but I don't think it's causing the problem

**Comment by ApartTUSITU** [comment]
This may not be an issue caused by micaforeveryone

**Comment by Blue-Star-Technology** [comment]
i think it is; try creating a rule in micaforeveryone

**Comment by ISIN11** [comment]
How do I make the LIGHT THEME display correctly?

**Comment by kastentop2005** [comment]
> i think it is; try creating a rule in micaforeveryone

Tried creating a rule for both WINWORD and OpusApp (Word window class name) but no luck

**Comment by kastentop2005** [comment]
The issue only persists with Mica theme, so its the source I guess

**Comment by Bodzijun** [comment]
in the Office account settings you can change the theme to the system one, for example, and then the sheet will become white, but this will not solve the problem, the selection will be white on white
