### ISSUE TITLE
Weird square on desktop

### ISSUE THREAD

**Issue by ArbestRiAgain** [Rectify11/Installer#179]
### Description

Like the title says, there is a weird square on my desktop in the top right corner.

### Steps To Reproduce

Install Rectify11 and choose the "dark theme with Mica" theme, I haven't tested other themes yet

### Rectify11 Version

3.0.24.0

### Windows Version

Windows 11 22H2 22621.1928

### Logs

![image](https://github.com/MishaProductions/Rectify11Installer/assets/132712354/5187dc5d-ba1b-4946-ac54-4bba723fb60d)

**Comment by CobaltGames** [comment]
Happened to me as well, press Windows+D to get rid of it (I think)

**Comment by ArbestRiAgain** [comment]
> Happened to me as well, press Windows+D to get rid of it temporarily (I think)

That fixed it, but I'll update sometime

**Comment by emigdio821** [comment]
@ArbestRiAgain could you please share that wallpaper? Thanks!

**Comment by ArbestRiAgain** [comment]
![image](https://github.com/Rectify11/Installer/assets/132712354/4e7bd7d3-312e-4cb8-85d7-c2840e49f1bf)
Latest commits fixed the square issue (this screenshot was from a VM)
