### ISSUE TITLE
Rectify11 Dark Cursor small uses cursor from medium & medium uses small

### ISSUE THREAD

**Issue by nasiftanjim** [Rectify11/Installer#181]
### Description

Rectify11 Dark Working in background cursor small uses cursor from medium & medium uses one from small.

### Steps To Reproduce

Just install & apply dark cursor

### Rectify11 Version

Version 3.0 rp3

### Windows Version

Windows 11 22H2 Build 22621.1848

### Logs

![image](https://github.com/MishaProductions/Rectify11Installer/assets/67149197/a620c0bb-b6c1-466c-88b2-38f5db267c6b)

**Comment by rounk-ctrl** [comment]
fixed
