### ISSUE TITLE
Buggy UI

### ISSUE THREAD

**Issue by YT-Advanced** [Rectify11/Installer#182]
# Black dot surround text
![image](https://github.com/MishaProductions/Rectify11Installer/assets/70064328/06297c9a-7c16-4e03-a6d6-6551494f868a)
# Some element doesn't have Mica
![image](https://github.com/MishaProductions/Rectify11Installer/assets/70064328/5f5486cd-1906-467e-8b12-471c09a8704b)

**Comment by SmirbYrneh420** [comment]
1. Nothing is perfect
2. Could be micaforeveryone issue

**Comment by legofanlovessayori** [comment]
the first screenshot is a known, unfixable bug in micaforeveryone (just read the github for that)
and mmc being hardcoded is a ms thing

**Comment by YT-Advanced** [comment]
Also want to report that the chosen boxes break on 150% scale in Devices Manager.
