### ISSUE TITLE
Right click on the task bar not working after install

### ISSUE THREAD

**Issue by TheKeiki** [Rectify11/Installer#187]
### Description

After installing the program, the right click on the taskbar stopped working, the right click on the icons still works, but the right click to open the task manager is gone. I tried using the registry modification solutions or using vivetool to bring it back but without any success.

### Steps To Reproduce

NA

### Rectify11 Version

3.0.24.0

### Windows Version

Windows 11 22H2

### Logs

NA

**Comment by YT-Advanced** [comment]
Same but now I can click (I don't know why) :)))

**Comment by apoklyps3** [comment]
same after restart. 
rectify11 v3.0-rc1

**Comment by rounk-ctrl** [comment]
did you install enhanced context menus?

**Comment by rounk-ctrl** [comment]
oh if you enable classic menus, the right click on taskbar breaks
