### ISSUE TITLE
Rectify11 Control Panel missing

### ISSUE THREAD

**Issue by bubblesssssss12122112** [Rectify11/Installer#188]
### Description

I installed Rectify11. I noticed that I was missing the Rectify11 Control Center. When I search up "Rectify11" in my Search, it only comes up with Rectify11installer.exe.

### Steps To Reproduce

Installing

### Rectify11 Version

3.0

### Windows Version

Windows 11 22H2 Home

### Logs

?

**Comment by ooTruffle** [comment]
R11 Control Center is Currently disabled

**Comment by dark-coder-cat** [comment]
> R11 Control Center is Currently disabled

then how can i customize it??

**Comment by bubblesssssss12122112** [comment]
exactly!

**Comment by rounk-ctrl** [comment]
its back
