### ISSUE TITLE
opening html files in Firefox turns black automatically even if set to light theme in browser settings

### ISSUE THREAD

**Issue by makkarankush68** [Rectify11/Installer#189]
### Description

when we open html files in firefox (specifically) with rectify 11 theme set to dark (any dark theme) it turns the page from light to dark automatically . Which is not good as it wasn't designed that way and hinders the development experience   

### Steps To Reproduce

1) Create/download a html file
2) open it with firefox browser while rectify11 dark theme set
3) page automatically goes to dark theme

### Rectify11 Version

Rectify11 3.0.24.0

### Windows Version

Windows 11 22H2 22621.1992

### Logs

>with windows dark theme (this is how it should be )
![Screenshot 2023-07-20 141347](https://github.com/MishaProductions/Rectify11Installer/assets/97383407/6fd8ee52-bea6-4204-b785-73e3fe2c315a)
>with rectify 11 dark theme
![Screenshot 2023-07-20 141320](https://github.com/MishaProductions/Rectify11Installer/assets/97383407/6c57b747-3336-4390-bb13-151809f7b260)

**Comment by makkarankush68** [comment]
with brave/chrome this doesn't happen but firefox is GOAT for CSS

**Comment by ooTruffle** [comment]
> In Firefox Settings, you have to go to _General -> Colors -> Manage Colors..._
> Uncheck the `Use system colors` checkbox. Now it should be as expected.

This unless something changes in the latest ff update 

As something might have

**Comment by Double-A-92** [comment]
This is a much wider problem caused by using the Rectify11 dark themes. Lots of applications are affected by this (e.g try opening Excel).

It's best to switch back to the normal Dark Theme, until they figure out some pargmatic solution...
