### ISSUE TITLE
Suggest creating a restore point before install

### ISSUE THREAD

**Issue by AtlasC0R3** [Rectify11/Installer#190]
**This is a feature request.**

Seeing as the installer currently does not have a functioning uninstaller, a restore point made before such (abrasive) changes to Windows can, for now, be a functioning workaround to an uninstaller.
Maybe add a last popup before the installation begins, prompting the user "do you want to be sure to have a backup? you can and perhaps should create a restore point", or something like that?

I suggest this, because that is what I have done to revert the changes.
*(It did also remove apps I had installed, but in the grand scheme of things that wasn't a huge issue. The important part is, it did successfully revert Rectify11's changes.)*

**Comment by legofanlovessayori** [comment]
pretty sure the team has implemented a uninstaller now

**Comment by AtlasC0R3** [comment]
It has failed on my end, giving an unhandled exception, so I guess this should be done as a backup measure.

**Comment by legofanlovessayori** [comment]
> It has failed on my end, giving an unhandled exception, so I guess this should be done as a backup measure.

kinda doesn't make sense to add that before finishing the uninstaller, also if possible can you provide the logs that the error spits out so the devs can actually fix it

**Comment by AtlasC0R3** [comment]
I have not saved the log or exception so I'm afraid I cannot post a log of the issue.
Besides that is not the point of this issue; should the uninstaller, which I remind is in prerelease, fail then the user still has ways to revert changes, admittedly a restore point is excessive but, again, that should only be used should the uninstaller catastrophically fail.

When the uninstaller is stable and functional, then I'm all for removing this indicator. Until then, not everyone wants to fiddle with their operating system to theme it, some just want to revert changes for whatever reason they'd like after realizing altering their OS like this isn't quite what they want.

**Comment by sans202** [comment]
I personally like the idea
