### ISSUE TITLE
Black Text Box (Dark Theme with Mica)

### ISSUE THREAD

**Issue by elNino0916** [Rectify11/Installer#191]
### Description

When clicking on an textbox in explorer, the textbox background is not transparent (mica).

### Steps To Reproduce

Open any explorer window (also control panel) and click on the search bar

### Rectify11 Version

3.0.24.0 (actions build from commit 1aeb33a)

### Windows Version

Windows 11 23H2 25905.1000

### Logs

![image](https://github.com/MishaProductions/Rectify11Installer/assets/84574414/1113d4bc-71e9-460f-991c-261577b6efd1)
![image](https://github.com/MishaProductions/Rectify11Installer/assets/84574414/4cffc507-5bcf-4cc9-9b0f-14bb0ab2c415)

**Comment by SmirbYrneh420** [comment]
Hm. Must be hardcoded. No easy fix

**Comment by RocGod** [comment]
Not only on Explorer, even some text input box on webpage, it will show black and can't see the input text

**Comment by Double-A-92** [comment]
Yeah it's pretty bad. This even changes things like the colors of the cells in Excel. And it also makes the background of some pages in Firefox black.

**Comment by bbecausereasonss** [comment]
Having this issue in many places like chrome (text and selection boxes)

**Comment by Gianlucasimonetz** [comment]
hi all, i have the exact same problem.
Black browser forms, black excel, black outlook. Is there a solution?

**Comment by rounk-ctrl** [comment]
limitation of windows
