### ISSUE TITLE
Windows Defender flags Phase 2 exe via heuristics

### ISSUE THREAD

**Issue by SmirbYrneh420** [Rectify11/Installer#193]
### Description

Happened after replacing files and/or phase 2

### Steps To Reproduce

1. Install Rectify11
2. Wait for it to replace files
3. Defender gives threats found notification

### Rectify11 Version

3.0.34.0

### Windows Version

Windows 11 Dev build 23511

### Logs

![image](https://github.com/MishaProductions/Rectify11Installer/assets/110212580/cc1e6a41-7257-4bf0-bb27-ffc5b8200703)

**Comment by MishaProductions** [comment]
Allow it in windows defender, its a false flag
