### ISSUE TITLE
Display scale doesn't work 

### ISSUE THREAD

**Issue by lts20050703** [Rectify11/Installer#199]
### Description

After installing the (as of now) latest github action build, display scaling doesn't work for some elements (see screenshots below)

### Steps To Reproduce

Install the (as of now) latest github action build, then set display scaling to anything other than 100%

### Rectify11 Version

https://github.com/Rectify11/Installer/actions/runs/5761794951

### Windows Version

Windows 11 Home Insider Canary (25915.1000 rs_prerelease)

### Logs

(Images below are at 150% display scale)

<img width="960" alt="image" src="https://github.com/Rectify11/Installer/assets/87189679/03145211-2193-4000-b892-24dc09bd2902">

<img width="960" alt="image" src="https://github.com/Rectify11/Installer/assets/87189679/a0cc131e-84f8-4687-b9b4-68329570c626">

<img width="960" alt="image" src="https://github.com/Rectify11/Installer/assets/87189679/790ae85d-c320-4c43-97fc-8df531e85900">

**Comment by SmirbYrneh420** [comment]
I set my display scale to 150% and it seems to be fine...
<img width="689" alt="image" src="https://github.com/Rectify11/Installer/assets/110212580/a8a73cfa-0483-47b3-8b5a-20694c152540">
<img width="683" alt="image" src="https://github.com/Rectify11/Installer/assets/110212580/fc52123a-ebe1-48c9-a724-00d2fc6e59c5">

**Comment by lts20050703** [comment]
Hmm what version of windows are you using? I guess this could be a windows 11 insider canary issue

**Comment by WinExperiments** [comment]
@lts20050703 The issue happens because the installer now automatically installs Segoe UI Variable, but the 9pt font does not scale (9pt is default on 100%, 150% uses 14pt.) If you have installed it on 100% scaling, it would've applied the 9pt font on there and you'd rescale it to 150% normally.
