### ISSUE TITLE
In Microsoft Word turning light theme on results in a full black page and turning dark theme on results in a white blank page

### ISSUE THREAD

**Issue by SavvyTech11** [Rectify11/Installer#200]
### Description

I use MS Word every day and I faced this issue. I turned dark theme on from rectify11 control and when I went to Word it was a greyed-out page and very little visible text that I had written. Then I proceeded to turn on the light theme from the rectify11 control center and the page turned full black with little visible grey text. Personally, I need the light mode to work with MS Word so when in light mode the page will also be white, not black. Please look into this and fix it. Thanks!
P.S.-I use Rectify 11 Dark theme and I use the light theme in Word because it's easier.

### Steps To Reproduce

Fix the black page in the light mode of Word.

### Rectify11 Version

Version 3.0 RC1

### Windows Version

Windows 11 22H2 22621.2070

### Logs

![Word1](https://github.com/Rectify11/Installer/assets/141437794/e2e6a4c6-f6f8-41ef-8181-cda5e220987a)
![Word](https://github.com/Rectify11/Installer/assets/141437794/9f486ac4-f43d-4e46-9c9d-ed0c07549f29)

**Comment by Vathsanmollyn** [comment]
To fix this issue, go to the options in ms word and check the - never change the document page color.
It works for only darker themes as the white document page is not available. hope this helps!
![Picture1](https://github.com/Rectify11/Installer/assets/123929329/f6bf6d45-0eef-4209-95de-152afabdf388)
![Picture2](https://github.com/Rectify11/Installer/assets/123929329/06cac963-526a-48c8-94f9-3e94a5727154)

**Comment by TheBeeBoi** [comment]
fr we need a better fix than this

**Comment by wangyan-life** [comment]
I'm also using the dark mode, and after making the changes you mentioned, it still doesn't read well, and I'm still hoping you can make a better fix, thanks!

**Comment by ISIN11** [comment]
Why the forum thread is closed, how to use a full-fledged white theme in word?

**Comment by x2435Bits** [comment]
> I cannot stand typing up documents on a black page, is there any way to fix this?

There likely won't be a fix to this anytime soon as this is caused by Microsoft Hardcoding colors in MS Office Products. Either use the partial dark theme, or use the fix provided above (turning on "Never Change Page Color".

**Comment by grimmute** [comment]
> ...or use the fix provided above (turning on "Never Change Page Color".

This "workaround" doesn't work on Office 2024.

![Screenshot 2024-11-04 124955](https://github.com/user-attachments/assets/aa24c8ca-3991-4340-96ec-40234917639a)
