### ISSUE TITLE
Colors are washed ot on images

### ISSUE THREAD

**Issue by TheMispeled** [Rectify11/Installer#201]
### Description

So if you open any (except the one that comes in windows) software that displays an image (example : irfanview), the colors are washed out. They appear a bit white.

### Steps To Reproduce

Download Irfanview then open any image

### Rectify11 Version

V3.0 RC1

### Windows Version

Windows 11 22H2 build 22621.1992

### Logs

![image](https://github.com/Rectify11/Installer/assets/111089725/f9c02f2a-ce99-4378-a707-e87be6860ba4)
(normal on the left and irfan view on the right)

**Comment by Quantum3566** [comment]
This is a MFE issue you can fix this by opening it from the system tray
