### ISSUE TITLE
Windows explorer shows parts of window as pitch black instead of gray

### ISSUE THREAD

**Issue by CheezyFriez12** [Rectify11/Installer#202]
### Description

Instead of the standard gray color, windows explorer is using a black color for most of the window.

### Steps To Reproduce

Applying a rectify11 theme

### Rectify11 Version

Version 3.0 rp3

### Windows Version

Windows 11 22H2 23516.ni_prerelease.230728-1428

### Logs

N/A

**Comment by legofanlovessayori** [comment]
did you apply the amoled dark theme by chance?

**Comment by Quantum3566** [comment]
im fucking done with people using rp3

**Comment by CheezyFriez12** [comment]
> im fucking done with people using rp3

What's wrong, is that not the latest build? I've only just started using rectify 11

**Comment by ooTruffle** [comment]
The Latest Release Candidate build is RC1
https://truffle.signed.host/MF6GQ.png
Not RP3

**Comment by CheezyFriez12** [comment]
> The Latest Release Candidate build is RC1 https://truffle.signed.host/MF6GQ.png Not RP3

Thank you for a straight answer, that other guy doesn't seem to know how to be helpful.

**Comment by CheezyFriez12** [comment]
> The Latest Release Candidate build is RC1 https://truffle.signed.host/MF6GQ.png Not RP3

Just realized I was on RC1, not sure why I typed RP3

**Comment by legofanlovessayori** [comment]
> Rectify11 dark with mica, but it applied to every rectify dark theme.

can you provide a screenshot

**Comment by CheezyFriez12** [comment]
> > Rectify11 dark with mica, but it applied to every rectify dark theme.
> 
> can you provide a screenshot

I'll have to reinstall it, I had some troubles with the taskbar not appearing

**Comment by CheezyFriez12** [comment]
It seems that MicahForEveryone was not applying to Windows Explorer windows, but that has been fixed with a reinstall
