### ISSUE TITLE
Images in Norton Security windows have a black background

### ISSUE THREAD

**Issue by piotr25691** [Rectify11/Installer#203]
### Description

The images contained in Norton Security settings windows have a black background.

That wasn't the case on clean Windows 11.

### Steps To Reproduce

1. Open the settings window in Norton Security
2. Observe the black background images

### Rectify11 Version

Rectify11 v3.0 RC1

### Windows Version

Windows 11 23H2 22631.2129

### Logs

![image](https://github.com/Rectify11/Installer/assets/71488561/8b6edbc9-6d0b-4876-9a4c-e3fd4b3526fb)

**Comment by SmirbYrneh420** [comment]
Hmm. Must be another instance of lazy developers hardcoding colours into software

**Comment by Dipuuu111** [comment]
so is there a way to exclude programs which can get affected from rectify 11?

**Comment by legofanlovessayori** [comment]
> so is there a way to exclude programs which can get affected from rectify 11?

no, blame norton for hardcoding resources

(also you should nuke it off your pc anyway, might be that it falsely detects components of r11 as malware)

**Comment by Dipuuu111** [comment]
yeah surely it does give a lot of false positives

it updates on its own then say that the cmd is data breaching
now it is time for norton say bye ig.

**Comment by piotr25691** [comment]
> > so is there a way to exclude programs which can get affected from rectify 11?
> 
> no, blame norton for hardcoding resources
> 
> (also you should nuke it off your pc anyway, might be that it falsely detects components of r11 as malware)

Indeed as I got a lot of Data Protector warnings that I had to turn off while installing Rectify11

**Comment by Double-A-92** [comment]
> Hmm. Must be another instance of lazy developers hardcoding colours into software

I don't understand how this is hard coding... It's exactly the opposite, since it's using a background color defined by some system ressource. How is it the softwares' fault if Rectify11 changes some system constant?

**Comment by legofanlovessayori** [comment]
> I don't understand how this is hard coding... It's exactly the opposite, since it's using a background color defined by some system ressource. How is it the softwares' fault if Rectify11 changes some system constant?
> 
> 
its not using a color from the system, its hardcoded to use white

and yes, thats definetly how a normal windows app's titlebar looks like

**Comment by Double-A-92** [comment]
The issue is not that the window is white (apps should be allowed to have their own custom designs)... it's the the **icons** inside the window have a black background.

I don't know why the icons used a color from the  windows system theme to define their white, but Rectify11 has definitely changed that color... And it probably shouldn't, since it seems to affect all kind of different apps negatively.

**Comment by legofanlovessayori** [comment]
> The issue is not that the window is white (apps should be allowed to have their own custom designs)... it's the the **icons** inside the window have a black background.
> 
> I don't know why the icons used a color from the  windows system theme to define their white, but Rectify11 has definitely changed that color... And it probably shouldn't, since it seems to affect all kind of different apps negatively.

thats how msstyles on hardcoded apps work my guy

**Comment by MishaProductions** [comment]
The issue is that the background is hardcoded and the foreground isn't, or in reverse. Contact the developer of the app or use the light theme.
