### ISSUE TITLE
R3 RC - Windows 11 Pro - Black Screen

### ISSUE THREAD

**Issue by jastranlove2020** [Rectify11/Installer#204]
### Description

It made me worry about Windows 11 Pro crashing when installing, there is no warning about setup time clearly,  the installer keeps standing at 8% for 1 hour non-completed as hang thought so i tried to reboot to stopping the install and then Windows 11 crashing with Black Screen, i moved to Safe mode with Low Resolution and then logging ok.

The installer software takes many hours to complete and feels as stuck with standing percentage long time, it takes too much time and could not do stop or rollback if user needs for that. The Installer decompiles and recompile resource dlls should show all active info at debug devel.

There is no guide and anyone considering with test pc because it can make you trouble as crashing and much effort taken.

### Steps To Reproduce

As above

### Rectify11 Version

V3 RC

### Windows Version

Windows 11 21H2

### Logs

No log

**Comment by Quantum3566** [comment]
just let it patch bro

**Comment by Quantum3566** [comment]
your drive is probably corroded from the inside

**Comment by ArbestRiAgain** [comment]
It must be caused by the `imageres` patching

**Comment by ArbestRiAgain** [comment]
Latest version from GitHub Actions fixed the `imageres` patching being stuck

**Comment by rounk-ctrl** [comment]
prob fixed idk
