### ISSUE TITLE
Very Laggy Window Scaling

### ISSUE THREAD

**Issue by ZoomDriver57** [Rectify11/Installer#206]
### Description

when you scale a window like cmd, task manager, and other programs except file explorer with blur behind on the scalling of the window is verry laggy. The Windows Build is Windows 11 22H2  25921.1000 but even with older builds its verry laggy

### Steps To Reproduce

turn on blur behind on in mica for everyone for a add process or something else that's not file explorer

### Rectify11 Version

3.0

### Windows Version

Windows 11 22H2  25921.1000

### Logs

N/A

**Comment by SmirbYrneh420** [comment]
![image](https://github.com/Rectify11/Installer/assets/110212580/9ad569a8-86f7-4d2e-a94b-3f51c07d2b02)
this is from the micaforeveryone wiki. this is a mfe issue, not a rectify11 issue
