### ISSUE TITLE
Certain apps with increased gamma/brightness due to MicaForEveryone

### ISSUE THREAD

**Issue by jaimetavares-code** [Rectify11/Installer#208]
### Description

As the title says, there's a couple software I have installed in my machine, which the window has increased gamma/brightness, due to MicaForEveryone. The software in question, as of now, are Minecraft in windowed mode and PPSSP. Below are screenshots to display the issue I'm having with Rectify11.

![image](https://github.com/Rectify11/Installer/assets/55595800/0f433a06-cab7-45dd-afa7-91f45cd112f4)
(PPSSPP windowed mode)

![image](https://github.com/Rectify11/Installer/assets/55595800/6c9cab20-d0ac-4210-8a4e-9643f12a2a11)
(PPSSPP full screen)

Googling PPSSPP images, this is how it usually looks, without rectify11. note that although the image is from windows 10, it's how it used to look like in windows 11, before installing rectify11. it's just for demonstration purposes
![image](https://github.com/Rectify11/Installer/assets/55595800/3124bd72-47db-4c41-887a-e38d73995fac)
("normal" PPSSPP)

![image](https://github.com/Rectify11/Installer/assets/55595800/43a36e8d-db12-45e5-8c0e-df467b055191)
(Minecraft windowed mode)

![image](https://github.com/Rectify11/Installer/assets/55595800/03bb3ae7-8ecb-45b9-860c-033214bd940c)
(Minecraft full screen; how it should look like)

### Steps To Reproduce

- Install Rectify11 with dark mode and MicaForEveryone

### Rectify11 Version

v3.0 RC1

### Windows Version

Windows 11 Home 22H2 (OS Build 22621.2070)

### Logs

no logs within my issue.

**Comment by legofanlovessayori** [comment]
exclude the affected apps in mfe's settings
