### ISSUE TITLE
Software leaving white patches in windows insider build dev release .

### ISSUE THREAD

**Issue by Dipuuu111** [Rectify11/Installer#210]
### Description

Recently i used this software and after applying the (theme any of them) especially in dark themes it leaves white patches it even makes may text unreadable which are covered in these patches.

Even some of the text is not readable

### Steps To Reproduce

Just open control panel it shows white patches in any dark theme selected

and 

select any drive and select the property tab and select different tabs to view different text colors

### Rectify11 Version

v3.0 RC1

### Windows Version

Windows 11 Insider Preview 23511.1000 (ni_prerelease)

### Logs

![image](https://github.com/Rectify11/Installer/assets/88713641/3ad297e2-77bd-4809-9574-a6b0068ff257)

![image](https://github.com/Rectify11/Installer/assets/88713641/fdaae016-fb99-4ffe-87d5-1a4d2e1b4fbc)

**Comment by rounk-ctrl** [comment]
yea

**Comment by Dipuuu111** [comment]
ok thanks
