### ISSUE TITLE
Browser font and minimizing, maximizing animation is weird

### ISSUE THREAD

**Issue by olam-diam-pmblaze** [Rectify11/Installer#211]
### Description

Please fix it it is in the 3.0 RC. Browser font and minimizing, maximizing animation is weird

### Steps To Reproduce

Fix wierd things and it will be ok.

### Rectify11 Version

3.0 rc

### Windows Version

Windows 11 23H2 22631.2129

### Logs

![image](https://github.com/Rectify11/Installer/assets/99337263/d890b7f9-56d3-4625-8bf1-2d6806572cd1)

**Comment by rounk-ctrl** [comment]
for browser font, #127.
for maximizing and minimizing animation we cant do anything until LucasB releases his themetool.
