### ISSUE TITLE
Firefox window controls get changed, doesn't match color of the taskbar

### ISSUE THREAD

**Issue by DylwinTFTW** [Rectify11/Installer#216]
### Description

When using Firefox with Rectify 11, the window controls change to be inconsistent with the rest of the UI.

### Steps To Reproduce

1. Install Rectify11
2. Launch Firefox

### Rectify11 Version

Version 3 RC1

### Windows Version

Windows 11 22H2 2621.2134

### Logs

![image](https://github.com/Rectify11/Installer/assets/51421022/e29549bd-69fb-4609-92ef-179a17c61db8)

**Comment by ooTruffle** [comment]
This is firefox falling back to high contrast with custom themes

To fix it apply this userChrome.css
https://mrotherguy.github.io/firefox-csshacks/?file=window_control_fallback_for_custom_windows_theme.css

**Comment by alanthast0s** [comment]
> This is firefox falling back to high contrast with custom themes
> 
> To fix it apply this userChrome.css https://mrotherguy.github.io/firefox-csshacks/?file=window_control_fallback_for_custom_windows_theme.css

how can I apply this userChrome.css ?

**Comment by alanthast0s** [comment]
> You can apply by:
> 
>     * First, on firefox type in `about:profiles` then at the root directory click `open folder`
> 
>     * Then, go to `about:config` find `toolkit.legacyUserProfileCustomizations.stylesheets` double click to enable
> 
>     * After that, make a folder named `chrome` in the directory that u opened then create a file name `userChrome.css` inside that folder
> 
>     * Then copy this to your `userChrome.css`:
> 
> 
> ```
> 
> .titlebar-button{
>   background-color: transparent !important;
>   -moz-context-properties: stroke !important;
>   stroke: currentColor !important;
> }
> .titlebar-button:hover{ background-color: hsla(0,0%,100%,.32) !important }
> .titlebar-close:hover{ background-color: hsl(355,86%,49%) !important }
> 
> .titlebar-close{ list-style-image: url(chrome://browser/skin/window-controls/close.svg) !important }
> .titlebar-min{ list-style-image: url(chrome://browser/skin/window-controls/minimize.svg) !important }
> .titlebar-max{ list-style-image: url(chrome://browser/skin/window-controls/maximize.svg) !important }
> .titlebar-restore{ list-style-image: url(chrome://browser/skin/window-controls/restore.svg) !important }
> ```
> 
>     * Then restart your firefox

thank you so much!!

**Comment by WildByDesign** [comment]
Apparently Firefox 117 (in my testing so far) has fixed the titlebar issues and the custom theme userChrome.css is no longer needed.

Firefox 117 seems to have also fixed SystemColors-related bugs in many other areas such as drop down menus, forms, etc.

Lots of improvements for use with custom Windows themes.

The big downside seems to be that Firefox removed the ability for transparent titlebar and therefore no Mica anymore.
