### ISSUE TITLE
MS Office Applications turn completely black

### ISSUE THREAD

**Issue by impaulstor** [Rectify11/Installer#217]
### Description

MS Word page, MS Excel workbook and other parts of MS Office applications becomes black when using Rectify 11 Dark with Mica.

### Steps To Reproduce

Install Rectify 11 Dark theme from RectifyControlCenter.
Open MS Word or MS Excel, create new document.

### Rectify11 Version

Version 3.0 RP3

### Windows Version

Windows 11 Pro 21H2

### Logs

![image](https://github.com/Rectify11/Installer/assets/74101138/d4d552af-41b7-449b-a680-db4af62d76e1)
![image](https://github.com/Rectify11/Installer/assets/74101138/9f9c3fea-2426-4ec6-8a3f-1795c3397556)

**Comment by rounk-ctrl** [comment]
#175
