### ISSUE TITLE
No description of what this software actually does

### ISSUE THREAD

**Issue by diamondavocado** [Rectify11/Installer#218]
### Description

Neither the GitHub repo nor the website describes what changes this software's going to make to your system.

Why would the authors expect anyone to install it before providing this information?

### Steps To Reproduce

1. Visit https://rectify11.net/
2. Scratch head

### Rectify11 Version

None

### Windows Version

None

### Logs

None

**Comment by diamondavocado** [comment]
More discussion of this issue at https://news.ycombinator.com/item?id=37099626

**Comment by MishaProductions** [comment]
I slightly changed the website to make it more clear what Rectify11 does
