### ISSUE TITLE
Control center having white UI sections

### ISSUE THREAD

**Issue by SomeoneCalledAdrian** [Rectify11/Installer#219]
### Description

_### **[FIXED]**_
It happens with both dark and dark with mica themes, it was originally working fine until it suddenly showed white sections i dont know why or how but it is quite annoying as you cant read text under the bugged areas (cus the text are "dark mode adjusted" and or white and the bugged are's background color being, suprise,  w h i t e
i know i am using a windows insider build but the problem was there before i even switched to using it... so yeah :)

![Screenshot (80)](https://github.com/Rectify11/Installer/assets/127946015/3d925f4c-ee93-4bba-88af-b3faafacef02)
![Screenshot (81)](https://github.com/Rectify11/Installer/assets/127946015/ab851f67-f849-4947-94b4-17c0096ee86c)

### Steps To Reproduce

open control center :)

### Rectify11 Version

3.0 rp3

### Windows Version

Windows 11 23h2 22631.2191

### Logs

no logs, since there is no "errors"

**Comment by WinExperiments** [comment]
You need to install System icons to fix the white bar

**Comment by rounk-ctrl** [comment]
patch shell32.dll.mun in Icons -> Basic

**Comment by SomeoneCalledAdrian** [comment]
so... i need to do that in the installer? but when i opened the installer it didnt show there was an option to "patch she;;32.dll.mun" and i installed the system icons already...

**Comment by SomeoneCalledAdrian** [comment]
ok its fixed so basically i have to reinstall the icons as the old ones got messed up lol
