### ISSUE TITLE
File Explorer: Font color matches background regardless of color\theme

### ISSUE THREAD

**Issue by rolltidehero** [Rectify11/Installer#224]
### **Some things I have tried:**

```
- Restarted Explorer
- Rebooted
- Changed theme from Windows 11
- Changed accent colors
- Changed to light mode (same thing but now the text is white)
- Enabled Contrast mode
- Created a new user profile
- Changed theme from Rectiffy11 Control Center
- I attempted a System Restore but sadly, it keeps failing
```
### Any suggestions are appreciated. Thanks!

![image](https://github.com/Rectify11/Installer/assets/11590510/f8ce3938-0418-4d50-9e81-4f6046265231)
![image](https://github.com/Rectify11/Installer/assets/11590510/771e2ed4-ef44-4073-9887-518cedfb1f4e)

### **This third image just shows how it looks normal whenever I take a screenshot for some reason**
![image](https://github.com/Rectify11/Installer/assets/11590510/7e2ab504-20ee-453a-ac82-7069bfb58393)

**Comment by Typical0** [comment]
reapply the Dark with Mica msstyles with themetool, ig

**Comment by rolltidehero** [comment]
> reapply the Dark with Mica msstyles with themetool, ig

No luck :(

**Comment by rounk-ctrl** [comment]
hdr?

**Comment by ed1fy** [comment]
same issue on my HDR enabled monitor
