### ISSUE TITLE
Disk Management Querying Window

### ISSUE THREAD

**Issue by PranavEWWFrwp** [Rectify11/Installer#225]
### Description

The Window that shows that Windows is querying the volume for available shrinkable space has some odd icon (maybe it can be a picturebox control). Attaching the screenshot for reference
![Screenshot (18)](https://github.com/Rectify11/Installer/assets/96933329/0596f7fe-1a2f-4805-ad97-30029d9ad959)

### Steps To Reproduce

Shrink any volume through diskmgmt.msc

### Rectify11 Version

3.0 RC1

### Windows Version

22621.2134

### Logs

There aren't any logs for this

**Comment by rounk-ctrl** [comment]
we cant do anything
