### ISSUE TITLE
Files Copied To C:\Windows\Rectify11 Prior To Installation

### ISSUE THREAD

**Issue by WildByDesign** [Rectify11/Installer#226]
### Description

When you first execute `Rectify11Installer.exe`, the `C:\Windows\Rectify11` directory is created and two files are copied there before choosing to proceed with installation.

The files are as follows:
```
C:
└───Windows
    └───Rectify11
            Dark.msstyles
            light.msstyles
```

Those msstyles likely have no reason to be in this directory anyway. Also, they are older versions of the msstyles. Also, no files should be copied prior to choosing to proceed with install.

This is clearly a minor bug. But I wanted to mention it anyway.

### Steps To Reproduce

- Execute Rectify11Installer.exe
- Do not proceed with installation
- Notice that files are copied

### Rectify11 Version

3.0 RC2

### Windows Version

Windows 11 22H2

### Logs

Details above.

**Comment by rounk-ctrl** [comment]
its not a bug, those are used by the installer

**Comment by WildByDesign** [comment]
I guess the part that I don’t understand is why it is copying msstyles that were last updated approximately 8 months ago to C:\Windows\Rectify11. These ones are outdated.

The msstyles that are copied to Resources\Themes are current though, as expected.

**Comment by rounk-ctrl** [comment]
its used for rendering the controls in the installer

**Comment by WildByDesign** [comment]
I didn’t realize that, my bad. That makes sense. I will close this issue.
