### ISSUE TITLE
Changing colors in File Explorer..

### ISSUE THREAD

**Issue by VitalSkib** [Rectify11/Installer#227]
Hi. 
Not a bug, but a question if you don't mind. 
Does anyone know what this panel in File Explorer is called? 
I want to change the background color of this panel using the msstyleEditor, but don't know what I should search for. 
Thanks in advance.

![explorer](https://github.com/Rectify11/Installer/assets/43848892/4c97a681-0a16-4a0a-bb4a-2d11a2788278)

**Comment by rounk-ctrl** [comment]
you cant, its hardcoded since it uses XAML.

**Comment by VitalSkib** [comment]
> you cant, its hardcoded since it uses XAML.

Oh bummer.. 
Thank you very much for the information.
