### ISSUE TITLE
Installer cannot create a system restore point if there are no restore points

### ISSUE THREAD

**Issue by Typical0** [Rectify11/Installer#228]
### Description

As stated in the title, Installer cannot make a system restore point if a one doesn't exist already. After 15-20 minutes the installer might reboot and make no changes to the install.

### Steps To Reproduce

1. Download RC2 on a system with no restore points.
2. Open it up and select "Install"
3. Select any option and click "Next"

### Rectify11 Version

v3.0 RC2

### Windows Version

Windows 11 23H2 22631.2134

### Logs

═════════════════════════════
START: 
Rectify11 Version: 3.0.40.0
═════════════════════════════

**Comment by xverge** [comment]
Does it still happen if you have restore points enabled but none exist?

**Comment by Typical0** [comment]
iirc this was the reason of the issue
