### ISSUE TITLE
Rectify phase 2 error

### ISSUE THREAD

**Issue by kameno22** [Rectify11/Installer#229]
### Description

Exception unknown error when patching system icons (updating the previous install)

### Steps To Reproduce

it should not give error

### Rectify11 Version

v3.0 RC2

### Windows Version

Windows 11 22621.1992

### Logs

![sada](https://github.com/Rectify11/Installer/assets/98833613/e24561dc-a00b-4322-9ae8-09b7615f82c8)

**Comment by rounk-ctrl** [comment]
how tf does this even happen
file disappeared???

**Comment by Basic6969** [comment]
> how tf does this even happen file disappeared???

no idea 🤷‍♂️

**Comment by Basic6969** [comment]
any fix?

**Comment by rounk-ctrl** [comment]
ill add a fix later

**Comment by Basic6969** [comment]
> ill add a fix later

![image](https://github.com/Rectify11/Installer/assets/98833613/a03772fe-ede9-45d8-a1c1-47b5a43ecfc4)
the file is present after install

**Comment by kameno22** [comment]
any fix yet?
