### ISSUE TITLE
(Question) Which one is safe to install on Windows 11 Canary Builds

### ISSUE THREAD

**Issue by foursplaysroblox** [Rectify11/Installer#230]
Which option is safe to install because I am scared of bricking my Windows 11 canary build
![image](https://github.com/Rectify11/Installer/assets/82078139/de138783-856c-4219-8bf3-892e45a6cc8b)

**Comment by ksajolaer** [comment]
Then don’t install it, what’s the problem? Rectify dev suggest to install it on 22H2 Stable.

**Comment by piotr25691** [comment]
> i'm on dev and it work fine you just have to re-run the installer every time you update to new build

same in beta, just you run the installer less often
