### ISSUE TITLE
Rectify VS Eac

### ISSUE THREAD

**Issue by kameno22** [Rectify11/Installer#231]
### Description

After installing rectify it broke eac games even on new install it doesnt work anymore

### Steps To Reproduce

It should not fight with it :')

### Rectify11 Version

v3.0 RC2

### Windows Version

Windows 11 22621.1992

### Logs

![eac](https://github.com/Rectify11/Installer/assets/98833613/994e9cb1-a7ea-4f40-82ef-f7e9c2256801)
![image](https://github.com/Rectify11/Installer/assets/98833613/868c02f4-1fd2-46f3-b5d8-6a606880c032)

**Comment by WinExperiments** [comment]
Type the following command in CMD:
sfc /scanfile=C:\Windows\System32\Faultrep.dll, then press Enter. The game should launch.

**Comment by kameno22** [comment]
> 

nope doesnt work 
![image](https://github.com/Rectify11/Installer/assets/98833613/b3117253-5939-4e00-986d-7af404baf0e1)

**Comment by WinExperiments** [comment]
Try restarting your PC

**Comment by rounk-ctrl** [comment]
Uninstall everything and install only basic

**Comment by Typical0** [comment]
It will only remove icons from advanced files, rest will stay

**Comment by foursplaysroblox** [comment]
I have not experienced that so far

**Comment by kameno22** [comment]
> I have not experienced that so far

Some games do not all
