### ISSUE TITLE
Black Spots on text in applications that dont normally have a dark theme

### ISSUE THREAD

**Issue by Findyourlimits** [Rectify11/Installer#233]
### Description

Black patches on some applications like Device Manager
![Screenshot 2023-08-20 121301](https://github.com/Rectify11/Installer/assets/142724758/dad9c677-8c1c-44a3-8bde-d761a9642d85)

### Steps To Reproduce

Open an application that doesnt normally have a dark theme

### Rectify11 Version

3.0.40.0

### Windows Version

Windows 11 22H2 22621.521

### Logs

none

**Comment by WinExperiments** [comment]
This only happens if you use transparency in the windows. If you use the standard Rectify11 dark theme, these won't appear.

**Comment by Findyourlimits** [comment]
thanks
