### ISSUE TITLE
File Explorer blow tittle has no mica and has a pitch black background (Usability of the file explorer is not affected though) 

### ISSUE THREAD

**Issue by blueciffer56** [Rectify11/Installer#235]
### Description

Title.

### Steps To Reproduce

Step 1. Set dark theme with mica in Rectify11 control center
Step 2. Open File Explorer 

### Rectify11 Version

Version 3..0.24.0

### Windows Version

Windows 11 22H2 22621.2134

### Logs

<img width="1128" alt="Screenshot 2023-08-20 164046" src="https://github.com/Rectify11/Installer/assets/102803783/4d685c3f-ddc7-45aa-b4b2-a7ffffaa1df1">

**Comment by kameno22** [comment]
is mica for everyone installed and running?

**Comment by piotr25691** [comment]
if the explorer turns black from the mica effect it means rectify11's modified files have been overwritten by a windows update

try reinstalling rectify11 from either RC2, or the current actions build to resolve it

**Comment by blueciffer56** [comment]
> is mica for everyone installed and running?

yes

**Comment by kameno22** [comment]
> > is mica for everyone installed and running?
> 
> yes

can you send ss of the mica config of global and explorer?

**Comment by piotr25691** [comment]
> > > is mica for everyone installed and running?
> > 
> > 
> > yes
> 
> can you send ss of the mica config of global and explorer?

most likely it was unchanged hence why i made a suggestion to reinstall RC2 again

**Comment by SmirbYrneh420** [comment]
https://github.com/micaforeveryone/explorerframe

**Comment by kameno22** [comment]
did you click on skip mfe installation when doing setup? if yes then reinstall it cauz its needed to work the theme.
