### ISSUE TITLE
Uninstalling rectify11

### ISSUE THREAD

**Issue by Emilia5691** [Rectify11/Installer#236]
### Description

I installed rectify11, but for personal reasons I had to unistall it soon after (using the same installer.exe, the last version on github). However I read online that there is a problem with the uninstaller and the only possible way to uninstall rectify11 is by reinstalling windows 11 completely. How do I make sure that I uninstalled it properly? Do I have to reinstall windows to be 100% sure? (If so, why don't you put a disclaimer in the installer?)

### Steps To Reproduce

Installing from github, using the installer.exe, unistalling using the installer.exe

### Rectify11 Version

3.0 RC2

### Windows Version

Windows 11 Version 22H2 x64 (KB4023057)

### Logs

my laptop is slightly slower than before

**Comment by rounk-ctrl** [comment]
just use the uninstaller, its stable in rc2

**Comment by Typical0** [comment]
a lot of the information on the internet that you can find on the internet is pretty much outdated (usually they document v2.5, rather than v3 RC)

**Comment by kajoken** [comment]
> 

Uninstaller crashed two times and I had to use system restore. Doesn't sound very stable to me.

**Comment by rounk-ctrl** [comment]
what was the error

**Comment by Arakhor** [comment]
Windows Settings app became really unresponsive after uninstalling, taking 2-3 seconds to change to another menu.  Ran installer again and problem is gone.  Uninstalled again and it's slow again.
Might be related to DPI scaling, when opened, the app starts at like 200% scaling, then adjusts to correct scaling after 1 second or less. This behavior only occurs after Rectify11 is uninstalled.

**Comment by rounk-ctrl** [comment]
how even

**Comment by Knigge111** [comment]
> ### Description
> I installed rectify11, but for personal reasons I had to unistall it soon after (using the same installer.exe, the last version on github). However I read online that there is a problem with the uninstaller and the only possible way to uninstall rectify11 is by reinstalling windows 11 completely. How do I make sure that I uninstalled it properly? Do I have to reinstall windows to be 100% sure? (If so, why don't you put a disclaimer in the installer?)
> 
> ### Steps To Reproduce
> Installing from github, using the installer.exe, unistalling using the installer.exe
> 
> ### Rectify11 Version
> 3.0 RC2
> 
> ### Windows Version
> Windows 11 Version 22H2 x64 (KB4023057)
> 
> ### Logs
> my laptop is slightly slower than before

Hello @Emilia5691 ,

i got a tip from a friend to the following and it´s worked for me:

so first of all:
delete the rectify folder from C: Windows --> it´s possible that a process will block the deletion. Use file lock smith to see with
and after that
apply the default dark mode --> settings designs
now run those one by one

sfc/scannow

DISM.exe /Online /Cleanup-image /Scanhealth

DISM.exe /Online /Cleanup-image /Restorehealth

DISM.exe /online /cleanup-image /startcomponentcleanup /resetbase

after the last command reboot windows.

**Comment by Knigge111** [comment]
> ### Description
> I installed rectify11, but for personal reasons I had to unistall it soon after (using the same installer.exe, the last version on github). However I read online that there is a problem with the uninstaller and the only possible way to uninstall rectify11 is by reinstalling windows 11 completely. How do I make sure that I uninstalled it properly? Do I have to reinstall windows to be 100% sure? (If so, why don't you put a disclaimer in the installer?)
> 
> ### Steps To Reproduce
> Installing from github, using the installer.exe, unistalling using the installer.exe
> 
> ### Rectify11 Version
> 3.0 RC2
> 
> ### Windows Version
> Windows 11 Version 22H2 x64 (KB4023057)
> 
> ### Logs
> my laptop is slightly slower than before

Hello @Emilia5691 ,

i got a tip from a friend to the following and it´s worked for me:

so first of all:
delete the rectify folder from C: Windows --> it´s possible that a process will block the deletion. Use file lock smith to see with
and after that
apply the default dark mode --> settings designs
now run those one by one

sfc/scannow

DISM.exe /Online /Cleanup-image /Scanhealth

DISM.exe /Online /Cleanup-image /Restorehealth

DISM.exe /online /cleanup-image /startcomponentcleanup /resetbase

**Comment by rounk-ctrl** [comment]
or just use system restore, since rc2 creates one

**Comment by piotr25691** [comment]
> > ### Description
> > I installed rectify11, but for personal reasons I had to unistall it soon after (using the same installer.exe, the last version on github). However I read online that there is a problem with the uninstaller and the only possible way to uninstall rectify11 is by reinstalling windows 11 completely. How do I make sure that I uninstalled it properly? Do I have to reinstall windows to be 100% sure? (If so, why don't you put a disclaimer in the installer?)
> > ### Steps To Reproduce
> > Installing from github, using the installer.exe, unistalling using the installer.exe
> > ### Rectify11 Version
> > 3.0 RC2
> > ### Windows Version
> > Windows 11 Version 22H2 x64 (KB4023057)
> > ### Logs
> > my laptop is slightly slower than before
> 
> Hello @Emilia5691 ,
> 
> i got a tip from a friend to the following and it´s worked for me:
> 
> so first of all: delete the rectify folder from C: Windows --> it´s possible that a process will block the deletion. Use file lock smith to see with and after that apply the default dark mode --> settings designs now run those one by one
> 
> sfc/scannow
> 
> DISM.exe /Online /Cleanup-image /Scanhealth
> 
> DISM.exe /Online /Cleanup-image /Restorehealth
> 
> DISM.exe /online /cleanup-image /startcomponentcleanup /resetbase
> 
> after the last command reboot windows.

this method is also a good no-restore point way to just replace all Rectify11 files with originals, giving you a clean Windows install again

**Comment by ggauzin** [comment]
> or just use system restore, since rc2 creates one

ik i'm kinda late for the party, but where acn i find the restore point, it doesn't show up anywhere

**Comment by wikiwedia** [comment]
> Windows Settings app became really unresponsive after uninstalling, taking 2-3 seconds to change to another menu. Ran installer again and problem is gone. Uninstalled again and it's slow again. Might be related to DPI scaling, when opened, the app starts at like 200% scaling, then adjusts to correct scaling after 1 second or less. This behavior only occurs after Rectify11 is uninstalled.

Hey, did you ever fix UWP apps being slow as hell? I've had this issue for like 5 months now and it's starting to get on my nerves because I did not make a restore point, and I do not want to reinstall windows because I will lose all of my app configurations.

**Comment by ggauzin** [comment]
select keep my personal files in windows restore menu

**Comment by CuteProgram** [comment]
Is it possible to just create a restore point before starting Recify11, and then use your restore point you created if you didn't like the app?
