### ISSUE TITLE
PLZ add an option to not create a restore point! 

### ISSUE THREAD

**Issue by sudo-000** [Rectify11/Installer#237]
I'm using tiny 11 at the moment and rectify 11 is refusing to install simply because tiny 11 removed the backing up function in windows completely. 
Please add an option to not create a restore point!

**Comment by legofanlovessayori** [comment]
or alternatively tell ntdev to readd system restore, since its kinda critical

**Comment by piotr25691** [comment]
why not just use debloated windows 11 instead of tiny11

i use it with rectify11 and it just works

**Comment by sudo-000** [comment]
> why not just use debloated windows 11 instead of tiny11
> 
> i use it with rectify11 and it just works

You mean rectify 11 2.5?
That's what I'm trying now. 
But I need someone to tell me how to get the powers hell ISE back. It's pretty useful for development.

**Comment by piotr25691** [comment]
> > why not just use debloated windows 11 instead of tiny11
> > i use it with rectify11 and it just works
> 
> You mean rectify 11 2.5? That's what I'm trying now. But I need someone to tell me how to get the powers hell ISE back. It's pretty useful for development.

debloated vanilla windows 11, not any custom windows distribution

**Comment by legofanlovessayori** [comment]
> But I need someone to tell me how to get the powers hell ISE back. It's pretty useful for development. 

add or remove optional features

**Comment by wealstarr** [comment]
> or alternatively tell ntdev to readd system restore, since its kinda critical

That equivalent of saying "You change for me, as I will not change for you"

**Comment by wealstarr** [comment]
> > That equivalent of saying "You change for me, as I will not change for you"
> 
> not r11s fault that ntdev chose to nuke system restore from tiny11

Different people with different use cases modify and configure their systems differently. R11 as a universal install package (meant for every Win 11 user) should take this into consideration.

Also, you don't get to decide what's "critical" for somebody else. I will rather not use R11 than use system restore.

**Comment by legofanlovessayori** [comment]
> > > That equivalent of saying "You change for me, as I will not change for you"
> > 
> > 
> > not r11s fault that ntdev chose to nuke system restore from tiny11
> 
> Different people with different use cases modify and configure their systems differently. R11 as a universal install package (meant for every Win 11 user) should take this into consideration.
> 
> Also, you don't get to decide what's "critical" for somebody else. I will rather not use R11 than use system restore.

then just don't use it
also blud seriously angry because of a decision that the team can't influence

**Comment by wealstarr** [comment]
> > > > That equivalent of saying "You change for me, as I will not change for you"
> > > 
> > > 
> > > not r11s fault that ntdev chose to nuke system restore from tiny11
> > 
> > 
> > Different people with different use cases modify and configure their systems differently. R11 as a universal install package (meant for every Win 11 user) should take this into consideration.
> > Also, you don't get to decide what's "critical" for somebody else. I will rather not use R11 than use system restore.
> 
> then just don't use it also blud seriously angry because of a decision that the team can't influence

Maybe you don't get the memo but mandatory system restore point creation feature is being mulled from the installer. So, you, like all other things, don't get to decide if I use it or not. Which I will.
