### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by addreeh** [Rectify11/Installer#238]
### Description

Checking if is a virus.

### Steps To Reproduce

I put exe in virtustotal.com

### Rectify11 Version

Latest

### Windows Version

Windows 11 23H2

### Logs

![image](https://github.com/Rectify11/Installer/assets/74270582/5b90f139-d4ce-41d0-a448-638c49278a10)

**Comment by rounk-ctrl** [comment]
no its not, you can check the source code

**Comment by WinExperiments** [comment]
False positive.
