### ISSUE TITLE
Yet another bug

### ISSUE THREAD

**Issue by kameno22** [Rectify11/Installer#239]
### Description

Explorer dying with load 🤷‍♂️ 

### Steps To Reproduce

Selection of large items>crashes

### Rectify11 Version

v3.0 RC2

### Windows Version

Windows 11 22621.1992

### Logs

![image](https://github.com/Rectify11/Installer/assets/98833613/fc8bb68d-a914-4702-9feb-2065609c3fa2)

**Comment by rounk-ctrl** [comment]
explorer's issue

**Comment by kameno22** [comment]
> explorer's issue

Fix wen
