### ISSUE TITLE
Uninstallation very unreliable

### ISSUE THREAD

**Issue by Gamesnic** [Rectify11/Installer#241]
### Description

I've tried Rectify11, and while it seems great, it had only UI bugs on my system, everywhere. I can probably give that fault to the fixed Windows themes that will interfere with Auto Dark/Light Mode.
So, I just wanted to uninstall it, but the uninstaller straight up stopped to do anything. It just says "Uninstalling themes" and won't do anything more. In Task Manager the process is using no resources other than 36MB RAM.

### Steps To Reproduce

Uninstall Rectify11.

### Rectify11 Version

v3.0 RC2

### Windows Version

Windows 11 22H2 Build 22621.2215

### Logs

![image](https://github.com/Rectify11/Installer/assets/49643487/4e57d955-74f9-49a2-aaef-ba7ef83df886)
![image](https://github.com/Rectify11/Installer/assets/49643487/02388eb5-5035-44ec-ba9d-075de598a049)

**Comment by piotr25691** [comment]
> ### Description
> I've tried Rectify11, and while it seems great, it had only UI bugs on my system, everywhere. I can probably give that fault to the fixed Windows themes that will interfere with Auto Dark/Light Mode. So, I just wanted to uninstall it, but the uninstaller straight up stopped to do anything. It just says "Uninstalling themes" and won't do anything more. In Task Manager the process is using no resources other than 36MB RAM.
> 
> ### Steps To Reproduce
> Uninstall Rectify11.
> 
> ### Rectify11 Version
> v3.0 RC2
> 
> ### Windows Version
> Windows 11 22H2 Build 22621.2215
> 
> ### Logs
> ![image](https://user-images.githubusercontent.com/49643487/263518444-4e57d955-74f9-49a2-aaef-ba7ef83df886.png) ![image](https://user-images.githubusercontent.com/49643487/263518458-02388eb5-5035-44ec-ba9d-075de598a049.png)

For me it works, but it’s throwing a “Process cannot access the file because it is being used by another process” when it tries to delete the Rectify11 directory, after clicking on Continue it just hangs

**Comment by holiq** [comment]
I experienced it too, so what should I do? End task from task manager or what?

**Comment by piotr25691** [comment]
> I experienced it too, so what should I do? End task from task manager or what?

Yeah that’s the only way, it has locked up.

Do SFC and DISM just in case to ensure you got rid of absolutely everything.

**Comment by Gamesnic** [comment]
> I experienced it too, so what should I do? End task from task manager or what?

I ended the task and got ready to use the system restore point created at the installation, but tried with using the uninstaller again and it actually picked up again where it left off. System runs as always now.

**Comment by rounk-ctrl** [comment]
fixed
