### ISSUE TITLE
Update Rectify11?

### ISSUE THREAD

**Issue by rennmaus-coder** [Rectify11/Installer#242]
Hi,
I am wondering if I should always update rectify11 to the latest version on github. If yes, do I just install the new version over to old one or do I have to unistall the old version first or something like that?

**Comment by piotr25691** [comment]
> Hi, I am wondering if I should always update rectify11 to the latest version on github. If yes, do I just install the new version over to old one or do I have to unistall the old version first or something like that?

I recommend uninstalling first, then you can reinstall the latest release
