### ISSUE TITLE
Some elements do not adopt the accent color.

### ISSUE THREAD

**Issue by ottozumkeller** [Rectify11/Installer#243]
### Description

After I installed Rectify11, set up everything and set a different accent color in the Windows settings, some elements like the textbox of the run dialog do not show the accent color correctly, but only a weird light red (see picture 1).
Maybe it is because I am on a Windows Insider build. Other elements are displayed correctly.

Also, some kind of tutorial e.g. in the wiki here on Github would be desirable, since even halfway experienced users can use a tutorial well. At least to get to know the basic functions and settings.

### Steps To Reproduce

1. Install Rectify11 and apply the Rectify11 Dark theme with Mica
2. In the Settings App under Personalization change your accent color.
3. Look at the Run-Dialog

### Rectify11 Version

Version 3.0 RC2

### Windows Version

Windows 11 22H2 Insider Build 23531.1001

### Logs

Picture 1
![image](https://github.com/Rectify11/Installer/assets/94012287/c30ab3ac-d669-417e-afe5-79a5a7efdf43)

**Comment by rounk-ctrl** [comment]
yeah its limited

**Comment by ottozumkeller** [comment]
Thanks for your reply. Even with this limitation and these small inconsistencies, these Windows components look absolutely beautiful in Dark mode with Mica design.
