### ISSUE TITLE
title bar

### ISSUE THREAD

**Issue by senolfndk** [Rectify11/Installer#245]
![Ekran görüntüsü 2023-08-28 183731](https://github.com/Rectify11/Installer/assets/52818836/20616583-a00d-4842-85cc-496f79a790e7)
how to make title bar dark

**Comment by rounk-ctrl** [comment]
micaforeveryone

**Comment by senolfndk** [comment]
😒

https://github.com/Rectify11/Installer/assets/52818836/c4a35efd-3864-4e16-a536-f1159f355353

**Comment by piotr25691** [comment]
change to "dark with mica" theme and tick use MicaForEveryone

if it doesn't work, reinstall Rectify11

**Comment by EDM115** [comment]
also make sure in Settings, Personalization, Colors that "Show accent color on title bars and window borders" is enabled
