### ISSUE TITLE
Msstyles get reset after restart

### ISSUE THREAD

**Issue by SonicFortress2** [Rectify11/Installer#246]
### Description

When trying to use Rectify11’s msstyles on the latest Windows 11 Dev and Beta builds, after a restart most msstyles based theming gets reset back to Microsoft’s msstyles.

### Steps To Reproduce

1) Install Rectify11 on a Dev or Beta insider machine, make sure themes is selected
2) Restart, and make sure themes are applied correctly
3) Restart again once themed are correctly installed.

Expected: Your msstyles will remain intact.
Result: Most areas get reverted, but some remain intact.

### Rectify11 Version

GitHub Actions commit 065e3a8

### Windows Version

Windows 11 22H2 Beta 22631.2262, Windows 11 Dev 23531

### Logs

Before the restart:
![IMG_6249](https://github.com/Rectify11/Installer/assets/128552117/67327c71-ab72-4f78-b538-ed4f2610b180)
![IMG_6250](https://github.com/Rectify11/Installer/assets/128552117/a71306b9-9f16-4f47-a97c-b2b2ac713ac0)
![IMG_6251](https://github.com/Rectify11/Installer/assets/128552117/a390dac3-60da-48a6-8a48-158a58f62226)
![IMG_6252](https://github.com/Rectify11/Installer/assets/128552117/d74a9f72-bc19-4ad3-a823-c1d48779b776)

After the restart:
![IMG_6253](https://github.com/Rectify11/Installer/assets/128552117/b58c9b05-a8d9-45b6-a107-0dfdfd9f358b)
![IMG_6254](https://github.com/Rectify11/Installer/assets/128552117/2626259a-a19c-4714-bc45-fb98f22c14ff)
![IMG_6255](https://github.com/Rectify11/Installer/assets/128552117/8b793400-fc09-4b27-a0a3-5237108c9758)
![IMG_6256](https://github.com/Rectify11/Installer/assets/128552117/bee9a463-21db-4ad9-8224-a7e11c8c2160)

**Comment by MishaProductions** [comment]
Enable logonui patching in themetool
