### ISSUE TITLE
[Question] Is this normal?

### ISSUE THREAD

**Issue by MGIsHeree** [Rectify11/Installer#248]
Loving this project so far, it does quite a good job at making everything better within the UI. However, I do notice that it takes quite longer to login/start to the operating system, notably during the login/logout & startup/shutdown process. Is this a normal behavior that's due to the UI patching?

**Comment by BestGuy-Windows-Tech-and-Fun** [comment]
No, this not from UI patching, the problem is this "RC" version, means (Rework Concept), this still under beta due V3.0 stable
i hope they fix it in next version

**Comment by piotr25691** [comment]
> No, this not from UI patching, the problem is this "RC" version, means (Rework Concept), this still under beta due V3.0 stable i hope they fix it in next version

doesn't RC mean "release candidate"?

**Comment by rounk-ctrl** [comment]
during login, it could be due to the new startup apps like MicaForEveryone

**Comment by MGIsHeree** [comment]
The thing is, I don't have MicaForEveryone installed, and I can assure my current startup apps doesn't cause this at all. It only happens after installing Rectify11.

**Comment by rounk-ctrl** [comment]
are you using themes?

**Comment by MGIsHeree** [comment]
Yes, happens to be Rectify11 Dark. I'm assuming it's because of that?

**Comment by rounk-ctrl** [comment]
yea, themetool causes the os to become slightly slower, since its a memory patcher for uxtheme

**Comment by MGIsHeree** [comment]
Alright yea I looked into it further and it seems this issues was really discussed kn the SecureUxTheme repo, thanks for the explanation.
