### ISSUE TITLE
VALORANT

### ISSUE THREAD

**Issue by yusufthechad** [Rectify11/Installer#250]
### Description

When playing valorant, sudden fps drops occur and the game becomes unplayable.

### Steps To Reproduce

Apply Rectify11
Open VALORANT

### Rectify11 Version

Latest action build 

### Windows Version

Windows 11 22H2 Build 22621.2215 Enterprise/Pro

### Logs

![VALORANT-Win64-Shipping_K7ZcQutNJr](https://github.com/Rectify11/Installer/assets/143716915/979e30b4-e5a4-4897-8fe1-55614177b9f6)
It happens when walking and shooting.

**Comment by yusufthechad** [comment]
Could it be a language problem ?

**Comment by WinExperiments** [comment]
It could be due to MicaForEveryone. Disable it and test again.

**Comment by yusufthechad** [comment]
Yes, It works now ty.
