### ISSUE TITLE
Do i need to reinstall it every update?

### ISSUE THREAD

**Issue by Fede2782** [Rectify11/Installer#252]
Do i need to reinstall Reactify11 after every Windows Update? Or new files are automatically patched?

**Comment by SmirbYrneh420** [comment]
For cumulative updates, no, Windows will not replace files.
For feature updates (or build updates in Dev and Canary channels), yes, you will have to reinstall Rectify11

**Comment by Fede2782** [comment]
I've Windows 11 Beta. Do I need to reinstall it after every non-cumulative update?
