### ISSUE TITLE
Mica for everyone disappeared after hiding it from tray

### ISSUE THREAD

**Issue by MooseZM** [Rectify11/Installer#255]
### Description

i hid MFE by right clicking in in the system tray and hiding it from the menu that showed up thinking i can just open it by looking up its name in the search but it's not showing up. I looked everywhere and i couldn't find it. I managed to find the installation folder from the task manager but opening micaforeveryone.exe launches the program (into the tray which i hid) and MicaForEveryone.UI.exe throws this error at me 
![image](https://github.com/Rectify11/Installer/assets/85148899/1cd5c229-0644-4190-89a0-1b5ff31beb96)

any way i can pull up the UI so i can change how certain programs interact with MFE?

### Steps To Reproduce

1-hide Mica For everyone from system tray
2-Can't open the UI anymore

### Rectify11 Version

V3 RC2

### Windows Version

Win 11 22h2

### Logs

![image](https://github.com/Rectify11/Installer/assets/85148899/5a06b2f9-90be-41cf-9896-58313f5e25bf)

**Comment by SmirbYrneh420** [comment]
did you run as admin???
try right clicking ---> run micaforeveryone.exe as admin
attempting to run micaforeveryone.ui.exe will result in the error you got, please do not try that

**Comment by MooseZM** [comment]
this fixed it, thanks
