### ISSUE TITLE
dark with mica theme have broken ui on some aplications

### ISSUE THREAD

**Issue by mahdi-limbo** [Rectify11/Installer#256]
### Description

Some apps have ugly white areas in dark mode with mica like softether vpn server manager or client, secure dns client and ... .

### Steps To Reproduce

1- install rectify 11 on windows 11
2- opening some apps like softether vpn client or softether vpn server manager.

### Rectify11 Version

V3 RC2

### Windows Version

Win 11 22h2 22621.2134

### Logs

![Screenshot 2023-09-02 080109](https://github.com/Rectify11/Installer/assets/138104312/35453bab-3cd5-4ae6-b6e4-d18d2a994cb3)
![Screenshot 2023-09-02 080130](https://github.com/Rectify11/Installer/assets/138104312/71ae593e-cdcd-489b-bc01-2e34f53efbc3)
![Screenshot 2023-09-02 080217](https://github.com/Rectify11/Installer/assets/138104312/a5c812ee-c0fc-41ac-8aba-2b22d2a2027a)
![Screenshot 2023-09-02 080258](https://github.com/Rectify11/Installer/assets/138104312/f8a8e072-8f95-4c02-94f8-c6ae1c2a5443)

**Comment by rounk-ctrl** [comment]
we cant do anything, its hardcoded by the app
