### ISSUE TITLE
Fails if any default windows/start menu folders or paths don't exist

### ISSUE THREAD

**Issue by exact** [Rectify11/Installer#260]
### Description

Add some exception handlers dawg

### Steps To Reproduce

run the app

### Rectify11 Version

latest

### Windows Version

22h2

### Logs

lol

**Comment by exact** [comment]
like srsly tho i wanna like this tool but the fact it messed up everything, doesn't even detect it's installed now or has the uninstall button available, I don't know exactly what you're doing with start menu folders & alike but the fact it can just fail and the entire function stops and the app is stuck is kinda ridiculous to me

**Comment by rounk-ctrl** [comment]
shi my bad
