### ISSUE TITLE
With Rectify11 installed, my accent color is changing randomly

### ISSUE THREAD

**Issue by dcorbe** [Rectify11/Installer#261]
### Description

My accent color changes at random.   While not annoying in and of itself, when it does change, it causes my whole screen to flash.  

### Steps To Reproduce

Install Ghost Spectre Superlite.  Then install Rectify11.

### Rectify11 Version

3.0rc2

### Windows Version

Windows 11 22H2 (Build 22621.1992)

### Logs

No log available.

**Comment by denisapain** [comment]
ghost spectre probably has something that changes the accent color, ask them for support if you can turn it off

**Comment by MishaProductions** [comment]
Closing to due to no response
