### ISSUE TITLE
Weird border around words on certain programs

### ISSUE THREAD

**Issue by MooseZM** [Rectify11/Installer#262]
### Description

Basically some words have a dark border behind them, I don't know what's the mutual thing between the different programs that causes this, it looks like this 
![image](https://github.com/Rectify11/Installer/assets/85148899/b4e2c5e8-f95c-4cdd-a001-4040b7bc77e2)
Internet Download Manager used to have this issue but i checked it now to screenshot it and it's somehow gone but i know for sure there are other programs with the same issue. Any way to fix it?

### Steps To Reproduce

Opening random programs

### Rectify11 Version

V3 RC2

### Windows Version

Win 11 22h2

### Logs

no logs

**Comment by SmirbYrneh420** [comment]
Micaforeveryone issue, unfortunately this bug cannot be fixed

**Comment by xverge** [comment]
https://github.com/Rectify11/Installer/issues/233#issuecomment-1685261486
