### ISSUE TITLE
mt4(meta trader 4) has some text issues.

### ISSUE THREAD

**Issue by eiliatmr** [Rectify11/Installer#264]
### Description

the app is very much works well but some texts are black on black/mica bg.
great app btw. love yall <3

### Steps To Reproduce

u can install the app from the web and see yourself.

### Rectify11 Version

3.0 RC2

### Windows Version

win11, build 22621.2215

### Logs

![image](https://github.com/Rectify11/Installer/assets/72338441/af7c64bc-e023-4356-8eb9-74a1db7600ac)

**Comment by SmirbYrneh420** [comment]
Unfortunately, there is no easy fix. These text colors are probably hardcoded
