### ISSUE TITLE
Why Developers Rectify11 Added Virus in Rectify11...

### ISSUE THREAD

**Issue by XNEOFF** [Rectify11/Installer#265]
### Description

**i just installed Rectify11 and make my pc very slow... and i upload the rectify11 on virustotal it says 5 security vendors and no** **sandboxes flagged this file as malicious if you don't believe me then see** **"https://www.virustotal.com/gui/file/6165118b41ba4a609bb05dded3e261484fc27eba1ffdfd6f7aa0366a3852acd1"**

**Results VirusScan...** 

**Security vendors' analysis**

**Cybereason
 | Malicious.c2ea27**
**Cylance | Unsafe**
**Gridinsoft (no cloud) | Ransom.Win64.Gen.bot**
**Rising | Trojan.Generic@AI.83 (RDML:Vs34qqYB3IW8W5lj6ctLgg)**
![Web capture_7-9-2023_23338_www virustotal com](https://github.com/Rectify11/Installer/assets/111242581/a2e38d48-6895-47c4-b488-5ee19f3de682)
![Web capture_7-9-2023_233143_www virustotal com](https://github.com/Rectify11/Installer/assets/111242581/22d7dd8a-ca34-492c-ab85-cc7a25a5daf4)
![Web capture_7-9-2023_233019_www virustotal com](https://github.com/Rectify11/Installer/assets/111242581/fcd67f1b-4b4e-4330-abec-47f3768684cd)

### Steps To Reproduce

**i just installed Rectify11 and make my pc very slow... and i upload the rectify11 on virustotal it says 5 security vendors and no** **sandboxes flagged this file as malicious if you don't believe me then see** **"https://www.virustotal.com/gui/file/6165118b41ba4a609bb05dded3e261484fc27eba1ffdfd6f7aa0366a3852acd1"**

**Results VirusScan...** 

**Security vendors' analysis**

**Cybereason
 | Malicious.c2ea27**
**Cylance | Unsafe**
**Gridinsoft (no cloud) | Ransom.Win64.Gen.bot**
**Rising | Trojan.Generic@AI.83 (RDML:Vs34qqYB3IW8W5lj6ctLgg)**
![Web capture_7-9-2023_23338_www virustotal com](https://github.com/Rectify11/Installer/assets/111242581/a2e38d48-6895-47c4-b488-5ee19f3de682)
![Web capture_7-9-2023_233143_www virustotal com](https://github.com/Rectify11/Installer/assets/111242581/22d7dd8a-ca34-492c-ab85-cc7a25a5daf4)
![Web capture_7-9-2023_233019_www virustotal com](https://github.com/Rectify11/Installer/assets/111242581/fcd67f1b-4b4e-4330-abec-47f3768684cd)

### Rectify11 Version

V3.0 RC2

### Windows Version

Windows11 22H2 22621.2215

### Logs

**i just installed Rectify11 and make my pc very slow... and i upload the rectify11 on virustotal it says 5 security vendors and no** **sandboxes flagged this file as malicious if you don't believe me then see** **"https://www.virustotal.com/gui/file/6165118b41ba4a609bb05dded3e261484fc27eba1ffdfd6f7aa0366a3852acd1"**

**Results VirusScan...** 

**Security vendors' analysis**

**Cybereason
 | Malicious.c2ea27**
**Cylance | Unsafe**
**Gridinsoft (no cloud) | Ransom.Win64.Gen.bot**
**Rising | Trojan.Generic@AI.83 (RDML:Vs34qqYB3IW8W5lj6ctLgg)**
![Web capture_7-9-2023_23338_www virustotal com](https://github.com/Rectify11/Installer/assets/111242581/a2e38d48-6895-47c4-b488-5ee19f3de682)
![Web capture_7-9-2023_233143_www virustotal com](https://github.com/Rectify11/Installer/assets/111242581/22d7dd8a-ca34-492c-ab85-cc7a25a5daf4)
![Web capture_7-9-2023_233019_www virustotal com](https://github.com/Rectify11/Installer/assets/111242581/fcd67f1b-4b4e-4330-abec-47f3768684cd)

**Comment by YahyaIDC** [comment]
![Screenshot_20230908-113944](https://github.com/Rectify11/Installer/assets/144433508/1df518f2-3cf8-4b84-9ae5-e64117463df0)

You should've know Rectify11 still have no signature, sometimes, someone can create malware on it, please be careful about install someone legit, also, no, this not a virus, Since it still have no signature, devs aware there no viruses on their software, in-public, yes, it is virus, please wait until the stable version, this still underdevelopment if you didn't know, it still have bugs at MSSTYLE and bug at try color, so please install it at your risk, my final thoughts about Rectify11 is virus or not, I would say "no, it doesn't"
Thanks for your feedback and have a nice day, stay safe my mate! 🙏

**Comment by XNEOFF** [comment]
oh okay I'm waiting stable version and please sign rectify11 on stable version

**Comment by rounk-ctrl** [comment]
gimme money to buy a cert

**Comment by legofanlovessayori** [comment]
you can literally check the code if it contains viruses, jesus

also a metric ton of custom made open source apps get false flagged by antivirus software so its kind of typical

**Comment by MishaProductions** [comment]
A signature costs $200 every 6 months
