### ISSUE TITLE
Problem with close, minimize and maximize buttons on the new Outlook app

### ISSUE THREAD

**Issue by AdityaKKhullar** [Rectify11/Installer#266]
### Description

Hey so uh I recently installed Rectify11 on my fresh Windows installation and it works very well with most apps except I've noticed an issue with the new outlook app on Windows 11.
The Rectify11 and the Outlook's own close, minimize buttons overlap each other. It's not something major, but just doesn't look good.

### Steps To Reproduce

Install Rectify11 as you normally would.

### Rectify11 Version

Version 3.0

### Windows Version

Windows 11 Enterprise 22H2 22621

### Logs

![image](https://github.com/Rectify11/Installer/assets/72785876/e024fcdd-ce52-4b0e-b65a-a48951880860)

**Comment by WinExperiments** [comment]
Does it happen with Rectify11's light theme?

**Comment by brenio55** [comment]
I'm also experiencing this issue

**Comment by AdityaKKhullar** [comment]
Yeah it does happen for me

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by AdityaKKhullar** [comment]
Yeah maybe the devs will fix it the next update

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by es1228** [comment]
I have this issue too, I fixed it by opening mica for everyone and adding a process rule for olk.exe (outlook) and turning off extend frame into client area.
