### ISSUE TITLE
No Icons ever get patched

### ISSUE THREAD

**Issue by wealstarr** [Rectify11/Installer#269]
### Description

OS: Windows 11 22H2 x64
Rectify 11 RC 3 (latest)

NO Icons anywhere on the system change.

### Steps To Reproduce

Installer works fine, no errors, can see the files being patched/replaced etc in terminal window.

### Rectify11 Version

Version 3 RC 3

### Windows Version

Windows 11 22H2

### Logs

stock windows icons stays the same .

**Comment by Typical0** [comment]
Could you specify the version? RC3 hasn't been released.

**Comment by wealstarr** [comment]
Apologies, it was RC 2

**Comment by MishaProductions** [comment]
Closing as this should be fixed
