### ISSUE TITLE
In the control panel these icons are not rectified

### ISSUE THREAD

**Issue by foursplaysroblox** [Rectify11/Installer#271]
### Description

The laptop closing lid and the power button icons are not rectified

### Steps To Reproduce

go to control panel, then hardware, then power options then click chose what the power buttons do

### Rectify11 Version

3.0 rc2

### Windows Version

Windows 11 Home Version 22H2 build	22621.2283 

### Logs

![image](https://github.com/Rectify11/Installer/assets/82078139/75ada202-a340-4493-b6a6-93d3f859b030)

**Comment by BetterWin11Project** [comment]
uhh why are you using rp3 (release PREVIEW(?!) 3). i would go to actions tab and download the latest

**Comment by foursplaysroblox** [comment]
what is wrong with using rp3

**Comment by Typical0** [comment]
its severely outdated

**Comment by BetterWin11Project** [comment]
download a build from the github actions

**Comment by foursplaysroblox** [comment]
I was mistaken

**Comment by rounk-ctrl** [comment]
not rectified due to anticheats
