### ISSUE TITLE
Add drag-n-drop to address bar back to Win11

### ISSUE THREAD

**Issue by beefufo** [Rectify11/Installer#278]
### Description

In the recent update, Microsoft removed yet another drag-n-drop function, this time with the address bar in the revamped explorer. It would be amazing if you guys added that functionality back to win11. Please, I am going insane! (I know I can just roll back, but its not like they didn't add a bunch of new stuff to the update), I'm sure many people will appreciate this addition!

### Steps To Reproduce

Update, Try to drag a file to a previous folder in the new Explorer. 

### Rectify11 Version

-- 

### Windows Version

22621.2361

### Logs

--

**Comment by Typical0** [comment]
This isn't a Rectify11 issue.

**Comment by beefufo** [comment]
> This isn't a Rectify11 issue.

It is now! Fixing inconsistencies is kind of the Rectify11 thing, right? 

1.Microsoft created the inconsistency by removing drag-n-drop for taskbar

2. They put it back, fixing inconsistency.

3. They removed drag-n-drop for address bar, making the inconsistency again.

4. Rectify11 may or may not be able to add it back. They should try!

**Comment by RTFTR** [comment]
Rectify11 can't modify XAML islands on File Explorer

**Comment by beefufo** [comment]
> Rectify11 can't modify XAML islands on File Explorer

That sucks. I hope some kind of solution to this would come up.
