### ISSUE TITLE
Powershell Files not beeing recognised

### ISSUE THREAD

**Issue by UltraAlex00** [Rectify11/Installer#283]
### Description

only *.ps1 files are beeing recognised.

there are other file extensions that share the same icon:
*.psm1 - ps module files
*.psd1 - ps data files
... (you can see all if you go to the ise > file > save as)

also would love if you rectify the powershell_ise.exe, yup its still my main editor cuz I hate when VS Code puts { on the new line :)

### Steps To Reproduce

create a .psm1 or .psd1 file

### Rectify11 Version

v3.0 rp3

### Windows Version

Windows 11 Pro build 22621

### Logs

![image](https://github.com/Rectify11/Installer/assets/104384457/68c1623d-cec9-4043-85ae-7ca441e61fe4)

**Comment by rounk-ctrl** [comment]
fixed
