### ISSUE TITLE
MySQL Workbench font color in editing screen

### ISSUE THREAD

**Issue by Yeekoi** [Rectify11/Installer#284]
### Description

Font color inside the MySQL Workbench editing screen is the same as the color of the backdrop.

### Steps To Reproduce

1. Apply Rectify11 Dark theme with Mica, Install MySQL Workbench 8.0 CE and MySQL Server.

2. Go through installation, configure the server and after installation start MySQL Workbench.

3. login on your server and look.

### Rectify11 Version

v3.0 RC3

### Windows Version

Windows 11 22H2 22621.2361

### Logs

![Screenshot 2023-10-03 142557](https://github.com/Rectify11/Installer/assets/74985966/65eb91df-5b4b-4845-949b-338eb0244067)

**Comment by rounk-ctrl** [comment]
app's limitation, we cant do anything
