### ISSUE TITLE
Remote Desktop Connection - "More..." dialog does not appear

### ISSUE THREAD

**Issue by valnoxy** [Rectify11/Installer#285]
### Description

When I try to click on "More" under Local Resources in the RDP client, no window appears.

### Steps To Reproduce

1. Open Remote Desktop Connection
2. Switch to Local Resources
3. Click on More...

### Rectify11 Version

3.0 RC3

### Windows Version

Windows 11 22H2 22621.2283 & 23555

### Logs

![image](https://github.com/Rectify11/Installer/assets/53713528/b99303f2-2fdb-4847-97aa-3aa323c11a35)

**Comment by rounk-ctrl** [comment]
fixed
