### ISSUE TITLE
OneNote Dark Mode background is the wrong color

### ISSUE THREAD

**Issue by makinbacon21** [Rectify11/Installer#286]
### Description

Instead of the dark-ized version of the background that OneNote usually shows, a gray background appears instead--but with the dark mode white ink. This makes notes completely unreadable.

### Steps To Reproduce

Open OneNote and enable Dark Mode.

### Rectify11 Version

3.0 rc3

### Windows Version

Windows 11 22H2 22621.2361

### Logs

![image](https://github.com/Rectify11/Installer/assets/19865598/14c7d691-d061-429a-8bda-fe3c999abbc3)

**Comment by makinbacon21** [comment]
Update: the background just seems inverted from what it should be--see Colorful theme for example:
<img width="1200" alt="image" src="https://github.com/Rectify11/Installer/assets/19865598/f64fc333-0c79-4ee6-9b51-686a8593d7ea">

**Comment by es1228** [comment]
Try switching to dark gray for now instead of black and see if that works

**Comment by makinbacon21** [comment]
dark gray was marginally better when I tried it but still very much not the right color palette

**Comment by es1228** [comment]
Wow that was a fast response, it’s probably a msstyles problem that needs fixing by the rectify11 developers.

**Comment by makinbacon21** [comment]
yea the one thing the GitHub phone app actually is good for is responding to issues lol. anyway yea, figured as much, hoping they'll see this and fix it. I would check it out but don't got the time at the moment.

**Comment by MishaProductions** [comment]
Try using the partial dark theme

**Comment by es1228** [comment]
Now as of version 3.0 the colours appear correct, even without the partial dark theme.

**Comment by makinbacon21** [comment]
thanks yall, I'll check it out later and report back

**Comment by es1228** [comment]
The only issue is that with the partial dark theme, you’re kind of sacrificing the full, consistent dark theme.
