### ISSUE TITLE
[I WAS WRONG ABOUT THIS] Missing title in enchanted context menus

### ISSUE THREAD

**Issue by Lime22H2** [Rectify11/Installer#289]
### Description

[I WAS WRONG ABOUT THIS, VERY SORRY TO RECTIFY11 DEVS ]The enchanted context menus should have "open with" title 

### Steps To Reproduce

You can make it as how you want, just make sure it is good

### Rectify11 Version

Latest version (RC3)

### Windows Version

Windows 11 23H2 Insider Preview build 25951.rs_prerelease.230908-1539

**Comment by ArbestRiAgain** [comment]
Rectify11 members, delete this issue

**Comment by Lime22H2** [comment]
> Rectify11 members, delete this issue

i was wrong abt this :(
