### ISSUE TITLE
Word, Excel and Access (in Office/Microsoft 365 apps) doesn't display colors correctly (Rectify11 Dark Theme)

### ISSUE THREAD

**Issue by Lime22H2** [Rectify11/Installer#290]
### Description

It was actually a mess, please fix this!

### Steps To Reproduce

idk how to

### Rectify11 Version

Latest version (RC3)

### Windows Version

Windows 11 22H2 Insider Preview build 25951.rs_prerelease.230908-1539

### Logs
Word:
<img width="960" alt="word" src="https://github.com/Rectify11/Installer/assets/129637929/9fbbd177-7bfe-425b-973b-d9085292f742">
<img width="960" alt="image" src="https://github.com/Rectify11/Installer/assets/129637929/d201bd3b-3dbf-4097-8eb4-770ee4694e5e">
<img width="960" alt="image" src="https://github.com/Rectify11/Installer/assets/129637929/f218b893-7172-4070-b5d9-0a61117f4a73">
Note: Only Word has the color bug in black mode

Acccess:
<img width="960" alt="access" src="https://github.com/Rectify11/Installer/assets/129637929/171c5b2f-4a1c-4172-b09d-efff7c860c61">
<img width="960" alt="image" src="https://github.com/Rectify11/Installer/assets/129637929/429af463-e7b2-478f-823a-d9b4abfa4f8c">
Excel:
<img width="960" alt="excel" src="https://github.com/Rectify11/Installer/assets/129637929/cebd1c94-bb8f-4adc-b6f5-b2babc01e9c0">
<img width="960" alt="image" src="https://github.com/Rectify11/Installer/assets/129637929/153680d8-ff41-424d-a63e-9ac4190f5da6">

Q: **Why don't you log an Outlook screenshot?** A: I couldn't launch Outlook.

**Comment by Lime22H2** [comment]
**`I noticed this bug since the 3.0 Release Preview 2`**

**Comment by EDM115** [comment]
https://github.com/Rectify11/Installer/issues/175#issuecomment-1672758054
