### ISSUE TITLE
Taskbar issue with the bundled build of NS Shell

### ISSUE THREAD

**Issue by Thisisauser6443** [Rectify11/Installer#293]
### Description

With **some** icons on the taskbar, trying to right-click on them, does not bring up the icon's context menu, _and instead opens Shell's context menu._ By "some" there was a specific cut-off as to where right-clicking was and was not bugged, at a fixed position irrelevant to the number of icons on the taskbar

https://github.com/Rectify11/Installer/assets/75092921/b4ecb172-342b-4223-94a3-7eba9781094d

_(If I'm being honest, I probably wouldn't have encountered this if my taskbar wasn't so cramped)_

However, I did a bit of research on this, and came across [#333](https://github.com/moudey/Shell/issues/333) in its repo, and it seems like it was fixed in v1.9, though I'm obviously still running the bundled 1.8.1 from the installer, so this'll need upgrading

### Steps To Reproduce

1. Install R11, as you'd normally do, **explicitly making sure that either one of the `Extended Context Menus` options are selected**
2. After rebooting, find that the icon context menus are inaccessible, for a specific portion of the taskbar itself

### Rectify11 Version

Actions build #544 (77cae38), though I assume this also applies to all versions bundled with Shell 1.8.1 

### Windows Version

Windows 11 23H2 22631.2361 (Insider - Beta)

### Logs

None

**Comment by Thisisauser6443** [comment]
Seems to have fixed the taskbar issue, but that's also ended up breaking the desktop's context menus

**Comment by rounk-ctrl** [comment]
soo should i revert?

**Comment by rounk-ctrl** [comment]
i just tried, doesnt seem to work at all

**Comment by rounk-ctrl** [comment]
the config file is broken

**Comment by Thisisauser6443** [comment]
I did a bit more research in the repo, and there was something about re-registering it with `shell.exe -r -treat`, but that didn't exactly work out either

Might be worth reverting, but there's always just forcing classic context menus, too, in case someone is that desperate. The fluent design does end up applying there, but there's no blur

**Comment by rounk-ctrl** [comment]
fixed it
