### ISSUE TITLE
Uninstalling does not remove Rectify11 folder

### ISSUE THREAD

**Issue by denisapain** [Rectify11/Installer#295]
### Description

The uninstaller should remove the Rectify11 folder in the Windows folder, because if you want to install it again, it won't let you install the icons, and its bloating your system, about the performance eh?

### Steps To Reproduce

Install Rectify11 with systemicons and other things
Uninstall Rectify11
the rectify11 folder stays with the backups and rectify control center.

### Rectify11 Version

3.0 rc3

### Windows Version

Win11.22H2 - 22621.2361

### Logs

The folder stays in the windows directory after uninstalling.

**Comment by rounk-ctrl** [comment]
you need to uninstall everything

**Comment by denisapain** [comment]
> you need to uninstall everything

I uninstalled through the rectify installer.

**Comment by WildByDesign** [comment]
It used to remove everything but for the past 1-2 weeks the Actions builds haven’t been deleting the backup files at all. And therefore not deleting the Rectify11 folder either.

Now that I think about it, it’s more like 2-3 weeks. I never had time to pin down which code change caused it.

**Comment by rounk-ctrl** [comment]
it does for me

**Comment by WildByDesign** [comment]
Confirmed fixed after testing the most recent Actions build.
