### ISSUE TITLE
Steam install texts are light theme

### ISSUE THREAD

**Issue by panzer42** [Rectify11/Installer#297]
### Description

I wanted to install steam and the texts looked like this

### Steps To Reproduce

Download Steam
Open the exe file

### Rectify11 Version

Version: 3.0 (theme: dark with mica)

### Windows Version

Tiny11

### Logs

![image](https://github.com/Rectify11/Installer/assets/131333636/3b200237-0594-4ed0-a5af-6febd5bfe6a2)
![image](https://github.com/Rectify11/Installer/assets/131333636/83a93e4a-27a6-40b2-a1a0-69f618e9186b)

**Comment by es1228** [comment]
It’s because the colours are hardcoded, there is no fix.
