### ISSUE TITLE
Update to Nilesoft Shell 1.9

### ISSUE THREAD

**Issue by LoreSchaeffer** [Rectify11/Installer#298]
### Description

As stated by Nilesoft Shell's author, old version of the software has som bugs related to the taskbar where the menu when you right click on an app icon (when the app is reduced to icon) shows the menu of the taskbar and not the menu with the options of the app. In the newest version 1.9 this bug has been fixed.

### Steps To Reproduce

Right click on the icon of an app on the taskbar  that is reduced to icon

### Rectify11 Version

3.0 rc3

### Windows Version

Windows 11 Pro 22H2 - 22621.2361

### Logs

![image](https://github.com/Rectify11/Installer/assets/15457448/c73b2f8b-524c-4cd5-ae7c-7b9b13bc730a)
This is an example of clicking on the settings app. The menu shows the taskbar items

**Comment by Thisisauser6443** [comment]
The more recent Actions builds have it upgraded to 1.9, but it ended up breaking the fluent context menus on my end (#293)
