### ISSUE TITLE
[BUG] The icon on shutdown Windows window is squeezed

### ISSUE THREAD

**Issue by EDM115** [Rectify11/Installer#299]
### Description

On the shutdown window, the icon of the moon in the computer is probably a "landscape" one, but the container might be a square, and so the icon is squeezed to fit in

### Steps To Reproduce

- Go on your desktop
- Do Alt+F4

### Rectify11 Version

v3.0 RC3

### Windows Version

Windows 11 23H2 build 22631.2361

### Logs

![image](https://github.com/Rectify11/Installer/assets/82015596/fe1ccdc2-78ba-4be1-95ba-fac3048dceca)

**Comment by WinExperiments** [comment]
That's a 125% scaling issue not related to Rectify11. Here is it on 100%:
![image](https://github.com/Rectify11/Installer/assets/91428431/025e03eb-fde4-4218-b7dd-a8af3bfee57c)

**Comment by EDM115** [comment]
indeed :(
