### ISSUE TITLE
French translation not shown

### ISSUE THREAD

**Issue by RaphMar2021** [Rectify11/Installer#301]
### Description

I have a French Windows 11 system installed on my PC, and when i run the Rectify11 installer, it shows in English.

### Steps To Reproduce

Install & set the French language pack on your PC

### Rectify11 Version

Commit with message: "New partial dark theme"

### Windows Version

Windows 11 Pro Insider Preview v22H2 (build 10.0.23565.1000)

### Logs

![image](https://github.com/Rectify11/Installer/assets/81994075/80d74338-634a-4567-8346-00585d3bb99c)

**Comment by rounk-ctrl** [comment]
fixed

**Comment by EDM115** [comment]
not on the last step :  
![image](https://github.com/Rectify11/Installer/assets/82015596/989d6854-3b09-49df-9e05-b3e63b6e0492)
