### ISSUE TITLE
Rectify11 Control Center Bugs

### ISSUE THREAD

**Issue by WildByDesign** [Rectify11/Installer#304]
### Description

I see that you guys switched back to the old Rectify11 Control Center. I personally preferred the newer Control Panel version.

But anyway, I compiled the latest code for Rectify11 Control Center and wanted to point out a few minor things.

- Rectify11 Control Center doesn't have high DPI built-in.

- The Theme Names get cut off (drop-down box needs to be wider)

### Steps To Reproduce

Details in Description above.

Screenshot of Theme Names being cut off:

![Rectify11-CC](https://github.com/Rectify11/Installer/assets/26308319/0f4993f2-23b5-416a-9b11-57d24f7bbf74)

### Rectify11 Version

Latest code as of 2023-10-14

### Windows Version

Windows 11 23H2

### Logs

Screenshot above.

**Comment by rounk-ctrl** [comment]
well control panel version lacked features, and it will take time to implement them

**Comment by rounk-ctrl** [comment]
fixed dpi

**Comment by dzid26** [comment]
Why is the text the wrong color?
![image](https://github.com/Rectify11/Installer/assets/841061/e2fb735c-0615-456d-8575-55805337905a)

Also, before installing I could not see any text at all.  Only after opening the snipping tool, the texts would appear.
