### ISSUE TITLE
After 23H2, file explorer is not fully themed.

### ISSUE THREAD

**Issue by sumeshir26** [Rectify11/Installer#318]
### Description

The background of file explorer is not properly themed.

### Steps To Reproduce

Open File Explorer

### Rectify11 Version

3.0

### Windows Version

23H2 22631.2428

### Logs

![image](https://github.com/Rectify11/Installer/assets/68823982/2a533eb2-d550-44d0-b59a-b5491f1463d9)

**Comment by Typical0** [comment]
This is a fairly known issue, and to fix it, download ViveTool and type:
```
vivetool /disable /id:40729001
```

After restart, the issue should be fixed.

**Comment by sumeshir26** [comment]
> This is a fairly known issue, and to fix it, download ViveTool and type:
> 
> ```
> vivetool /disable /id:40729001
> ```
> 
> After restart, the issue should be fixed.

Thank you so much, sorry for the unnecessary issue.
