### ISSUE TITLE
"New > Shortcut" missing when using Enhanced Context Menus

### ISSUE THREAD

**Issue by MGIsHeree** [Rectify11/Installer#320]
### Description

The option to create a new shortcut is not present when using Enhanced Context Menus.

### Steps To Reproduce

1. Right click on the desktop.
2. Hover over "New".
3. Then notice the option to create a shortcut is missing, when it should be present.

### Rectify11 Version

Version: 3.0

### Windows Version

Windows 11 22H2 22621.2428

### Logs

![image](https://github.com/Rectify11/Installer/assets/51394649/43816aa9-e977-4200-9448-f270e71d4aaf)

**Comment by Mukul1127** [comment]
This is a default from Nilesoft Shell's config that seems to have been missed. Modify Nilesoft's modify.nss and remove the line relating to shortcuts

**Comment by MGIsHeree** [comment]
where is the directory of this file?

**Comment by MGIsHeree** [comment]
nvm I got it figured out, thanks!
