### ISSUE TITLE
Outlook E-Mails unreadable

### ISSUE THREAD

**Issue by Basecatcherz** [Rectify11/Installer#321]
### Description

E-Mails in Outlook 365 (classic, not the new Outlook) sometimes gets unreadable cause the theme sets backgreound and text to simmilar colors.

### Steps To Reproduce

Open E-Mails in Outlook that contain styled HTML

### Rectify11 Version

3.0

### Windows Version

Windows 11 23H2 (10.0.22631)

### Logs

![image](https://github.com/Rectify11/Installer/assets/20948255/5a81378a-eb7f-4884-ba09-5a737f438500)
![image](https://github.com/Rectify11/Installer/assets/20948255/f1d38c12-7e90-4341-abcd-e1e644f52f22)

**Comment by MishaProductions** [comment]
This is a bug with outlook, try using the partial dark theme.
