### ISSUE TITLE
Broken Themes

### ISSUE THREAD

**Issue by TestingUser1234567** [Rectify11/Installer#326]
### Description

When installing Rectify 11, When choosing dark theme, I noticed that some apps that have light theme and when you apply the dark theme, it breaks.

### Steps To Reproduce

First open an app that only has light theme ex. Uninstall Tool etc. And then apply dark theme, and then you will see that the application theme is broken

### Rectify11 Version

Rectify 11 V3

### Windows Version

Windows 11 Build 23565

### Logs
![Screenshot 2023-10-18 120119](https://github.com/Rectify11/Installer/assets/145440969/3b25c266-3639-4d23-8551-28b75fef8f10)

**Comment by MishaProductions** [comment]
Use the partial dark theme, as those apps have hardcoded colors
