### ISSUE TITLE
Window(s) Look Terrible Out of Focus

### ISSUE THREAD

**Issue by CE-Yazeed** [Rectify11/Installer#327]
### Description

As the title says, windows look terrible out of focus. How can I make it so that the focus effect is retained while out of focus and alternatively just have a border or anything of that sort appear to indicate the window is in focus? 
![image](https://github.com/Rectify11/Installer/assets/95697849/46d737c3-d8a3-472b-8027-7a9e29ca5d0d)

In focus:
![image](https://github.com/Rectify11/Installer/assets/95697849/057e4ccf-c451-46bb-8110-e215972ff153)

Out of focus:
![image](https://github.com/Rectify11/Installer/assets/95697849/8afb2753-e7c7-437a-841e-114c5d103741)

### Steps To Reproduce

![image](https://github.com/Rectify11/Installer/assets/95697849/2ec5ca7a-2782-41fd-a375-3140037e5f28)

![image](https://github.com/Rectify11/Installer/assets/95697849/34de7152-b34c-42a7-8c3f-9467259a59be)

### Rectify11 Version

Rectifyll Version: 3.0.48.0  + Mica For Everyone 1.3.0.0

### Windows Version

OS: Windows NT Build 1002621

### Logs

.

**Comment by EDM115** [comment]
the issue should probably go in [MicaForEveryone](https://github.com/MicaForEveryone/MicaForEveryone/)  
anyway I believe it's by design, from what I know Windows doesn't allow for nested levels of transparency, so it's only applied to the focused window (to save energy on laptops ? idk)
