### ISSUE TITLE
Apply theme after reboot

### ISSUE THREAD

**Issue by alanthast0s** [Rectify11/Installer#328]
### Description

I have to open Rectify Control Center and apply theme every time I reboot or boot after shutdown
First screenshot is after I apply theme and second screenshot is after reboot

### Steps To Reproduce

Reboot Windows

### Rectify11 Version

Version 3.0

### Windows Version

Windows 11 22H2 22621.2428

### Logs

![1](https://github.com/Rectify11/Installer/assets/143002488/d04bd13b-8a8f-4b00-a048-fbf6a3bc07f6)
![2](https://github.com/Rectify11/Installer/assets/143002488/7e53dc3b-1088-4989-b3ca-ac71735a74cc)

**Comment by MishaProductions** [comment]
Patch logonui in themetool
