### ISSUE TITLE
"Copy as Path" missing when using Enhanced Context Menus

### ISSUE THREAD

**Issue by RaspberryKitty1** [Rectify11/Installer#330]
### Description

The option to Copy a files path is not present when using Enhanced Context Menus.

Its a very nice thing in windows 11 I used a lot and would be nice to have again.

### Steps To Reproduce

1. Right Click on a file
2. notice the option to "Copy as path" is missing, when it should be present.

### Rectify11 Version

Version: 3.0

### Windows Version

Windows 11 Version 22H2 (0S Build 22621.2428)

### Logs

With Classic menu:
![image](https://github.com/Rectify11/Installer/assets/28585042/2421ed04-00ea-4674-bc1e-75d4a59dfbc1)

With Enhanced Context Menus:
![image](https://github.com/Rectify11/Installer/assets/28585042/28812aef-329b-4d78-a93f-1b049e98e4b7)

**Comment by Mukul1127** [comment]
This is probably because of Rectify11's custom config for nilesoft shell, tr removing enhanced context menus from Rectify11's installer and install from https://nilesoft.org/download
