### ISSUE TITLE
Dark Mode Bugs in Visual Studio

### ISSUE THREAD

**Issue by tee1234517** [Rectify11/Installer#332]
### Description

When you are trying to debug a WPF-App then for example the buttons show up for a second and then they disappear the same thing is happening with the title bar. The App works fine when i am starting the exe not in debug mode.

### Steps To Reproduce

Open Visual Studio open or make a WPF-Application and but a for example a button in there (i only tested it with a button) and start the application in debug mode.

### Rectify11 Version

Version 3.0.48.0

### Windows Version

WIndows 11 22635 Beta-Preview

### Logs

https://youtu.be/O3uS-vvWp9Q

**Comment by MishaProductions** [comment]
doesn't seem to be an R11 issue as the buttons render correctly before disappearing for whatever reason. Can you try changing your theme to the regular windows 11 theme and see if that changes anything?
