### ISSUE TITLE
ESET Antivirus unable to open or install after installing Rectify's "System icons - Advanced"

### ISSUE THREAD

**Issue by wbs-perso** [Rectify11/Installer#333]
### Description

I have been trying to install the latest version of Rectify11 alongside ESET, and for some unknown reason -that I was able to narrow down to the "Advanced" section of the System icons being patched/modified by Rectify11- every time this gets installed, ESET does refuses to open (when it's installed) and refuses to even install if it wasn't installed beforehand.

### Steps To Reproduce

1. Fresh Windows 11 install (fully updated)
2. Install ESET Antivirus
3. Install Rectify11 with the "**Advanced**" section of **System icons** checked
4. Reboot
5. ESET doesn't startup anymore and cannot be opened

OR

1. Fresh Windows 11 install (fully updated)
2. Install Rectify11 with the "**Advanced**" section of **System icons** checked
3. Reboot
4. Try to install ESET Antivirus
5. ESET's installation fails towards the end when its trying to launch its services

### Rectify11 Version

Version 3.0

### Windows Version

Windows 11 22H2 22621.2428

### Logs

I am unsure which event log to copy/share, please let me know if you need anything specific!

**Comment by WinExperiments** [comment]
Try patching each file individually until you see which file prevents ESET from launching.

**Comment by darthdemono** [comment]
Had this issue for a while. A Windows update occurred and now it's fine. Try /sfc commands, Might work.

**Comment by Mukul1127** [comment]
> Had this issue for a while. A Windows update occurred and now it's fine. Try /sfc commands, Might work.

The point is to use Rectify11 alongside ESET, sfc just reverts many of Rectify11's changese

**Comment by boromyr** [comment]
I also have the same problem with ESET, I only installed the icons.

**Comment by klinok64** [comment]
I am having the same issue with Rectify11 and ESET. I installed all options except for the icons as an experiment, and the same issue occurred.

**Comment by nickk289** [comment]
I have the same issue. After installing Rectify11, ESET stopped working. But when I uninstalled Rectify11 and restarted the PC, ESET automatically started working again.

**Comment by KloWhrhyde** [comment]
Same issue here. With or without advanced.

**Comment by REALMWTH** [comment]
Uncheck `msi.dll` from Advanced, this is the only library that prevents ESET from being loaded correctly.
