### ISSUE TITLE
Help me pls, i can't uninstall the app

### ISSUE THREAD

**Issue by ggauzin** [Rectify11/Installer#335]
### Description

![image](https://github.com/Rectify11/Installer/assets/128216038/03c61a69-41e1-4447-9537-b73b36a592fb)

### Steps To Reproduce

execute rectify11 installer, click uninstall, select anything, click next

### Rectify11 Version

3.0

### Windows Version

Win11 pro 23h2

### Logs

![image](https://github.com/Rectify11/Installer/assets/128216038/a859ed34-3241-4fd5-9e21-a00ec1421a83)

**Comment by ggauzin** [comment]
i have too much ui bugs and i wanna just get rid of it

**Comment by TuanDung0902** [comment]
> i have too much ui bugs and i wanna just get rid of it

You can uninstall it by go to Settings>Apps>Installed apps. Find Rectify 11 then click into 3 dots button in the right side then click uninstall. Next you follow the steps to uninstall it.

**Comment by es1228** [comment]
This is because you are running an old version, update to the latest stable version and try again.

**Comment by ggauzin** [comment]
> > i have too much ui bugs and i wanna just get rid of it
> 
> You can uninstall it by go to Settings>Apps>Installed apps. Find Rectify 11 then click into 3 dots button in the right side then click uninstall. Next you follow the steps to uninstall it.

next button does not work

**Comment by es1228** [comment]
> > This is because you are running an old version, update to the latest stable version and try again.
> 
> i am wtf

That isn’t the version 3.0 uninstaller, version 3.0 uninstaller is different. Try downloading the release on this github page called “Version 3.0” and try reinstalling/updating and then try to uninstall.
