### ISSUE TITLE
Icons bugs

### ISSUE THREAD

**Issue by UserNotfoundR** [Rectify11/Installer#336]
### Description

The system looks incredibly beautiful but the icons with folders inside are like this, I'm going to uninstall it. It could also be that my Windows is not compatible but it's working correctly, only the icons that are bugged
![image](https://github.com/Rectify11/Installer/assets/128847349/b8dff0e0-af50-4dcc-a338-befde55c8445)
I may not have seen that it is only for Windows 11

### Steps To Reproduce

None, I just installed everything and it's like this

### Rectify11 Version

3.0

### Windows Version

Windows 10 Pro 22H2 19045.3636

### Logs

![image](https://github.com/Rectify11/Installer/assets/128847349/abe52213-66ec-4732-a10f-da7414d0b241)

**Comment by TuanDung0902** [comment]
It is just a bug on folder icon or any other icon?

**Comment by TuanDung0902** [comment]
> ### Description
> 
> The system looks incredibly beautiful but the icons with folders inside are like this, I'm going to uninstall it. It could also be that my Windows is not compatible but it's working correctly, only the icons that are bugged
> ![image](https://github.com/Rectify11/Installer/assets/128847349/b8dff0e0-af50-4dcc-a338-befde55c8445)
> I may not have seen that it is only for Windows 11
> 
> ### Steps To Reproduce
> 
> None, I just installed everything and it's like this
> 
> ### Rectify11 Version
> 
> 3.0
> 
> ### Windows Version
> 
> Windows 10 Pro 22H2 19045.3636
> 
> ### Logs
> 
> ![image](https://github.com/Rectify11/Installer/assets/128847349/abe52213-66ec-4732-a10f-da7414d0b241)
> 

It is just a bug on folder icon or it having bug on any other icon?

**Comment by UserNotfoundR** [comment]
Apparently what I saw was only in the folders and when I went to uninstall the program it didn't remove the folder icons and I had to do it manually (those that were present on the desktop)

**Comment by TuanDung0902** [comment]
> Apparently what I saw was only in the folders and when I went to uninstall the program it didn't remove the folder icons and I had to do it manually (those that were present on the desktop)

I think you should reinstall the icon pack of Rectify11 by go to Rectify11 setup>choose Modify>uncheck icon box and then follow the installation. Next you run the setup and re-check the icon box just like normal install

**Comment by UserNotfoundR** [comment]
![image](https://github.com/Rectify11/Installer/assets/128847349/b62c8d06-6f79-440d-bfaf-9933d09873f0)
I'm going to install more when it already warns me about compatibility problems, would that be the problem?

**Comment by WinExperiments** [comment]
You are using Windows 10 which has the folder previews styled after its folder icons. When you install Rectify11 the folder icon changes but not the previews. Reinstalling Rectify11 won't fix it.

**Comment by TuanDung0902** [comment]
> ![image](https://github.com/Rectify11/Installer/assets/128847349/b62c8d06-6f79-440d-bfaf-9933d09873f0)
> I'm going to install more when it already warns me about compatibility problems, would that be the problem?
That maybe the reason cause bug in your folder icon, because Rectify11 is design specailly for Windows 11 and also because the Windows 10's folder icon is different from Windows 11's one.

**Comment by UserNotfoundR** [comment]
![image](https://github.com/Rectify11/Installer/assets/128847349/520f1031-104c-4a4c-aa3c-d63d39547f1d)
still the same thing.

**Comment by TuanDung0902** [comment]
> ![image](https://github.com/Rectify11/Installer/assets/128847349/520f1031-104c-4a4c-aa3c-d63d39547f1d)
> still the same thing.

If you still want to install Rectify11 on Windows 10 you can run the setup>click modify>expand the icon option>find the "imageres.dll" option and uncheck it. This will reverse the change to folder icon and folder icon will back to Windows 10's.
