### ISSUE TITLE
Control panel white areas after installing Rectify

### ISSUE THREAD

**Issue by toastiee** [Rectify11/Installer#337]
### Description

In the control panels application, white highlights appears, obscuring controls and hindering navigation. This persists even after following the user manual's instructions, indicating a potential rendering issue with the software. I've had this problem occur prior the latest update. 

### Steps To Reproduce

None as I've installed everything as per instruction.

### Rectify11 Version

3.0.48.0

### Windows Version

Windows 11 version 22H2 22621.2506

### Logs

This is what happens on the top of the control panel
![image](https://github.com/Rectify11/Installer/assets/103567701/f49c6764-7c9f-45f4-9e98-4fb63fce20c2)

This is what happens on the side of the control panel
![image](https://github.com/Rectify11/Installer/assets/103567701/f00b067a-e9b3-4abb-9e8d-4e1388bb739f)

**Comment by e-t-l** [comment]
How did you fix this?
