### ISSUE TITLE
Part of Explorer stays the old dark theme when applying mica

### ISSUE THREAD

**Issue by iPigTW** [Rectify11/Installer#338]
### Description

After applying "Rectify11 Dark theme with Mica" and open explorer. On any page only partial of explorer became mica theme.

### Steps To Reproduce

1.Apply "Rectify11 Dark theme with Mica"
2.Open explorer

### Rectify11 Version

3.0.48.0

### Windows Version

Windows 11 23H2 25982.1000

### Logs

![image](https://github.com/Rectify11/Installer/assets/49023948/2557b6bc-3ed3-4726-9518-8acae926a4ea)
![image](https://github.com/Rectify11/Installer/assets/49023948/5bcd86fc-c4e4-4094-b7d0-820851c8241b)

**Comment by SmirbYrneh420** [comment]
This is probably hard-coded UWP shell in explorer. Extremely hard to fix, if possible at all

**Comment by TuanDung0902** [comment]
> ### Description
> 
> After applying "Rectify11 Dark theme with Mica" and open explorer. On any page only partial of explorer became mica theme.
> 
> 
> 
> ### Steps To Reproduce
> 
> 1.Apply "Rectify11 Dark theme with Mica"
> 2.Open explorer
> 
> 
> ### Rectify11 Version
> 
> 3.0.48.0
> 
> ### Windows Version
> 
> Windows 11 23H2 25982.1000
> 
> ### Logs
> 
> ![image](https://github.com/Rectify11/Installer/assets/49023948/2557b6bc-3ed3-4726-9518-8acae926a4ea)
> ![image](https://github.com/Rectify11/Installer/assets/49023948/5bcd86fc-c4e4-4094-b7d0-820851c8241b)
> 

You can just uses normal Dark mode without Mica

**Comment by Thisisauser6443** [comment]
Could be something to do with a missing configuration file for MFE. About a week ago, I got a warning message saying that the `TAero.conf` file was missing, causing ExplorerFrame to be activated, when it clearly shouldn't be:

![image](https://github.com/Rectify11/Installer/assets/75092921/93d2bc48-1e58-4e01-8a92-a00cac4fa416)


You can just right-click, hit `Exit` and refocus on Explorer to fix that effect
