### ISSUE TITLE
MySQL WorkBench Issue

### ISSUE THREAD

**Issue by RaisTheCoder** [Rectify11/Installer#340]
### Description

MySQL WorkBench 8 looks weird with Rectify11, I can't see some texts, had to use High Contrast to make some of texts visible, but still can't see my query

### Steps To Reproduce

Installed Rectify11
Installed MySQL after a while when I started to take Java Lessons
![image](https://github.com/Rectify11/Installer/assets/69309638/1ec94336-3f1d-4509-b704-3850d42c126a)

### Rectify11 Version

3.0.40.0

### Windows Version

Windows 11 Pro 22H2 22621.2134

### Logs

No logs.. sadly

**Comment by MishaProductions** [comment]
This is an issue with that software. Try using the partial dark theme.
