### ISSUE TITLE
Error opening rectify control panel

### ISSUE THREAD

**Issue by fiendclub** [Rectify11/Installer#347]
### Description

error - Failed to create directUI parser: E_FAIL

### Steps To Reproduce

N/A

### Rectify11 Version

Latest

### Windows Version

Windows 11 10.0.22000 N/A Build 22000

### Logs

---------------------------
CElementProvider::CreateDUI failed
---------------------------
Failed to create DirectUI parser: E_FAIL
---------------------------
OK   
---------------------------

**Comment by MishaProductions** [comment]
Fixed by e48507d719181b6428a45247d935b17711a25081
