### ISSUE TITLE
Word + Dark mode + Rectify11 = this mess of a word.exe:

### ISSUE THREAD

**Issue by CE-Yazeed** [Rectify11/Installer#348]
### Description

Word + Dark mode + Rectify11 = this mess of a word.exe:
![WORD](https://github.com/Rectify11/Installer/assets/95697849/e7167b28-11da-446e-a9c1-276bda7793d6)

Rectify11 breaks Microsoft Word, using "gray mode" on Word makes it less bad, but bad none the less. Please resolve this if possible :c

 
![image](https://github.com/Rectify11/Installer/assets/95697849/8451eb9b-97c2-4807-be47-9d36af2c09ad)

### Rectify11 Version

Rectifyll Version: 3.0.48.0

### Windows Version

OS: Windows NT Build 10.022621

**Comment by EDM115** [comment]
https://github.com/Rectify11/Installer/issues/175#issuecomment-1672758054
