### ISSUE TITLE
R11 Control Panel unable to change the style of context menus

### ISSUE THREAD

**Issue by steveji2021** [Rectify11/Installer#350]
### Description

Choosing styles for context menus from r11 control panel does not work.

### Steps To Reproduce

1. Install Rectify11
2. Go to Rectify11 Control Panel and select a different style
3. See if it works by right clicking anywhere

### Rectify11 Version

3.1.0.0

### Windows Version

Windows 11 23H2 22635.2552

### Logs

No dialog box was shown.

**Comment by steveji2021** [comment]
I have already tried this and it has no use.

**Comment by ewenlau** [comment]
Same issue. Any fix?

**Comment by GentlemanMC** [comment]
same issue here

**Comment by dukelaflame** [comment]
hello, please tell me how to launch the control panel in the latest Rectify11?

**Comment by MishaProductions** [comment]
Install latest actions build
