### ISSUE TITLE
Uninstall button doesnt work

### ISSUE THREAD

**Issue by luisfdcf92** [Rectify11/Installer#351]
### Description

I was trying to uninstall the program since the black and white sections of the MS Office tools got change and made everything to hard to read or highlight, and it would work 

### Steps To Reproduce

Run the installer and try to uninstall

### Rectify11 Version

3.1

### Windows Version

11

### Logs

![image](https://github.com/Rectify11/Installer/assets/129665603/27a7a356-e36a-4f6d-89cc-8885a42f0781)

**Comment by IdkWhatToCallMe123** [comment]
press next?

**Comment by arnavpuranik** [comment]
> press next?

That does absolutely nothing, it's broken.

**Comment by luisfdcf92** [comment]
That does absolutely nothing

**Comment by IdkWhatToCallMe123** [comment]
Do you mean that nothing happens when you press the button?

**Comment by NesChrome** [comment]
yeah nothing happens (i'm having the same issue)

**Comment by NesChrome** [comment]
like you press but nothing updates or changes it doesn't uninstall Rectify11 ..

**Comment by NesChrome** [comment]
like if didn't pressed it but you pressed it sooo you cant uninstall

**Comment by NesChrome** [comment]
okay woaw i just installed the last version and i uninstalled it yay
