### ISSUE TITLE
Can't open control panel 

### ISSUE THREAD

**Issue by Blankially** [Rectify11/Installer#356]
### Description

whenever i open the the control panel i get this error

### Steps To Reproduce

i just installed it but whenever i open the control panel i get this

### Rectify11 Version

v3.1

### Windows Version

22h2 22621.2506

### Logs

![ecEu38ELYV](https://github.com/Rectify11/Installer/assets/149958111/775707ed-3e3a-45b7-947e-0c9f7fdf60f9)

**Comment by MishaProductions** [comment]
you need to install at least 1 icon
