### ISSUE TITLE
Please add an option to use the light theme for specific applications. 

### ISSUE THREAD

**Issue by sudo-000** [Rectify11/Installer#357]
Some applications that set the text color to black without changing the background, and some others set the background to white without changing the color of the text may result in making the text impossible to read. 
It would be very helpful if you can implement a function to apply the light theme specifically to these apps only while keeping dark theme on all others.

**Comment by sudo-000** [comment]
This is not a bug of rectify 11's theme, it's those stupid software developers who don't support it.

**Comment by MishaProductions** [comment]
This is very complicated due to how uxtheme and the window manager is structured
