### ISSUE TITLE
OneNote For Windows 10 - dark more causes white forecolor on white background when trying to export to pdf

### ISSUE THREAD

**Issue by RaZ9Z** [Rectify11/Installer#358]
### Description

when trying to use OneNote with dark mode it exports the pdf white white on white colors.
when i used onenote without rectify11 it worked so i know it has to do something with the rectify11 colors

### Steps To Reproduce

1. Set dark mode on 
![image](https://github.com/Rectify11/Installer/assets/105592934/f50bb894-c4d2-40f8-8a6d-d2c359173455)
2.use a white pen 
![image](https://github.com/Rectify11/Installer/assets/105592934/a760f214-056a-463d-8f1e-165441fde13a)
3.Export to pdf
![image](https://github.com/Rectify11/Installer/assets/105592934/d444da9f-a7c1-4ba8-ae1a-a7dcb5868635)

### Rectify11 Version

3.1.0.0

### Windows Version

22H2 22621.2506

### Logs

![image](https://github.com/Rectify11/Installer/assets/105592934/f50bb894-c4d2-40f8-8a6d-d2c359173455)
![image](https://github.com/Rectify11/Installer/assets/105592934/d444da9f-a7c1-4ba8-ae1a-a7dcb5868635)

**Comment by MishaProductions** [comment]
try using the partial dark theme
