### ISSUE TITLE
Can't change the context menu

### ISSUE THREAD

**Issue by Shy1nx** [Rectify11/Installer#361]
### Description

With the new version, control panel based settings panel isn't working. I was able change context menu in the older version.

### Steps To Reproduce

I'm changing the context menu settings, no changes appearing, not even from a restart.

### Rectify11 Version

3.1

### Windows Version

22H2

### Logs

![image](https://github.com/Rectify11/Installer/assets/67850212/1a81db84-2827-4094-9371-21bc89d2434d)

**Comment by blackwind** [comment]
Yep, same thing here.

**Comment by ewenlau** [comment]
No fix?

**Comment by Excremation** [comment]
Also getting this. No matter what I choose, after closing the Rectify11 Settings windows it just reverts back to what it was, and I also have to re-enable "Change settings that are unavailable".

**Comment by MishaProductions** [comment]
install latest actions build

**Comment by Excremation** [comment]
> install latest actions build

How do I do that? Sorry I'm a GitHub noob!

**Comment by Entropy159** [comment]
I'm having this same issue on Rectify11 3.2, windows 24H2
