### ISSUE TITLE
Certain HTML elements seem to be broken.

### ISSUE THREAD

**Issue by gaster2411** [Rectify11/Installer#368]
### Description

Some HTML elements(or is it JS? I don't know much programming)seem to be broken, as seen in a recording of this website:
black bullets should be shot out of the red and black triangles, but they cannot be seen. Also, the buttons on the right have the incorrect colors. This is on dark theme(No mica)
[capture.webm](https://github.com/Rectify11/Installer/assets/121835599/64d31374-0384-410e-a76d-10d386d99bcf)

### Steps To Reproduce

1. Go on https://iblobtouch.github.io/IdleBulletGame/
2. Start game
3. Shoot by pressing e or left click
4. See issue

### Rectify11 Version

Version 3.1

### Windows Version

Windows 11 Version 23H2 (OS Build 22631.2429)

### Logs

[capture.webm](https://github.com/Rectify11/Installer/assets/121835599/eba3d861-d2b2-45bd-865e-78899d81e27b)

**Comment by MishaProductions** [comment]
See section 6c in the faq.
