### ISSUE TITLE
POSTAL 2 takes Mica style, becoming blue.

### ISSUE THREAD

**Issue by aag8a** [Rectify11/Installer#375]
### Description

For some reason, Postal 2 with "Rectify 11 Dark theme with Mica" theme becomes blue, like other apps would do.

### Steps To Reproduce

1. Install Rectify11 with choosing Dark theme with Mica.
2. Install Postal 2
3. Boot it up.

### Rectify11 Version

v. 3.1

### Windows Version

Windows 11 23H2 Build 22631

### Logs

![image](https://github.com/Rectify11/Installer/assets/72987745/c0d33b1c-75ee-453c-8834-d4d8ef06df2b)
![image](https://github.com/Rectify11/Installer/assets/72987745/ace6f7f9-c796-4ef8-b7fe-5f16b60d4453)

**Comment by Antonomasia3** [comment]
Open "Mica For Everyone" on your system tray icon, add "Postal2" as the Process Rule, leave everything as default
![image](https://github.com/Rectify11/Installer/assets/89201774/1d3618c0-df50-4127-9615-90722a942220)

Tutorial Video:
![](https://github.com/Rectify11/Installer/assets/89201774/48045ff9-1ace-4b36-9c2f-43820d74e284)

**Comment by aag8a** [comment]
Strange, lowercase doesn't work, but capital one does. Thanks!
