### ISSUE TITLE
Mica theme not applying to explorer correctly

### ISSUE THREAD

**Issue by CobaltBar** [Rectify11/Installer#376]
### Description

Most of Windows Explorer doesn't have Mica, despite me applying the theme and using ExplorerFrame and ExplorerBlurMica

### Steps To Reproduce

Open Explorer after installing Rectify11

### Rectify11 Version

[Latest Github Actions Build](https://github.com/Rectify11/Installer/actions/runs/6808194855)

### Windows Version

Windows 11 23H2

### Logs

![image](https://github.com/Rectify11/Installer/assets/79053181/1bb102e3-a068-490b-8fb2-4394e9672a7e)

**Comment by SmirbYrneh420** [comment]
This new home page in explorer seems to be hardcoded, basically impossible to fix without Micro$haft getting after us
