### ISSUE TITLE
Application Setup Text is Not Visible

### ISSUE THREAD

**Issue by kavinthangavel** [Rectify11/Installer#382]
### Description

I was about to install an application and i found this issue that the text are present in the installation setup are not readable because of this theme 

### Steps To Reproduce

try to install any software setup but here i used mkvtoolnix 

### Rectify11 Version

Version 3.1

### Windows Version

Win 11 23H2 22631.2715

### Logs

![image](https://github.com/Rectify11/Installer/assets/91929982/bffffab9-8045-4002-8ea9-d22d2aefa273)

**Comment by ItzELECTR0** [comment]
Not only the installer. I managed to install it with the text all invisible and all Windows UI changed by Rectify11 has it's text not visible, and the parts that are visible are extremely hard to read with a weird small font. I uninstalled the Rectify 11 theme and kept everything else. The rest works perfectly fine.

Rectify Version:
3.1

Windows Build:
23H2 25997.1010 (Canary Channel)

**Comment by ooTruffle** [comment]
This is due to hardcoded colours
partal dark is the only "solution" to this as not as much gets changed

**Comment by jerfer1111** [comment]
This is just Rectify 11 Dark Mode. I think this is because the installer isn't linked with Rectify 11 in any way unlike 7-Zip etc.

**Comment by ooTruffle** [comment]
> This is just Rectify 11 Dark Mode. I think this is because the installer isn't linked with Rectify 11 in any way unlike 7-Zip etc.

Its hardcoded colours in the installer
