### ISSUE TITLE
Mica For Everyone is not installed

### ISSUE THREAD

**Issue by ShahranPlayz** [Rectify11/Installer#389]
### Description

When I installed Rectify 11 I Selected Mica for everyone it did not install, but I cant Figure it out.

### Steps To Reproduce

There is no way to reproduce the same behavior

### Rectify11 Version

Version:3.0

### Windows Version

Windows 11 22h2

### Logs

There are no logs

**Comment by MishaProductions** [comment]
It works fine for me, try the latest actions build
