### ISSUE TITLE
Control Panel and Control Center stopped Working

### ISSUE THREAD

**Issue by NDNIAD** [Rectify11/Installer#390]
### Description

Control Panel and Control Center stopped Working. The Control Panel isn't Opening and Control Rectify Center freezes and crashes

### Steps To Reproduce

Control Panel and Control Center stopped Working. The Control Panel isn't Opening and Control Rectify Center freezes and crashes. Fix it

### Rectify11 Version

version 3.1

### Windows Version

Windows 11 23H2

### Logs

Control Panel and Control Center stopped Working. The Control Panel isn't Opening and Control Rectify Center freezes and crashe

**Comment by super-coder01** [comment]
Facing same issue.

**Comment by MGIsHeree** [comment]
Same issue, whenever I open the Rectify11 Control Center, Control Panel stops working and won’t launch until I restart.

**Comment by Donniem70** [comment]
Same issue for me also. Open the Rectify11 Setting, click on Control Panel Home, and the wheel just starts spinning and never stops. It is not responding, Have to force close. 
Windows 11 22H2

**Comment by MishaProductions** [comment]
Fixed in latest commit
