### ISSUE TITLE
AV not working

### ISSUE THREAD

**Issue by Ross2750** [Rectify11/Installer#396]
### Description

I installed rectify11 and my antivirus Avast stops working
I tried it on both windows 10 and 11 but still no luck so I think that was a bug

### Steps To Reproduce

1. Install Rectify11
2. Open Avast
3. Avast crashes

### Rectify11 Version

Rectify11 v3.1

### Windows Version

Windows 10/11 22H2

### Logs

![image](https://github.com/Rectify11/Installer/assets/122451270/eccc206b-12ce-436a-83fc-5feba4991f18)

**Comment by ooTruffle** [comment]
Anti virsus should not break on modded files

Use a diffrent av

**Comment by KMTSTUDIO** [comment]
I've experienced the same thing with Avast crashing after a reboot of my system once Reftify has been installed.
Defender is disabled. I'm running the latest version of Rectify 11 and Windows 11 23H2?

**Comment by ooTruffle** [comment]
> Anti virsus should not break on modded files
> 
> Use a diffrent av

@KMTSTUDIO this still applies

Avast is also a shitty av

**Comment by Ross2750** [comment]
> I've experienced the same thing with Avast crashing after a reboot of my system once rectify11 has been installed. Defender is disabled. I'm running the latest version of rectify11 and Windows 11 23H2?

That happens because r11 modifies files on the system that breaks antiviruses

**Comment by ooTruffle** [comment]
> > I've experienced the same thing with Avast crashing after a reboot of my system once rectify11 has been installed. Defender is disabled. I'm running the latest version of rectify11 and Windows 11 23H2?
> 
> That happens because r11 modifies files on the system that breaks antiviruses

More so that advast sucks and complains at the littlest thing

**Comment by KMTSTUDIO** [comment]
> > > I've experienced the same thing with Avast crashing after a reboot of my system once rectify11 has been installed. Defender is disabled. I'm running the latest version of rectify11 and Windows 11 23H2?
> > 
> > 
> > That happens because r11 modifies files on the system that breaks antiviruses
> 
> More so that advast sucks and complains at the littlest thing

The need to rectify that.
