### ISSUE TITLE
Ruined MS Office - Blacked excell cells and powerpoint white (and off-white) elements

### ISSUE THREAD

**Issue by lerianux** [Rectify11/Installer#397]
### Description

Since I installed this, I cannot have any white backgrounds in Excel and PowePoint, because this extension is overlaying them automatically to black. 

### Steps To Reproduce

Install MS Office 365, Open any document that you know from previous installs, in Excel or powerpoint. Or, try to draw a white square in powerpoint - it will automatically get black.

### Rectify11 Version

3.1

### Windows Version

Windows 11 23h2 

### Logs

No log, see attached image
![rectify11-bug](https://github.com/Rectify11/Installer/assets/65623982/b4abcce9-9d61-4a7f-8be6-e37c2180655a)

**Comment by Thisisauser6443** [comment]
https://github.com/Rectify11/Installer/issues/175#issuecomment-1672758054

**Comment by ANDREW007CZ** [comment]
This issue extends to other Office programs as well. Try Outlook or OneNote.
This is probably problem with setting "WindowFrame" option to darker tones in themes and there might be no workaround... idk

**Comment by lerianux** [comment]
> there might be no workaround... idk

There is one, but its not working as intended - switch to a white theme while working in office. I did that to work on some office documents, and then when I switched back, the dark effect on the white areas didn't applied. Restarted the computer while the Rectify11 dark was active, also no effect. Had to uninstall and reinstall Rectify11 to apply it back. Will write a but tomorrow, didn't checked if anyone already did it yet.

**Comment by ANDREW007CZ** [comment]
To reapply Rectify11 theme again, for me it worked using this https://github.com/namazso/SecureUxTheme

**Comment by ANDREW007CZ** [comment]
Also wanted to mention that using Rectify dark theme in Excel - so you have dark cells bakcground later somehow wierdly translates to PDF export as well. For example text is light (almost white) but background becames white. So even if you would like to use dark-themed excel, export result in not good.
