### ISSUE TITLE
Some Windows programs started to require UAC after installing Rectify11

### ISSUE THREAD

**Issue by rottakore** [Rectify11/Installer#399]
### Description

After installing Rectify11, some classic Windows programs now require UAC

### Steps To Reproduce

Install Rectify11, open some classic Windows program.

### Rectify11 Version

v3.1

### Windows Version

Windows 11 23H2 22631.2792

### Logs

Nothing.

**Comment by MishaProductions** [comment]
Normal, this can't be fixed
