### ISSUE TITLE
Enabling HDR makes installer unusable ( on Dark Theme only )

### ISSUE THREAD

**Issue by mignat** [Rectify11/Installer#400]
### Description

Hi,

The installer has dark text on default win 11 dark theme if HDR is turned ON 

NOTE: Had to take photo of the screen as snipping tool was seeing the text normally with HDR on !

![IMG_0861](https://github.com/Rectify11/Installer/assets/30924447/73cc011b-a0f3-48a2-bf95-67991d868c89)

![IMG_0860](https://github.com/Rectify11/Installer/assets/30924447/7ca320ba-3523-4f34-b12d-75bb8f6b3d28)

### Steps To Reproduce

1. Download latest installer from releases
2. Open installer
3. Profit

### Rectify11 Version

3.1.0.0

### Windows Version

Windows 11 Pro Version	23H2 22631.2715

### Logs

N/A

**Comment by rafachavantes** [comment]
I have the same problem but my display does not support HDR. 
It is running Dark Theme, if i switch to light theme It display normally.

**Comment by Tellinq** [comment]
I'm also affected by this, but not limited by the installer itself.

Once I apply one of the Rectify11 dark themes, I reproduce this.

**Comment by OldGamerDarthyOfficial** [comment]
Hi, on my monitor after hdr enabled the dark mode make ureadable both, dark color to dark texts, but i think if is disponible a text color changer or a fix ?

**Comment by MishaProductions** [comment]
This can't really be fixed as winforms/GDI+ doesn't support HDR
