### ISSUE TITLE
Disables ESET Antivirus and Create Permanent Issue

### ISSUE THREAD

**Issue by NDNIAD** [Rectify11/Installer#404]
### Description

After Installing Rectify11, My ESET Antivirus Program Does not open and Bugs out the Antivirus Service off the Application

### Steps To Reproduce

Fix it and don't take away ESET Antivirus

### Rectify11 Version

version 3.1, 3.0

### Windows Version

Windows 11 23H2

### Logs

After Installing Rectify11, My ESET Antivirus Program Does not open and Bugs out the Antivirus Service off the Application. Fix it and don't take away ESET Antivirus

**Comment by MarekSurek** [comment]
I have same issue 😭

**Comment by REALMWTH** [comment]
Uncheck `msi.dll` from Advanced, this is the only library that prevents ESET from being loaded correctly.
