### ISSUE TITLE
Control Center not working

### ISSUE THREAD

**Issue by jayden1090** [Rectify11/Installer#405]
### Description

It says a error message

### Steps To Reproduce

I open it and then it pops up an error

### Rectify11 Version

v3.1

### Windows Version

Windows 10 22H2 19045.3803

### Logs

CElementProvider::CreateDUI failed

Failed to create DirectUI parser: E_FAIL

**Comment by MishaProductions** [comment]
install at least 1 icon in rectify11 installer
