### ISSUE TITLE
Cant Install Recify11

### ISSUE THREAD

**Issue by Speedchiller** [Rectify11/Installer#406]
### Description

Cant install Recify11 im not sure where the problem is

### Steps To Reproduce

Just install the program

### Rectify11 Version

3.1.0.0

### Windows Version

Windows 11 23H2 22631.2861

### Logs

═════════════════════════════
START: 19.12.2023 12:18:15
Rectify11 Version: 3.1.0.0
═════════════════════════════
Preparing Installation
──────────────────────
Wrote 7za.exe
Wrote files.7z
Wrote extras.7z
Wrote ResourceHacker.exe
WriteFiles() succeeded.
C:\Windows\Rectify11\Backup already exists.
Extracting vcredist.exe from extras.7z
Extracting core31.exe from extras.7z
Executing vcredist.exe with arguments /install /quiet /norestart
vcredist.exe exited with error code 1638
Executing core31.exe with arguments /install /quiet /norestart
core31.exe exited with error code 0
InstallRuntimes() succeeded.
══════════════════════════════════════════════
Installing Themes
─────────────────
Wrote themes.7z
Wrote SecureUXHelper.exe
Wrote ThemeDll.dll
WriteFiles() succeeded.
Extracted files.7z
Deleted old wallpapers.
Copied wallpapers to C:\Windows\web\wallpaper\Rectified
Copied Themetool.
InstallThemes() failed. Die Datei wurde nicht gefunden.
   bei Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   bei Rectify11Installer.Core.Themes.InstallThemes()

Deleted old wallpapers.
Deleted themes.
Themes.Install() failed. Die Datei wurde nicht gefunden.
   bei Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   bei Rectify11Installer.Core.Themes.InstallThemes()
   bei Rectify11Installer.Core.Themes.Install()

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

**Comment by sutnax** [comment]
same issue here

**Comment by sutnax** [comment]
> same issue here

fixed it, just exclude the folder Rectify11 in C:\Windows11 in your antivirus

**Comment by sutnax** [comment]
> same issue here

fixed it, just exclude the folder Rectify11 in C:\Windows\Rectify11 in your antivirus
