### ISSUE TITLE
Rectify11 dark mode applies to other applications and websites

### ISSUE THREAD

**Issue by randomguy-2650** [Rectify11/Installer#409]
### Description

I installed the Rectify11 dark mode theme with Mica, and started coding, but after a while, I go to websites like boxicons.com, and text suddently starts to be hard to read. And it's also in dark mode. But boxicons.com has its own dark mode, and the Rectify11 dark theme overrides that, so it does not match. It also applies to applications like Notepad++. If you find any insights or solutions, comment it in this bug report.

### Steps To Reproduce

1. I turn on my computer
2. Sometimes, I code, and open boxicons.com to use their icons
3. Suddently the dark theme does not match, and text became hard to read
4. I take notes in Notepad++, and suddently text is also hard to read

### Rectify11 Version

Version: 3.0.48.0

### Windows Version

Windows 11 23H2 22631.2861

### Logs

No specific error messages were observed.

**Comment by SmoGroove** [comment]
Same here!
For example on aliexpress
![image](https://github.com/Rectify11/Installer/assets/75605318/a8b74684-4dd5-44d9-b61f-c1d148799b8e)
![image](https://github.com/Rectify11/Installer/assets/75605318/b7af4a93-0966-45de-901e-4701dcdaf903)

**Comment by randomguy-2650** [comment]
## Note

I don't really know what version I'm on, in `Rectify11 Settings` in the Control Panel, it says `Version 3.0.48.0`, but in the installer, it says `Version 3.1` so I don't really know.

###### I submitted this issue by the way

**Comment by randomguy-2650** [comment]
<style>
    @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap");

    * {
        font-family: "Poppins", sans-serif;
    }
</style>



I updated it to Rectify11 Version 3.1.0.0 but it still doesn't fix it.

###### I submitted this issue by the way

**Comment by MishaProductions** [comment]
Use partial dark theme
