### ISSUE TITLE
When Rectify Control Center is opened by the item on the desktop, then clicking on Control Panel tab to bring back to the main Control Panel menu, it just crashes

### ISSUE THREAD

**Issue by CorruptedChunks** [Rectify11/Installer#415]
### Description

When Rectify Control Center is opened by the item on the desktop, then clicking on Control Panel tab to bring back to the main Control Panel menu, it just crashes

### Steps To Reproduce

Open Rectify Control Center using the desktop icon, then at the Adress bar, choose Control Panel
![image](https://github.com/Rectify11/Installer/assets/144022656/8b86cbba-762e-47e8-9332-c1a2538bbf69)

### Rectify11 Version

Version : 3.1

### Windows Version

Windows 11 23H2 22631.2861

### Logs

![image](https://github.com/Rectify11/Installer/assets/144022656/1d04c4ae-7e99-43c1-8426-6b8b8eff75d2)

**Comment by MishaProductions** [comment]
This is a known issue
