### ISSUE TITLE
Virus detected in windows defender scan

### ISSUE THREAD

**Issue by Justavinash09** [Rectify11/Installer#418]
### Description

HackTool:Win32/Patcher detected in windows  defender scan ,  link of virustotal report - https://www.virustotal.com/gui/file/1057e5499e57f88c345f3b28c6473fc2fe889a33abcb75df6f02226a022ce3d4/detection
![image](https://github.com/Rectify11/Installer/assets/112340801/2e01e43d-9e73-44ae-afd3-b2c62668d4d4)

### Steps To Reproduce

scan the c drive using windows defender 

### Rectify11 Version

Rectify11 v3.1

### Windows Version

Windows 11  23H2

### Logs

![image](https://github.com/Rectify11/Installer/assets/112340801/4a10de45-588e-4368-ad1a-034fd271d107)

**Comment by Justavinash09** [comment]
![image](https://github.com/Rectify11/Installer/assets/112340801/930174a0-5f93-4241-becd-a9a708487a9f)
this thing occur in detection

**Comment by doEggi** [comment]
Thats because you have to whitelist the directory C:/Windows/Rectify11/ from your Anti Virus...
This has been told, but i don't know where atm

**Comment by Justavinash09** [comment]
I haven't Whitelisted the directory..

**Comment by MishaProductions** [comment]
known issue, allow c:\windows\rectify11 in your antivirus

**Comment by doEggi** [comment]
There is some way to whitelist directorys per code (IntelliJ uses this feature to increase compile performance)
Maybe some of you could research / implement it to do so on install?
