### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by reality8080** [Rectify11/Installer#420]
### Description

This is my problem 
![screenshot_1704470983](https://github.com/Rectify11/Installer/assets/155755865/aa265e86-8b31-4507-a84e-ea20c4c5ef12)
![screenshot_1704470889](https://github.com/Rectify11/Installer/assets/155755865/b6c38c11-09ee-46bc-b38b-0baa694c29ce)

### Steps To Reproduce

install on win 11, it doesn't show the selections related to win11 or 10.

### Rectify11 Version

Version: 3.1.0.0

### Windows Version

Windows 11, version 23H2

### Logs

![screenshot_1704470889](https://github.com/Rectify11/Installer/assets/155755865/ceee09af-66d1-4d02-938b-4156a2a94882)

**Comment by error404ts** [comment]
I'm also getting this error. Windows Defender is preventing suspicious behavior. The installation has worked before, so I'm not sure what's happening.
![Screenshot 2024-01-13 154216](https://github.com/Rectify11/Installer/assets/49771469/86a520e7-313d-4ec7-9290-6ce5f9749f74)

**Comment by jerfer1111** [comment]
That is the exact message I'm getting, but I noticed it was only for Rectify Version 3.1 for some reason¿¿

**Comment by MishaProductions** [comment]
cannot reproduce
