### ISSUE TITLE
Update ThemeTool to latest version

### ISSUE THREAD

**Issue by rodolfol95** [Rectify11/Installer#421]
### Description

I think the ThemeTool it's really outdated and causes issues sometimes please update it to latest version

https://github.com/namazso/SecureUxTheme/releases

Thanks :)

### Steps To Reproduce

ThemeTool Utility version issue

### Rectify11 Version

3.0

### Windows Version

Windows 11 

### Logs

No Logs

**Comment by MishaProductions** [comment]
I updated themetool, however ThemeDll needs to be updated.
