### ISSUE TITLE
Bug on fresh install

### ISSUE THREAD

**Issue by RandomUser35** [Rectify11/Installer#423]
### Description

While installing, I see this error shown in the screenshot, how to fix this?

### Steps To Reproduce

There is a screenshot below to explain my problem.

### Rectify11 Version

Version 3.1

### Windows Version

Windows 11 23H2 Build 25967.1000

### Logs

![Screenshot 2024-01-05 183247](https://github.com/Rectify11/Installer/assets/155769238/dc11c3ed-0c44-4996-8f64-930fd1aeec50)

**Comment by MishaProductions** [comment]
Can you please send the log file?

**Comment by RandomUser35** [comment]
how though?

**Comment by RandomUser35** [comment]
oh there we go here it is, can you describe my problem now?:
═════════════════════════════
START: 05/01/2024 18:31:06
Rectify11 Version: 3.1.0.0
═════════════════════════════
Preparing Installation
──────────────────────
Wrote 7za.exe
Wrote files.7z
Wrote extras.7z
Wrote ResourceHacker.exe
WriteFiles() succeeded.
C:\WINDOWS\Rectify11\Backup already exists.
Extracting vcredist.exe from extras.7z
Extracting core31.exe from extras.7z
Executing vcredist.exe with arguments /install /quiet /norestart
vcredist.exe exited with error code 1638
Executing core31.exe with arguments /install /quiet /norestart
core31.exe exited with error code 0
InstallRuntimes() succeeded.
══════════════════════════════════════════════
Installing Themes
─────────────────
Wrote themes.7z
Wrote SecureUXHelper.exe
Wrote ThemeDll.dll
WriteFiles() succeeded.
Extracted files.7z
Deleted old wallpapers.
Copied wallpapers to C:\WINDOWS\web\wallpaper\Rectified
Copied Themetool.
InstallThemes() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()

Deleted old wallpapers.
Deleted themes.
Themes.Install() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()
   at Rectify11Installer.Core.Themes.Install()

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

**Comment by RandomUser35** [comment]
It doesn't matter now I fixed it, I just turned off Windows Firewall and Security, I'm enjoying the new look of Windows 11 after installation, all the Windows 7-themed icons are now fluent just like Windows 11!
![Screenshot 2024-01-06 170851](https://github.com/Rectify11/Installer/assets/155769238/f0da01ae-0038-4803-b61b-c18d047bc498)

**Comment by shambhav15** [comment]
> oh there we go here it is, can you describe my problem now?: ═════════════════════════════ START: 05/01/2024 18:31:06 Rectify11 Version: 3.1.0.0 ═════════════════════════════ Preparing Installation ────────────────────── Wrote 7za.exe Wrote files.7z Wrote extras.7z Wrote ResourceHacker.exe WriteFiles() succeeded. C:\WINDOWS\Rectify11\Backup already exists. Extracting vcredist.exe from extras.7z Extracting core31.exe from extras.7z Executing vcredist.exe with arguments /install /quiet /norestart vcredist.exe exited with error code 1638 Executing core31.exe with arguments /install /quiet /norestart core31.exe exited with error code 0 InstallRuntimes() succeeded. ══════════════════════════════════════════════ Installing Themes ───────────────── Wrote themes.7z Wrote SecureUXHelper.exe Wrote ThemeDll.dll WriteFiles() succeeded. Extracted files.7z Deleted old wallpapers. Copied wallpapers to C:\WINDOWS\web\wallpaper\Rectified Copied Themetool. InstallThemes() failed. File not found. at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout) at Rectify11Installer.Core.Themes.InstallThemes()
> 
> Deleted old wallpapers. Deleted themes. Themes.Install() failed. File not found. at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout) at Rectify11Installer.Core.Themes.InstallThemes() at Rectify11Installer.Core.Themes.Install()
> 
> Cleaning up ─────────── Cleanup() succeeded. ══════════════════════════════════════════════

Can you say how did you installed it because i am getting the same error

**Comment by MishaProductions** [comment]
You need to exclude c:\windows\rectify11 in your antivirus
