### ISSUE TITLE
Right Button Click Issue

### ISSUE THREAD

**Issue by SeniorMatth3w** [Rectify11/Installer#424]
### Description

When u fast click right button on desktop, then right click to the taskbar there may appear old context menu
![image](https://github.com/Rectify11/Installer/assets/130131083/184e1d0d-40db-4672-9b1f-7b1893a8bda7)
![image](https://github.com/Rectify11/Installer/assets/130131083/f0fbc880-ce0a-4006-a0c5-09fb38b4f98b)

### Steps To Reproduce

Fast right click on desktop, then on taskbar

### Rectify11 Version

Last Version

### Windows Version

Last Update

### Logs

None

**Comment by MishaProductions** [comment]
issue with nilesoft shell
