### ISSUE TITLE
Cant install Rectify11 on my PC

### ISSUE THREAD

**Issue by SYCOINFOERNO** [Rectify11/Installer#425]
### Description

When I ran the exe file the installation started and then it show cant open cmd.exe(0xc0000142 error) and then the same thing with something called 7az.exe(or something)(0xc0000142 error) and said it was patching some file after completing them, I said failed to install.

### Steps To Reproduce

1) Install Rectify11
2) Run the .exe file
3) the error popped up 

### Rectify11 Version

Rectify11 v3.1

### Windows Version

Version 22H2 (OS Build 22621.2861)

### Logs

[installer.log](https://github.com/Rectify11/Installer/files/13853686/installer.log)
![image](https://github.com/Rectify11/Installer/assets/100705590/bc847ce7-5cd6-4386-8754-3f619628be13)

**Comment by McKpol** [comment]
Same

═════════════════════════════
START: 07.01.2024 19:05:10
Rectify11 Version: 3.1.0.0
═════════════════════════════
Preparing Installation
──────────────────────
Wrote 7za.exe
Wrote files.7z
Wrote extras.7z
Wrote ResourceHacker.exe
WriteFiles() succeeded.
Extracting vcredist.exe from extras.7z
Extracting core31.exe from extras.7z
Executing vcredist.exe with arguments /install /quiet /norestart
vcredist.exe exited with error code 1638
Executing core31.exe with arguments /install /quiet /norestart
core31.exe exited with error code 0
InstallRuntimes() succeeded.
══════════════════════════════════════════════
Installing Themes
─────────────────
Wrote themes.7z
Wrote SecureUXHelper.exe
Wrote ThemeDll.dll
WriteFiles() succeeded.
Extracted files.7z
Deleted old wallpapers.
Copied wallpapers to C:\Windows\web\wallpaper\Rectified
Copied Themetool.
InstallThemes() failed. Nie odnaleziono pliku.
   w Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   w Rectify11Installer.Core.Themes.InstallThemes()

Deleted old wallpapers.
Deleted themes.
Themes.Install() failed. Nie odnaleziono pliku.
   w Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   w Rectify11Installer.Core.Themes.InstallThemes()
   w Rectify11Installer.Core.Themes.Install()

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

**Comment by McKpol** [comment]
You can use older versions, it probably will work

**Comment by SYCOINFOERNO** [comment]
Ok will try

**Comment by bbmaster123** [comment]
Not a dev, but according to your log, vcredist didn't install correctly. Try extracting it from extras.7z and see if you can install manually. If it installs fine, try installing rectify again, and if not, try uninstalling vcredist, reboot, reinstall vcredist

**Comment by SYCOINFOERNO** [comment]
Hmm well I am resetting my computer anyway, so will try after that I guess

**Comment by MishaProductions** [comment]
something is really wrong with your windows install if reg.exe doesn't work. Try reinstalling windows

**Comment by YourFavoriteScripter** [comment]
did u install a virus or smth? reg.exe is a system file - **reinstall windows.**
