### ISSUE TITLE
theme preferences should be respected upon update/re-install

### ISSUE THREAD

**Issue by ninbura** [Rectify11/Installer#430]
I have my theme preferences configured in Rectify11's settings within Control Panel as follows:
![image](https://github.com/Rectify11/Installer/assets/58058942/c83d2770-29e3-4087-9d71-0973e29ad7a1)

These theme preferences are respected when changing theme's via the switcher in Recitfy11's settings. However, they are *not respected* when updating Rectify11. Updating Rectify11 is frequently required as Windows Updates often break theming.

I have Rectify11 installed on 4 PCs connected to a total of 12 displays. On each display I have a specific background set. I also disable many system sounds within windows, and set a specific accent color per PC. Re-configuring all of this, per pc, after every Rectify11 update/re-install, is extremely tedious.

Theme preferences should always be respected once Rectify11 is installed. They must be accessible during update, as they are maintained after updating.

**Comment by MishaProductions** [comment]
should be fixed in latest commit, can please test again?
