### ISSUE TITLE
Broken theme?

### ISSUE THREAD

**Issue by kameno22** [Rectify11/Installer#434]
### Description

![IMG20240114165622](https://github.com/Rectify11/Installer/assets/98833613/a3c773bd-e3de-4684-bb8e-706a48dec740)

https://github.com/Rectify11/Installer/assets/98833613/913881f1-df36-46d8-b1f3-35cb1618f7ab

Snipping tool and screenshot shows the text 

### Steps To Reproduce

it is weird it should do that 

### Rectify11 Version

3.0

### Windows Version

windows 11 23h2

### Logs

no logs

**Comment by NanKillBro** [comment]
Try turning off HDR, it works for me

**Comment by kameno22** [comment]
> Try turning off HDR, it works for me

![image](https://github.com/Rectify11/Installer/assets/98833613/d35df3ba-3126-4af9-af07-0cc9a2d7770c)
this option you talking abt right, just turned it off but same results

**Comment by NanKillBro** [comment]
![image](https://github.com/Rectify11/Installer/assets/72297072/428506c6-5d02-4cef-8f9c-8bb002ed39e4)
It on the Advanced Display

**Comment by kameno22** [comment]
> ![image](https://private-user-images.githubusercontent.com/72297072/296656306-428506c6-5d02-4cef-8f9c-8bb002ed39e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDAxNTgsIm5iZiI6MTcwNTI5OTg1OCwicGF0aCI6Ii83MjI5NzA3Mi8yOTY2NTYzMDYtNDI4NTA2YzYtNWQwMi00Y2VmLThmOWMtOGJiMDAyZWQzOWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA2MjQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjY2ZiNWY3MDIwNzUzOWZmYjllYzVlMTIzMDAxYTc5OTUwOTEzNzExOWQ1ZDI2ZWVjM2FiMDE1MTM0NTQxNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KNdea-HJzO16o7WV6-VCZKYddylJWycVUrU577GaVls) It on the Advanced Display

oooo yes it workss thank youu, hope this issue will be fixed in future with that option being turned on :D
