### ISSUE TITLE
Rectify 11 Bootlooping Explorer

### ISSUE THREAD

**Issue by gsggsg815** [Rectify11/Installer#436]
### Description

After switching to Rectify11 Theme in settings PowerToys gives an error. I try installing 3.1 but InstallThemes failed. I uninstalled Rectify11 i rebooted then Explorer Bootloops i try ending explorer and launching it again. Didnt work, still loops. I also switched to normal Windows 11 dark theme no powertoys error only when i select Rectify11 Theme.

### Steps To Reproduce

To do reproduce. Install version 3.0 , Then try uninstalling Rectify11, Reboot then Explorer bootloops. 

### Rectify11 Version

Rectify 11 3.0

### Windows Version

Windows 11 23H2 22631.2861

### Logs

[installer.log](https://github.com/Rectify11/Installer/files/13936057/installer.log)

**Comment by jerfer1111** [comment]
I have the same issue with "Install Themes" Failed. That might be just Windows Defender. Maybe try disabling Windows Defender and then install 3.1.

**Comment by MishaProductions** [comment]
should be fixed
