### ISSUE TITLE
HDR trouble 

### ISSUE THREAD

**Issue by Redkr0me** [Rectify11/Installer#440]
### Description

I have a problem when I activate HDR on Windows... 
I can no longer read the text.
Any idea where this might be coming from? 

Thanks in advance

Without HDR :
![image](https://github.com/Rectify11/Installer/assets/64694459/f1d7ed63-4204-465c-b1ad-cabf0ed172ca)

With HDR : (Windows screenshot)
![image](https://github.com/Rectify11/Installer/assets/64694459/b9738849-6a89-4481-ba48-60b1b9c86cba)

With HDR : (My view)
![IMG_0252](https://github.com/Rectify11/Installer/assets/64694459/cfee6209-23a6-4f39-a0f4-ffad9284565b)

### Steps To Reproduce

Activate HDR

### Rectify11 Version

Rectify11 v3.1

### Windows Version

Windows 11 Professionnel / 23H2 / 22631.3007

### Logs

No log

**Comment by danturism0** [comment]
Having the same HDR issue to the point that the installer is even illegible when using the native dark theme in windows

**Comment by Tellinq** [comment]
Apparently this issue won’t be fixed due to https://github.com/Rectify11/Installer/issues/400#issuecomment-1873558561
