### ISSUE TITLE
NVCleanstall text can't be read + Feature suggestion

### ISSUE THREAD

**Issue by CarlMichaelFabe** [Rectify11/Installer#441]
### Description

I'm using Dark Theme with Mica and text in `NVCleanstall` can't be seen.

![image](https://github.com/Rectify11/Installer/assets/116660522/6fdf8073-3e38-48c8-8e91-a66ba4a54b8c)

I understand this bug might be because of how `NVCleanstall` is implemented.

But I wanna ask if its possible to have a menu like `Mica for Everyone` where we can change the theme of apps individually, at least as a workaround for apps that don't work well with `Rectify11` dark theme.

### Steps To Reproduce

1. Use Dark Theme with Mica
2. Open NVCleanstall
3. The image attached is from the downloading screen.

### Rectify11 Version

Version: 3.1.0.0

### Windows Version

Windows 11 23H2 22635.3061

### Logs

N/A

**Comment by Xenonionite** [comment]
Changing the rectify 11 theme to partially dark theme fixed all text issues for me
