### ISSUE TITLE
Installer won't install due to "Pending Updates"

### ISSUE THREAD

**Issue by DanielLMcGuire** [Rectify11/Installer#445]
### Description

My computer has no Windows Updates pending, I have restarted 7 times and it still doesn't work. Upon installing, I get the following error message:
```
You cannot install Rectify11 as Windows Updates are pending. Please reboot your system.
```

### Steps To Reproduce

- Download the Installer.
- Run the Installer.
- Click Install.

### Rectify11 Version

v-3.1-fixed2

### Windows Version

Windows 11 23H2 22631.3007

### Screenshot:

![Screenshot 2024-01-22 073541](https://github.com/Rectify11/Installer/assets/146508360/8e12854f-e886-42c9-83ca-9716ac6e405c)

**Comment by Moherwinseptianto** [comment]
Might help, I tried to update my windows (before, I pause my windows using program the windows update will be stopped) and it will works.

If you using software (let's say No Thanks Windows Update), you should reverse back to normal, restart, then try update 1-2 update, after that try to install rectify again. It works for me xixi

**Comment by jerfer1111** [comment]
Update whatever pending system updates you have, then you can install it

**Comment by DanielLMcGuire** [comment]
### This bug was fixed after reverting the previous Windows Update.
<sup>I meant to close this issue a lot sooner</sup>
