### ISSUE TITLE
Uninstalling rectify11 broke windows 11

### ISSUE THREAD

**Issue by BlueBudgieTech** [Rectify11/Installer#447]
When uninstalling rectify11, not all parts get uninstalled, thus leaving many legacy apps looking completely broken.

For example, this is the control panel apps section:-
![image](https://github.com/Rectify11/Installer/assets/85682026/7da91955-3d77-4d87-9d1c-88ad072348e3)

Run dialog:-
![image](https://github.com/Rectify11/Installer/assets/85682026/6da156cc-4ea5-4548-a309-8b2b55adbb75)

Windows version:-
![image](https://github.com/Rectify11/Installer/assets/85682026/ab7065e9-ee97-4705-a7d0-b15fe3481131)

I'm on Rectify11 v3.1 on Windows 11 23H2 Build 25941.1000.

Does the insider preview have anything to do with this?

**Comment by Ermageeerd** [comment]
likely

**Comment by qb20nh** [comment]
No, my colors are fd up too. doesn't seem to be a easy way to fully revert it to default colors except full system reinstalltion

**Comment by TheSystemGuy1337** [comment]
The software comes with no warranty. **Format and reinstall.**

**Comment by piotr25691** [comment]
have you tried doing stuff like

`sfc /scannow`
`dism /online /cleanup-image /restorehealth`

a couple times then restarting?

**Comment by TheSystemGuy1337** [comment]
> have you tried doing stuff like
> 
> `sfc /scannow` `dism /online /cleanup-image /restorehealth`
> 
> a couple times then restarting?

Like that's going to do anything; Rectify11 clearly hosed OP's installation to the point where both of these boilerplate commands will do nothing to help, or alternately make the issue worse.

OP must **format and reinstall.**

**Comment by qb20nh** [comment]
For me it fixed itself after Windows update.

**Comment by TheSystemGuy1337** [comment]
A Windows update is extremely unlikely to fix OPs problem; his OS is far too damaged to even be worth salvaging.

Again, the best course of action here is the good old format and reinstall.

**Comment by qb20nh** [comment]
You cac reinstall Windows without deleting installed programs and user data.

https://support.microsoft.com/en-us/windows/reinstall-windows-d8369486-3e33-7d9c-dccc-859e2b022fc7#bkmk_reinstall_windows_10_using_installation_media:~:text=Types%20of%20reinstalls%20for%20Windows%2010

**Comment by qb20nh** [comment]
How to reinstall Windows and keep the program and data

https://support.microsoft.com/en-us/windows/reinstall-windows-d8369486-3e33-7d9c-dccc-859e2b022fc7#bkmk_reinstall_windows_10_using_installation_media&WindowsVersion=Windows_11:~:text=Types%20of%20reinstalls%20for%20Windows%2011

**Comment by TheSystemGuy1337** [comment]
> How to reinstall Windows and keep the program and data
> 
> https://support.microsoft.com/en-us/windows/reinstall-windows-d8369486-3e33-7d9c-dccc-859e2b022fc7#bkmk_reinstall_windows_10_using_installation_media&WindowsVersion=Windows_11:~:text=Types%20of%20reinstalls%20for%20Windows%2011

OP, do not do this. In place reinstallations are unlikely to fix your problem. I did it with AtlasOS to try to fix Windows Update, and all it did was upgrade the OS, reinstall all the bloatware and nothing else. Formatting and traditional reinstallation is the best way forward.

**Comment by piotr25691** [comment]
> > have you tried doing stuff like
> > `sfc /scannow` `dism /online /cleanup-image /restorehealth`
> > a couple times then restarting?
> 
> Like that's going to do anything; Rectify11 clearly hosed OP's installation to the point where both of these boilerplate commands will do nothing to help, or alternately make the issue worse.
> 
> OP must **format and reinstall.**

Well, I have actually succeeded in restoring Windows 11 from the Rectify11/Windows 11 hybrid using those two and after I rebooted all changed files were restored to defaults. I also can’t see you being a contributor for this project. I think contributors would actually know if this is the case

**Comment by TheSystemGuy1337** [comment]
It might have worked for you, but there is no guarantee that these two very common and boilerplate commands will work for OP. Besides, his install from the pictures alone is far too gone for sfc /scannow and DISM to even help, all they will do is either nothing, or make the issue worse than it already is.

Best course of action: format and reinstall.

**Comment by piotr25691** [comment]
> It might have worked for you, but there is no guarantee that these two very common and boilerplate commands will work for OP. Besides, his install from the pictures alone is far too gone for sfc /scannow and DISM to even help, all they will do is either nothing, or make the issue worse than it already is. Best course of action: format and reinstall.

Bro still holding onto that solution 💀

**Comment by jerfer1111** [comment]
That's the Mica theme when it's uninstalled. I think you just change the theme back to light mode or dark mode

**Comment by MishaProductions** [comment]
Apply any theme from windows settings.
