### ISSUE TITLE
Java installer broken by Rectify11

### ISSUE THREAD

**Issue by CobaltBar** [Rectify11/Installer#448]
### Description

Java can't install if Rectify11 is installed. Uninstalling Rectify11 fixes the issue.
Also happens with Avast.

### Steps To Reproduce

Attempt to install Java x64

### Rectify11 Version

Latest actions build

### Windows Version

Windows 11 (latest, cant remember exact ver)

### Logs

None

**Comment by qb20nh** [comment]
What Java are you trying to install?

**Comment by MishaProductions** [comment]
it works fine for me
![image](https://github.com/Rectify11/Installer/assets/106913236/fbc92b2e-a62a-49e7-a885-6cad11402439)
