### ISSUE TITLE
Rectify11 Dark Theme not understanding what a game is

### ISSUE THREAD

**Issue by ukraineman345** [Rectify11/Installer#452]
### Description

Whenever I open a game, like Roblox, Minecraft, or Deltarune my screen just starts flashing black randomly for some reason????

### Steps To Reproduce

Open literally any 3d or 2d game with the rectify11 dark theme on, like Minecraft.

### Rectify11 Version

Version 3.1

### Windows Version

Windows 11 21H2 22000.2538

### Logs

I have no idea how to do that I'm sorry

**Comment by KaseyTheJackal** [comment]
That sounds like it's on your end, it works just fine for me
