### ISSUE TITLE
I can't launch my system control panel

### ISSUE THREAD

**Issue by ColorAWA** [Rectify11/Installer#454]
### Description

After installing Rectify 11, when I opened the "Rectify 11 Control Center" on my desktop and clicked on "Control Panel Home," the program became unresponsive.

### Steps To Reproduce

1. Install Rectify 11.
2. Open Rectify 11 Control Center.
3. Click on the Control Panel Home.

### Rectify11 Version

3.1

### Windows Version

Windows 11 22H2 23620

### Logs

No logs.

**Comment by MishaProductions** [comment]
this was fixed in latest github actions build
