### ISSUE TITLE
Do not modify specific programs.

### ISSUE THREAD

**Issue by is52hertz** [Rectify11/Installer#457]
Rectify’s Dark theme looks great overall.
But still **not compatible** with many software:
![image](https://github.com/Rectify11/Installer/assets/144510573/ee0ce681-2805-4c15-b7ae-238aee068582)
![image](https://github.com/Rectify11/Installer/assets/144510573/177a76d7-4838-4dfc-becf-d3a8f88410b2)
This makes an otherwise good-looking software/webpage look crappy.
I want the following functionality:
Maybe choosing Dark theme does not work on some software.
Add these options:

- [ ] Xampp (Specific run program)
- [ ] Edge (All pages)
- [ ] Wedsite: https://example.google.com (designated web page)

**Comment by MishaProductions** [comment]
Use partial dark theme
