### ISSUE TITLE
Dark theme at control panel broken on win11 update `KB5034204`

### ISSUE THREAD

**Issue by PRO-2684** [Rectify11/Installer#459]
### Description

Background still white after enabling dark theme. It works properly before the update.

![demo](https://github.com/Rectify11/Installer/assets/54608551/752d112f-a85c-4533-bb22-f449573b4685)

### Steps To Reproduce

Install `KB5034204` Windows update and restart

### Rectify11 Version

3.1.0.0

### Windows Version

Windows 11 23H2 22631.3085

### Logs

Screenshot is already attached at "Description".

**Comment by MishaProductions** [comment]
Repatch shell32
