### ISSUE TITLE
The control panel interface crashes（控制面板界面崩溃）

### ISSUE THREAD

**Issue by nulijiazaizhong** [Rectify11/Installer#460]
### Description

After the installation is complete, the control panel cannot be opened or the opening is stuck（安装完成后控制面板无法打开或者打开卡死）

### Steps To Reproduce

Question：
1、Double-clicking on the control panel or win+s search for the control panel and pressing enter will not open it（双击控制面板或者win+s搜索控制面板并回车均无法打开）

2、After the control panel is opened, there is no response and freezes（控制面板打开之后没有反应卡死）

3、From the Rectify 11 Setting screen that opens, when you click on the Control Panel in the navigation bar, the interface freezes（从打开的Rectify 11 Setting界面 点击导航栏中的控制面板时界面会卡死）
Resolution：
Restart  computer

### Rectify11 Version

Vwesion 3.1

### Windows Version

Windows 11 23H2 22631.3085

### Logs

![image](https://github.com/Rectify11/Installer/assets/127476147/369615fe-6a29-4a3e-a1ed-6070ac9dcd4a)

**Comment by MishaProductions** [comment]
install latest github actions build

**Comment by nulijiazaizhong** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by nulijiazaizhong** [comment]
Okay, I'm going to try it out, thanks
