### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by le0-VV** [Rectify11/Installer#468]
### Description

Installation failed, I was told by the installer to open an issue here with the installer.log

[installer.log](https://github.com/Rectify11/Installer/files/14250608/installer.log)

### Steps To Reproduce

1. Run the installer
2. It would fail after creating a restore point

### Rectify11 Version

3.1.0.0

### Windows Version

Windows 11 Pro Workstation 23H2, Build 22631.3085, Windows Feature Experience Pack 1000.22684.1000.0

### Logs

═════════════════════════════
START: 13/02/2024 7:22:49 AM
Rectify11 Version: 3.1.0.0
═════════════════════════════
Preparing Installation
──────────────────────
Wrote 7za.exe
Wrote files.7z
Wrote extras.7z
Wrote ResourceHacker.exe
WriteFiles() succeeded.
C:\WINDOWS\Rectify11\Backup already exists.
Extracting vcredist.exe from extras.7z
Extracting core31.exe from extras.7z
Executing vcredist.exe with arguments /install /quiet /norestart
vcredist.exe exited with error code 1638
Executing core31.exe with arguments /install /quiet /norestart
core31.exe exited with error code 1638
InstallRuntimes() succeeded.
══════════════════════════════════════════════
Installing Themes
─────────────────
Wrote themes.7z
Wrote SecureUXHelper.exe
Wrote ThemeDll.dll
WriteFiles() succeeded.
Extracted files.7z
Deleted old wallpapers.
Copied wallpapers to C:\WINDOWS\web\wallpaper\Rectified
Copied Themetool.
InstallThemes() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()

Deleted old wallpapers.
Deleted themes.
Themes.Install() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()
   at Rectify11Installer.Core.Themes.Install()

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

**Comment by Cipher-H7** [comment]
Disable your Windows Antivirus and It will work.

**Comment by Voidlighter** [comment]
Can confirm—I didn't disable my Windows Security, but I did have to open it and tell it to allow the process, and the next time the installer worked. 

(Sidenote, I don't know if this was just a me problem, but my Windows Security was broken until I ended all its processes in Task Manager, and then I was finally able to fix this issue)
