### ISSUE TITLE
Changes setting that are unavailable

### ISSUE THREAD

**Issue by Moherwinseptianto** [Rectify11/Installer#470]
### Description

I want to back to default option because I want to unpin some folder, but the option is not available
![image](https://github.com/Rectify11/Installer/assets/78137303/95ec960c-fe60-4107-a060-575d1bb75b48)

In Rectify11, the option show "Changes setting that are unavailable". I don't know what I should do.
![image](https://github.com/Rectify11/Installer/assets/78137303/ad2db52e-cde8-4f9f-8e48-738de0102fa1)

Is there any way to bring back Windows 11 menu default?

### Steps To Reproduce

Just right click in Windows Explorer

### Rectify11 Version

3.1.0.0

### Windows Version

23H2 22631.3085

### Logs

![image](https://github.com/Rectify11/Installer/assets/78137303/102cd7c0-d412-404f-bdf9-3cfbe0870570)

**Comment by MishaProductions** [comment]
Click on "Change settings that are unavailable" to make it available
