### ISSUE TITLE
Rectify11 Issues with ESET Antivirus

### ISSUE THREAD

**Issue by ghost** [Rectify11/Installer#477]
### Description

when eset and rectify11 are installed on the same device, eset would no longer open and the default antivirus change button won't work in windows security either. figured i could ask here since it works fine on normal windows.

### Steps To Reproduce

have ESET antivirus (https://eset.com) and rectify11 on the same pc

### Rectify11 Version

3.2.60.2

### Windows Version

23H 22631.3155

### Logs

![a9716180-b376-4a46-bf52-e692367723e4](https://github.com/Rectify11/Installer/assets/141976171/f2281d4a-32c6-445f-b26c-d9862f3c587c)

**Comment by boromyr** [comment]
I had the same problem and had to uninstall rectify11.

**Comment by Xferno2** [comment]
Having the same problem after installing rectifty11. Eset stops working and even after purging the eset installation the installer fails to install without uninstalling rectify11.

**Comment by REALMWTH** [comment]
Uncheck `msi.dll` from Advanced, this is the only library that prevents ESET from being loaded correctly.

**Comment by AngryDavid808** [comment]
> Uncheck `msi.dll` from Advanced, this is the only library that prevents ESET from being loaded correctly.

Hey, I was having the same issue as well. I'll try your solution and post an update once the other icons have finished installing.

**Comment by AngryDavid808** [comment]
Quick update! Skipping `msi.dll` seems to have worked perfectly! ESET still works even after installing all other icons.
