### ISSUE TITLE
Theme Install Fail

### ISSUE THREAD

**Issue by mazenelshemy** [Rectify11/Installer#479]
### Description

when I use the Rectify11 v3.1 installer to install themes, I get an error mentioning a "file not found" in the log file

### Steps To Reproduce

Step 1: Open the installer
Step 2: Click on "Modify" or "Install"
Step 3: Make sure "Themes" is checked
Step 4 (Optional): Select a theme and put any other options and preferences

### Rectify11 Version

Version 3.1

### Windows Version

Windows 11 v22H2 Build 22621.3155

### Logs

![Screenshot 2024-02-18 203656](https://github.com/Rectify11/Installer/assets/128849655/7cd988e9-a724-42ed-89ad-a0f80e0d0999)

Log:

═════════════════════════════
START: 18 Feb 2024 8:24:59 pm
Rectify11 Version: 3.1.0.0
═════════════════════════════
Preparing Installation
──────────────────────
Wrote 7za.exe
Wrote files.7z
Wrote extras.7z
Wrote ResourceHacker.exe
WriteFiles() succeeded.
C:\WINDOWS\Rectify11\Backup already exists.
Extracting vcredist.exe from extras.7z
Extracting core31.exe from extras.7z
Executing vcredist.exe with arguments /install /quiet /norestart
vcredist.exe exited with error code 1638
Executing core31.exe with arguments /install /quiet /norestart
core31.exe exited with error code 0
InstallRuntimes() succeeded.
══════════════════════════════════════════════
Installing Themes
─────────────────
Wrote themes.7z
Wrote SecureUXHelper.exe
Wrote ThemeDll.dll
WriteFiles() succeeded.
Extracted files.7z
Deleted old wallpapers.
Copied wallpapers to C:\WINDOWS\web\wallpaper\Rectified
Copied Themetool.
InstallThemes() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()

Deleted old wallpapers.
Deleted themes.
Themes.Install() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()
   at Rectify11Installer.Core.Themes.Install()

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

**Comment by ItsVeridian** [comment]
Themes won't install for me too

**Comment by zSudoKnight** [comment]
It's an easy fix. Just exclude Windows (C:)/ WINDOWS/ Rectify11 in your Windows Security app from virus checks
.

**Comment by mazenelshemy** [comment]
> It's an easy fix. Just exclude Windows (C:)/ WINDOWS/ Rectify11 in your Windows Security app from virus checks.

I tried this fix and it worked! Thank you so much.

**Comment by zSudoKnight** [comment]
No problem!
