### ISSUE TITLE
There are still some default icons that are still unchanged and needs rectifying.

### ISSUE THREAD

**Issue by theHeadlessGrapes** [Rectify11/Installer#481]
### Description

I recognise and appreciate the amount of work and effort required to modify each and every Windows default icon so that it conforms to the Windows 11 design language, but I would like to draw attention to the fact that some icons, as shown in the following file locations, have not been altered at all. This will make it a bit easier for icon designers here to find and identify the icons that have not been altered:

- %systemroot%\explorer.exe
- %systemroot%\system32\accessibilitycpl.dll
- %systemroot%\system32\mmcndmgr.dll
- %systemroot%\system32\netshell.dll
- %systemroot%\system32\networkexplorer.dll
- %systemroot%\system32\setupapi.dll
- %systemroot%\system32\wmploc.dll
- %systemroot%\system32\wpdshext.dll
- %systemroot%\system32\compstui.dll
- %systemroot%\system32\ieframe.dll
- %systemroot%\system32\mstsc.exe

### Steps To Reproduce

1. Open the "Properties" window from any shortcut file and select the "Change Icon" option.
2. Copy any these file location mentioned above to the "Look for icons in this file" box.
3. Look for any icons that don't match the design style of Windows 11 and rectify them!

### Rectify11 Version

Version: 3.1.0.0

### Windows Version

Windows 11 23H2 22635.3209

### Logs

N/A

**Comment by LittleNever** [comment]
I reboot my system about 2 or 3 times. it change the default icons

**Comment by RTFTR** [comment]
Explorer seems to be impossible, touching anything in it will cause it to crash constantly afaik

**Comment by theHeadlessGrapes** [comment]
I believe Resource Hacker could be used to find and change the icons within explorer.exe, no? Perhaps trying the icons on separate systems other than the main one to see if it functions?

![image](https://github.com/Rectify11/Installer/assets/158155682/0cb47923-2879-4e39-801a-713bacc62460)

**Comment by jerfer1111** [comment]
Depending on the program, I don't think we would ever see these icons. But yes, better get them Rectified!

**Comment by MishaProductions** [comment]
Those files are intentionally not modified as things would break.
