### ISSUE TITLE
The theme is broken

### ISSUE THREAD

**Issue by RobGames678** [Rectify11/Installer#482]
### Description

When windows automatically updates (or maybe to restore lost files) the dark theme gets broken !
Everything becomes unreadable, the buttons and titlebar become white, mlease help

### Steps To Reproduce

Update the system after installing Rectify11

### Rectify11 Version

2.0 and 3.0

### Windows Version

Windows 11 22h2 build 22000

### Logs

.

**Comment by Girofox** [comment]
When this happens press both keys `Win + i` and change the theme in UWP settings app (which should not be affected by this bug).

**Comment by Girofox** [comment]
By the way which options did you chose when installing Rectify11? Just Icons and Theme? I never had problems even when selecting theme before. Which theme did you chose in setup?
![image](https://github.com/Rectify11/Installer/assets/43116061/c7a6332f-d554-4f28-9a3c-b27e2611b993)

**Comment by MishaProductions** [comment]
Rerun the rectify11 installer
