### ISSUE TITLE
instalation of rectify11 has failed

### ISSUE THREAD

**Issue by BrunoPower25** [Rectify11/Installer#484]
### Description

how can i fix this

### Steps To Reproduce

when i click on install i get the message that the instalation has failed

### Rectify11 Version

3.1

### Windows Version

Windows 11 23H2 22631.3155

### Logs

[installer.log](https://github.com/Rectify11/Installer/files/14468780/installer.log)

**Comment by DamageCase13** [comment]
i get the same  issue
