### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by oiutretu** [Rectify11/Installer#489]
### Description

Installation of Rectify 1 1 has failed. Please send
C:\WlNDOWS\Rectify11\installer.log and open an issue
on GitHub or send it on the Rectify 1 1 Discord server for
help.

### Steps To Reproduce

Installation of Rectify 1 1 has failed. Please send
C:\WlNDOWS\Rectify11\installer.log and open an issue
on GitHub or send it on the Rectify 1 1 Discord server for
help.

### Rectify11 Version

3.1

### Windows Version

windows 11 24H2 26063 ge.release

### Logs

[installer.log](https://github.com/Rectify11/Installer/files/14510779/installer.log)

**Comment by oiutretu** [comment]
please warn users to turn off security like ame wizard when installing a playbook

**Comment by jerfer1111** [comment]
I have the same issue too. So is this issue just Windows Defender?

**Comment by jerfer1111** [comment]
Oh, Windows Defender Keeps Quarantining "Hacktool" and that's when the install fails¿
