### ISSUE TITLE
Rectify11 breaks x64dbg's persistence interface

### ISSUE THREAD

**Issue by bfloat16** [Rectify11/Installer#494]
### Description

After installing Rectify11:
![屏幕截图(15)](https://github.com/Rectify11/Installer/assets/38366253/b90ab086-d30f-4d31-b2a6-54b54555b25a)
The correct one should be like this, with file name and file type:
![image](https://github.com/Rectify11/Installer/assets/38366253/f9ffa00f-37b0-4a51-b97a-ca05344666f3)

### Steps To Reproduce

Just install Rectify11 and check all correct components.

### Rectify11 Version

3.2.62.2

### Windows Version

Windows 11 23H2 22631.3296

### Logs

None

**Comment by WinExperiments** [comment]
Should be fixed in 3.2.63.1
