### ISSUE TITLE
Overwritten Rectify Wallpapers

### ISSUE THREAD

**Issue by simpzophrenic** [Rectify11/Installer#495]
### Description

The wallpapers has been overwritten with no reason and no clue.

### Steps To Reproduce

Copy the img19 from the installer repository.

### Rectify11 Version

Rectify11 3.1 (Oct 31 Release)

### Windows Version

Windows 11 Enterprise LTSC 2024 Insider Preview 25941.1000

### Logs

![Windows 11 LTSC-2024-03-17-10-09-10](https://github.com/Rectify11/Installer/assets/90614108/01e1e452-1e46-488e-84d8-658416ec70d1)

**Comment by maybeiwasdreaming** [comment]
a small note: while using this in VM, i resized the screen and it stays the same, so it concludes that the file may have been overwritten.

**Comment by jerfer1111** [comment]
I don't have that directory in my Rectify 11 folder. I'm running the same version of Rectify 11.
<img width="1172" alt="Screenshot 2024-03-29 at 9 55 19 am" src="https://github.com/Rectify11/Installer/assets/137011961/9615bf40-2484-46e0-92bc-4e912400f5d6">

**Comment by maybeiwasdreaming** [comment]
@jerfer1111 huh, weird.

**Comment by MishaProductions** [comment]
probably a windows wallpaper cache bug
