### ISSUE TITLE
After Installing Rectify11, I cannot modify or uninstall it

### ISSUE THREAD

**Issue by MaliDragon2006** [Rectify11/Installer#496]
### Description

I've performed a clean installation of Windows 11, and decided to put Rectify11 on it. After receiving no help wihtin the [discord server](https://discord.gg/rectify11-community-1077324213142175744 for a long time, I had to remove my message and have to ask here in an attempt for an answer. 

All I want to fix is issues that cause this to happen in certain apps: 
![image](https://github.com/Rectify11/Installer/assets/69179169/8d2fc7a7-235a-4858-8324-69ef1fa60156)
![image](https://github.com/Rectify11/Installer/assets/69179169/b1e36740-faf7-4f3a-a40a-da7e89ae1466)
![image](https://github.com/Rectify11/Installer/assets/69179169/0306e01e-0792-40f2-a7a4-30ce17f22ca3)

I've also couldn't open the menu that has been put within the control panel, for some reason. 

### Steps To Reproduce

‎ 

### Rectify11 Version

Rectify11 v3.1

### Windows Version

Microsoft Windows Version 23H2 (OS Build 22631.2861)

### Logs
[installer.log](https://github.com/Rectify11/Installer/files/14650610/installer.log)

‎

**Comment by jerfer1111** [comment]
I'm pretty sure that's theme. Maybe don't use Mica and like go back into System Settings and Switch the theme to either Light or Dark

**Comment by MaliDragon2006** [comment]
I have already fixed this issue. It's becuase of the themes.

**Comment by jerfer1111** [comment]
Okay
