### ISSUE TITLE
Rectify11 is slightly broken

### ISSUE THREAD

**Issue by TFB2023** [Rectify11/Installer#500]
### Description

It installs succesfully, but when I try to open the Rectify11 Settings, it says "Failed to create DirectUI Parser E_FAIL".
And the winver and control panel are slightly broken, it does show in the theme, but some elements stay as default

### Steps To Reproduce

All i did was just install rectify11, and disable Real-Time Protection

### Rectify11 Version

3.1.0.0

### Windows Version

Windows 11 23H2 22631.3291

### Logs

![image](https://github.com/Rectify11/Installer/assets/153972286/eea258fd-fc4f-4092-80c7-27f37bb4a22a)
![image](https://github.com/Rectify11/Installer/assets/153972286/549eb20e-7d73-4a9e-8739-9e085dc815d1)
![image](https://github.com/Rectify11/Installer/assets/153972286/cb08fe0b-26b4-4b63-87d5-2128146b3e49)

**Comment by MishaProductions** [comment]
Install any icon in the installer

**Comment by TFB2023** [comment]
thanks! that actually worked out!
![image](https://github.com/Rectify11/Installer/assets/153972286/a500b7ec-138f-430d-815b-748f1f356eb2)
![image](https://github.com/Rectify11/Installer/assets/153972286/ed905868-7c6c-4915-adf1-ea2d4216c331)

**Comment by e-t-l** [comment]
> Install any icon in the installer

What does this mean exactly? I installed the R11 dark theme using SecureUXTheme (on unmodified Windows 11 OS) and it has the same problem with white elements in Control Panel.
