### ISSUE TITLE
Inconsistancy in UI

### ISSUE THREAD

**Issue by ShashankKalwa** [Rectify11/Installer#502]
### Description

The UI is not truly consistent.
I have tried both 3.1 and 3.0 versions, in both version I am having the same issue.
I am having the Windows 11 Beta build running on my computer.

### Steps To Reproduce

I did nothing, just did normal installation of Rectify 11.

### Rectify11 Version

3.0

### Windows Version

Windows 11 23H2 22635.3350

### Logs

Sorry i haven't copied it.

**Comment by MishaProductions** [comment]
Can you please provide more details? What is not consistent?

**Comment by ShashankKalwa** [comment]
![image](https://github.com/Rectify11/Installer/assets/93568767/6ef3e9c9-e0a4-4037-a2a6-83160bcb28f9)
The control panel and services panel are not in dark mode

**Comment by ShashankKalwa** [comment]
> Can you please provide more details? What is not consistent?

![image](https://github.com/Rectify11/Installer/assets/93568767/9445a1cc-008a-420d-9801-9ee240cc9444)

The control panel and services panel are not in dark mode

**Comment by MishaProductions** [comment]
Reinstall SecureUxTheme and reapply the rectify11theme in the rectify control panel.
