### ISSUE TITLE
Tilted Screen 

### ISSUE THREAD

**Issue by Gamiel-72** [Rectify11/Installer#503]
### Description

I am using an virtual machine to test out rectify v2 in a virtual machine [(Downloaded on dl.malwarewatch.org](https://dl.malwarewatch.org/windows/mods/Rectify11-v2.iso) and the setup was normal , but when the virtual machine restarted , it was tilted , it had to restart again , and then it started as normal but the logon was tilted , and when i entered the desktop was like tilted a lot to the point where i could see the wallpaper repeated.
![Screenshot 1](https://github.com/Rectify11/Installer/assets/164921120/c6dd09f5-59ef-4e3c-93f0-5ac28f456872)
![Screenshot 2](https://github.com/Rectify11/Installer/assets/164921120/ada9b19d-5234-4821-b87d-1ab8031ba703)
![Screenshot 3](https://github.com/Rectify11/Installer/assets/164921120/647e89df-8e67-4272-bb2e-c79de95b20c3)

### Steps To Reproduce

1. Have A Virtual Machine Software (VMware Workstation 17 Prefered)
2. [Download the ISO from this website](https://dl.malwarewatch.org/windows/mods/Rectify11-v2.iso)
3. Setup the Virtual Machine
4. Setup Windows

### Rectify11 Version

Rectify11-v2

### Windows Version

ISO with built-in Rectify 11 idk

### Logs

no log , ISO with built in Rectify 11

**Comment by RTFTR** [comment]
Don't use Rectify11 V2, Rectify11 has moved to being an installer and there will be no ISO updates

**Comment by WinExperiments** [comment]
Outdated Rectify11 ISO from February 2022.
