### ISSUE TITLE
Gray rectangle on desktop

### ISSUE THREAD

**Issue by windowz98** [Rectify11/Installer#506]
I use a Dell Inspiron 15 7535 2-in-1.
For some reason, a gray rectangle on the desktop appeared after i installed Rectify11.

What caused this to appear, and how can i get rid of it?
![Screenshot 2024-03-29 150919](https://github.com/Rectify11/Installer/assets/165424774/eb8381ef-f158-4d12-9a86-e86ccd282e16)

**Comment by EDM115** [comment]
duplicate of #359

**Comment by kameno22** [comment]
its just some startup app which doesnt support mica for everyone backdrop mode , u need to figure out the app and exclude in mfe so it will stop rendering the effect for it.

**Comment by matt-dong-123** [comment]
or just open the app and it'll disappear

**Comment by windowz98** [comment]
> Re

Fixed, it was the Wireless Display Adapter!
