### ISSUE TITLE
Redistributable error

### ISSUE THREAD

**Issue by ElistanCoding** [Rectify11/Installer#517]
### Description

Error installing Redistributable.

### Steps To Reproduce

Use version Windows 10 22H2 build 19045.4291.
Use every feature.
You will get an error. (for me) 

### Rectify11 Version

v3.1

### Windows Version

Windows 10 22H2 build 19045.4291

### Logs

═════════════════════════════
START: 10/04/2024 17.45.43
Rectify11 Version: 3.1.0.0
═════════════════════════════
Preparing Installation
──────────────────────
Wrote 7za.exe
Wrote files.7z
Wrote extras.7z
Wrote ResourceHacker.exe
WriteFiles() succeeded.
Extracting vcredist.exe from extras.7z
Extracting core31.exe from extras.7z
Executing vcredist.exe with arguments /install /quiet /norestart
vcredist.exe exited with error code 1638
Executing core31.exe with arguments /install /quiet /norestart
core31.exe exited with error code 0
InstallRuntimes() succeeded.
══════════════════════════════════════════════
Installing Themes
─────────────────
Wrote themes.7z
Wrote SecureUXHelper.exe
Wrote ThemeDll.dll
WriteFiles() succeeded.
Extracted files.7z
Copied wallpapers to C:\WINDOWS\web\wallpaper\Rectified
Copied Themetool.
InstallThemes() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()

Deleted old wallpapers.
Deleted themes.
Themes.Install() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()
   at Rectify11Installer.Core.Themes.Install()

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

**Comment by maybeiwasdreaming** [comment]
I think, the problem is that Rectify 11 is **only** for Windows 11, and it may not work and break your system.

**Comment by ooTruffle** [comment]
Please disable windows defender, it removed what r11 uses to install the theme

@simpzophrenic 
R11 can work for windows 10 but is not recomended, Personaly i dont use the installer on 10 and manualy patch files.
