### ISSUE TITLE
Can't come back to Windows default after uninstall

### ISSUE THREAD

**Issue by Jiang10086** [Rectify11/Installer#518]
### Description

I installed the latest releases version [(v3.1](https://github.com/Rectify11/Installer/releases/tag/v-3.1-fixed2)), but I find I can't launch control panel after install it, and I searched an issue tells me to installed the action version, so I install the [latest action version](https://github.com/Rectify11/Installer/actions/runs/8554254562). But I after install, control panel still didn't launch. And even worse: some of my app goes an ugly white and black background. So I decided to uninstall it. But after I uninstall it twice (first I use the action version exe, and restarted found problem unsolved, so I use the release version to uninstall again), this remain the same.

### Steps To Reproduce

1. Install the releases version
2. Install the action version
3. Uninstall both

### Rectify11 Version

3.1.1.0

### Windows Version

Windows 11 23H2 22631.3447

### Logs

![image](https://github.com/Rectify11/Installer/assets/67213568/50e708a3-2ccc-449a-97c6-974072734b33)
![image](https://github.com/Rectify11/Installer/assets/67213568/91af6a42-70bb-415d-86a0-69988c422895)
![image](https://github.com/Rectify11/Installer/assets/67213568/4c61937b-183e-44ee-9762-02c6937288c3)

**Comment by USLTD** [comment]
Try selecting your default theme.

**Comment by Jiang10086** [comment]
> Try selecting your default theme.

Ok, ugly looking issue is fixed, but still can't launch the Control Panel

**Comment by USLTD** [comment]
Do you mean stock Control Panel? Or Rectify11's Control Panel?

**Comment by Jiang10086** [comment]
> stock Control Panel

I mean the Windows system control panel, but I don't what happened, I can launcher the  system control panel now.

**Comment by USLTD** [comment]
Just in case run **DISM** and **SFC** commands to make sure nothing is corrupted on your system.

Here's [**forum link**](https://www.tenforums.com/performance-maintenance/161345-what-correct-order-dism-sfc-commands-fix-problems.html)[^1] for the order in which you need to run each command.

[^1]: Disclaimer: I'm not responsible for any damage that occurs from the moment this comment gets sent. I hope you will research what each command does and will not blindly copy-paste them.

**Comment by Jiang10086** [comment]
> Just in case run **DISM** and **SFC** commands to make sure nothing is corrupted on your system.
> 
> Here's [**forum link**](https://www.tenforums.com/performance-maintenance/161345-what-correct-order-dism-sfc-commands-fix-problems.html)[1](#user-content-fn-1-ec25ce3d5459c7e361c47c1e14722240) for the order in which you need to run each command.
> ## Footnotes
> 
>     1. Disclaimer: I'm not responsible for any damage that occurs from the moment this comment gets sent. I hope you will research what each command does and will not blindly copy-paste them. [↩](#user-content-fnref-1-ec25ce3d5459c7e361c47c1e14722240)

Nice idea.

I got this problem again (but I can launch control panel this time), I fixed it by heading to system's setting - personalization - theme, and choose the default Windows dark theme. Now I completely uninstalled Rectify11 and go back to the Windows default.
