### ISSUE TITLE
Sent install.log to GitHub Issue.

### ISSUE THREAD

**Issue by Nickson1209** [Rectify11/Installer#520]
### Description

The install.log file sent me here!

### Steps To Reproduce

I ran the installer
![Screenshot 2024-04-17 195649](https://github.com/Rectify11/Installer/assets/167344322/ce2fe26f-50a9-4d6f-9d72-06ea00d33bf7)
 and I made first steps and in one time, the installer gave me an error that says in: C:/Windows/Rectify11/install.log to sent to GitHub issue.

### Rectify11 Version

Rectify11 v3.1

### Windows Version

Windows 11 23H3 OS 22631.3447

### Logs

═════════════════════════════
START: 17-Apr-24 7:40:02 PM
Rectify11 Version: 3.1.0.0
═════════════════════════════
Preparing Installation
──────────────────────
Wrote 7za.exe
Wrote files.7z
Wrote extras.7z
Wrote ResourceHacker.exe
WriteFiles() succeeded.
C:\Windows\Rectify11\Backup already exists.
Extracting vcredist.exe from extras.7z
Extracting core31.exe from extras.7z
Executing vcredist.exe with arguments /install /quiet /norestart
vcredist.exe exited with error code 1638
Executing core31.exe with arguments /install /quiet /norestart
core31.exe exited with error code 0
InstallRuntimes() succeeded.
══════════════════════════════════════════════
Installing Themes
─────────────────
Wrote themes.7z
Wrote SecureUXHelper.exe
Wrote ThemeDll.dll
WriteFiles() succeeded.
Extracted files.7z
Deleted old wallpapers.
Copied wallpapers to C:\Windows\web\wallpaper\Rectified
Copied Themetool.
InstallThemes() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()

Deleted old wallpapers.
Deleted themes.
Themes.Install() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()
   at Rectify11Installer.Core.Themes.Install()

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

**Comment by MishaProductions** [comment]
Please read existing GitHub issues and the faq

**Comment by Nickson1209** [comment]
A link bro?

**Comment by AqdasDar** [comment]
disable your antivirus or go to widows security , history of protection find rectify and authorize it

**Comment by Nickson1209** [comment]
Thank you bro, thanks
