### ISSUE TITLE
League of Legends client broken

### ISSUE THREAD

**Issue by doGior** [Rectify11/Installer#521]
### Description

At the end of a game of league of legends, when you're supposed to view the stats of the match, the client opens but there's only a tiny rectangle readable and the rest is my desktop background but blurred

### Steps To Reproduce

Play a game of LoL

### Rectify11 Version

3.1.0.0

### Windows Version

Windows 11 23H2

### Logs

![immagine](https://github.com/Rectify11/Installer/assets/43815981/979a88d0-0cad-4daf-8782-0af0132355f5)

**Comment by ApartTUSITU** [comment]
Installed micaforeveryone?

**Comment by doGior** [comment]
I do and I think that's the problem, because closing it and then closing and reopening lol fixes the problem

**Comment by Blue-Star-Technology** [comment]
create a rule on micaforeveryone for league of legends and disable micaforeveryone just for league of legends

**Comment by doGior** [comment]
How do I do that?
