### ISSUE TITLE
How to Switch context menus with Recitfy11 already installed

### ISSUE THREAD

**Issue by MaliDragon2006** [Rectify11/Installer#522]
### Description

I have installed Rectify11 on my Windows 11 home machine with all items in root as my context menu choice, but I want to switch it to the classic context menu but I don't know how to do that when Recitfy 11 has been already installed on there. 

### Steps To Reproduce

Install Rectify11 on a clean laptop. That's pretty much it.

### Rectify11 Version

Latest verson

### Windows Version

Windows 11 23H2 22631.3447

### Logs

‎

**Comment by kuildor** [comment]
Open Rectify Control Center, click on "Change settings that are unavailable", and check the prefer menu style.

**Comment by MaliDragon2006** [comment]
Where do I find the Rectify Control Center?

**Comment by EDM115** [comment]
@MaliDragon2006 Win + R, `C:\Windows\System32\control.exe /name Rectify11.SettingsCPL`
