### ISSUE TITLE
AVG antivitus not working

### ISSUE THREAD

**Issue by MatrixXD** [Rectify11/Installer#527]
### Description

When I install Rectify 11 AVG antivirus crashing even when i reinstall Antivirus/Rectify 11

### Steps To Reproduce

I dont know

### Rectify11 Version

Version: 3.1

### Windows Version

Windows 11 Wersja 23H2 (kompilacja systemu operacyjnego: 22631.3447)

### Logs

I cant get log from AVG Antivitus

**Comment by ooTruffle** [comment]
Please dont use AVG its a shovel ware av

just stick with defender or use a diffrent av
