### ISSUE TITLE
Rectify11 Setup text barely visible with monitor HDR on

### ISSUE THREAD

**Issue by Girofox** [Rectify11/Installer#528]
### Description

When I start the Rectify11 setup, i cannot read the menu elements in setup window when HDR is on (Nvidia). When I try to take a screenshot via `Win + Shift + S` or via `Print` key the text is shortly visible. This seems like an bug related to HDR.

### Steps To Reproduce

- Turn on HDR
- Launch Rectify11 setup

### Rectify11 Version

Version: 3.1

### Windows Version

Windows 11 23H2 22631.3527

### Logs

No log, can't take screenshot because then text is visible.

**Comment by BlankFX1** [comment]
[Already known Issue.](https://github.com/Rectify11/Installer/issues/345)
