### ISSUE TITLE
Uninstall error

### ISSUE THREAD

**Issue by AT-3109** [Rectify11/Installer#530]
### Description

When I run the uninstall.exe and click uninstall, it stes the windows theme to default but doesnt uninstall anything and instantly shows an error message
![Screenshot 2024-05-02 211834](https://github.com/Rectify11/Installer/assets/116757809/8876c20c-8a25-485f-85b7-48bd3ec02fc3)

### Steps To Reproduce

-Run uninstall.exe
-Press uninstall

### Rectify11 Version

3.0.24.0

### Windows Version

Windows 11 23H2 22631.3447

### Logs

═════════════════════════════
START: 02/05/2024 21:07:13
Rectify11 Version: 3.1.0.0
═════════════════════════════
Uninstalling themes
───────────────────
Wrote SecureUXHelper.exe
Wrote ThemeDll.dll
Themes.Uninstall() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.Uninstall()

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

**Comment by MishaProductions** [comment]
read the faq
