### ISSUE TITLE
Error install themes 

### ISSUE THREAD

**Issue by arvrekis2004** [Rectify11/Installer#531]
### Description

![image](https://github.com/Rectify11/Installer/assets/164420811/866f3398-d044-40f0-8747-1e6e8c7c6557)
![image](https://github.com/Rectify11/Installer/assets/164420811/f2d628af-d631-4076-9230-e965f70bba59)

### Steps To Reproduce

![image](https://github.com/Rectify11/Installer/assets/164420811/866f3398-d044-40f0-8747-1e6e8c7c6557)
![image](https://github.com/Rectify11/Installer/assets/164420811/f2d628af-d631-4076-9230-e965f70bba59)

### Rectify11 Version

Version: (3.2)

### Windows Version

WINDOWS 11LTSC 26100.268 (24H2)

### Logs

![image](https://github.com/Rectify11/Installer/assets/164420811/866f3398-d044-40f0-8747-1e6e8c7c6557)
![image](https://github.com/Rectify11/Installer/assets/164420811/0ecdcbd0-6ba1-4be3-9d4e-ae98108563fc)

**Comment by natesworks** [comment]
This is the worst issue I've ever seen

**Comment by MishaProductions** [comment]
Fixed in latest commit
