### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by jtalion41116** [Rectify11/Installer#532]
### Description

![image](https://github.com/Rectify11/Installer/assets/168945868/996f4b39-3f78-4342-b060-01a86cead9f2)
When I was installing Rectify11 I got this theme error message.

### Steps To Reproduce

First, I was installing, then it was installing everything needed for Rectify11. While it's installing on themes I got an error message

### Rectify11 Version

3.1.0.0

### Windows Version

Windows 11 22621.3527

### Logs

═════════════════════════════
START: 05/05/2024 10:16:15 am
Rectify11 Version: 3.1.0.0
═════════════════════════════
Preparing Installation
──────────────────────
Wrote 7za.exe
Wrote files.7z
Wrote extras.7z
Wrote ResourceHacker.exe
WriteFiles() succeeded.
C:\Windows\Rectify11\Backup already exists.
Extracting vcredist.exe from extras.7z
Extracting core31.exe from extras.7z
Executing vcredist.exe with arguments /install /quiet /norestart
vcredist.exe exited with error code 1638
Executing core31.exe with arguments /install /quiet /norestart
core31.exe exited with error code 1638
InstallRuntimes() succeeded.
══════════════════════════════════════════════
Installing Themes
─────────────────
Wrote themes.7z
Wrote SecureUXHelper.exe
Wrote ThemeDll.dll
WriteFiles() succeeded.
Extracted files.7z
Deleted old wallpapers.
Copied wallpapers to C:\Windows\web\wallpaper\Rectified
Copied Themetool.
InstallThemes() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()

Deleted old wallpapers.
Deleted themes.
Themes.Install() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()
   at Rectify11Installer.Core.Themes.Install()

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

**Comment by dhgouveia2** [comment]
same issue
![image](https://github.com/Rectify11/Installer/assets/24292467/61e5c058-c5f3-4e2b-84fb-aab9dd6d54e9)

**Comment by gongmengyang** [comment]
![Snipaste_2024-05-06_19-41-18](https://github.com/Rectify11/Installer/assets/59244030/da0891d6-070a-4640-8749-2caeea7e0cff)

**Comment by jtalion41116** [comment]
![image](https://github.com/Rectify11/Installer/assets/168945868/111a4406-a5ad-4c6c-9770-7c0fc3c44768)

**Comment by Yanfiq** [comment]
Try checking windows defender, I've experienced something similar and it turned out that the SecureUXHelper program was quarantined. Once allowed, try repeating the installation process.

**Comment by koyuawsmbrtn** [comment]
Yep, please add C:\Windows\Rectify11 to your exceptions in Windows Defender
