### ISSUE TITLE
Download link 3.1

### ISSUE THREAD

**Issue by Shawn9347** [Rectify11/Installer#538]
### Description

Where can I download version 3.1? 

### Steps To Reproduce

-

### Rectify11 Version

3.1

### Windows Version

-

### Logs

-

**Comment by MishaProductions** [comment]
Use GitHub actions build

**Comment by EDM115** [comment]
@MishaProductions you can check what I did in https://github.com/Rectify11/Website/pull/3  
if merged, you could just say "go on the website and click download", which will help people not understanding what actions are or other  
note that I tried to make it a markdown-compatible button, but failed as GitHub would render the javascript as plain text anyway
