### ISSUE TITLE
I found some application icons non rectified

### ISSUE THREAD

**Issue by foursplaysroblox** [Rectify11/Installer#539]
### Description

They are using old icons there are not rectified

### Steps To Reproduce

put "*.exe" in the file explorer search bar in system32 folder

### Rectify11 Version

Rectify11 v3.1 (Actions Build)

### Windows Version

Windows 11 Home 23H2 22631.3527

### Logs

List of applications
![image](https://github.com/Rectify11/Installer/assets/82078139/c1921c29-0115-4359-93ef-829f1d62371b)
![image](https://github.com/Rectify11/Installer/assets/82078139/0697364b-8a88-419b-9515-aea0e20bf282)
![image](https://github.com/Rectify11/Installer/assets/82078139/3312b113-4f5a-44de-87cb-1d038eede0cf)
![image](https://github.com/Rectify11/Installer/assets/82078139/038d57f3-19e2-400e-956c-d02b71b58d91)

**Comment by ooTruffle** [comment]
Why take the time to rectify icons for apps that are never used / seen

R11 at face value patches icons that the user is most likely to see in day to day use

**Comment by MishaProductions** [comment]
I don't think that these icons are used anywhere.
