### ISSUE TITLE
Installation Warning on Windows 11 24H2

### ISSUE THREAD

**Issue by errypuu** [Rectify11/Installer#542]
### Description

Warning message "You are running a build of Windows that is too new to be fully supported by Rectify 11"
![image](https://github.com/Rectify11/Installer/assets/2776081/dbd9f04e-2696-46bc-8e3a-21e7099ec70a)

Is this safe to run?

### Steps To Reproduce

1. Open the Installer

### Rectify11 Version

Version 3.1 Build date: Oct 31, 2023

### Windows Version

Windows 11 24H2 26100.712

### Logs

![image](https://github.com/Rectify11/Installer/assets/2776081/70c590af-a311-464d-b4d9-6d7a3531db1a)

**Comment by ilan0098** [comment]
The problem isn't only just a warning message, but the installer actually fails when you try to install it since it has some errors.

**Comment by Nico202009** [comment]
i have 24h2 same problem but i tried on a windows 11 23h2 vm and i get the same errors during installation the one with many zeros the vm also has no windows defender and no antivirus

**Comment by kamez104** [comment]
W
