### ISSUE TITLE
Link to the latest Actions build download

### ISSUE THREAD

**Issue by 03302024** [Rectify11/Installer#543]
### Description

On https://github.com/Rectify11/Installer/releases page, it reads:

NOTE: WE HIGHLY RECOMMEND USING LATEST GITHUB ACTIONS BUILD FOR BEST STABILITY!

But, where I could find the latest Actions build download? Any download link, please?

### Steps To Reproduce

N/A

### Rectify11 Version

N/A

### Windows Version

N/A

### Logs

N/A

**Comment by wjpvandenheuvel** [comment]
You can find it here:
https://github.com/Rectify11/Installer/actions/runs/8823085428

**Comment by MishaProductions** [comment]
Please don't open an issue for a question, use https://rectify11.net

**Comment by 03302024** [comment]
> You can find it here: https://github.com/Rectify11/Installer/actions/runs/8823085428

Great, thank you!
