### ISSUE TITLE
Rectify 11 Startup Window buttons don't work.

### ISSUE THREAD

**Issue by EliasRonefors** [Rectify11/Installer#544]
### Description

Clicking the buttons "Check it out" and "Turn on" do nothing at all. Nothing happens when clicking on them. The "Close" button works however.
![image](https://github.com/Rectify11/Installer/assets/90244703/4ae70101-9715-401b-9f37-c32e17496bfe)

### Steps To Reproduce

1. Download Rectify11 and start the installer
2. Choose options for all the icons and the enhanced context menus and accent color colorizing extras.
3. After installation, restart.
4. After restart, try pressing buttons in the Rectify11 popup window. The "Check it out" and "Turn on" buttons won't work.

### Rectify11 Version

3.2.63.4

### Windows Version

Windows 11 Home 23H2 22631.3593

### Logs

![image](https://github.com/Rectify11/Installer/assets/90244703/4ae70101-9715-401b-9f37-c32e17496bfe)
[installer.log](https://github.com/Rectify11/Installer/files/15447358/installer.log)

Some relevant information might be:
* I've used nilesoft shell before (the program used for the fancier context menus) but it was uninstalled right before installing rectify11.
* I am using StartAllBack but I tried this with all StartAllBack settings off and that didn't change anything.

**Comment by MishaProductions** [comment]
I will implement that soon.
