### ISSUE TITLE
Selected files in File Explorer don't appear selected

### ISSUE THREAD

**Issue by EliasRonefors** [Rectify11/Installer#545]
### Description

When selecting a file or folder in File Explorer there is usually a half-transparent rectangle around it to indicate it is selected. After installing Rectify11 selected files/folders no longer have that rectangle to show that they are selected. In the image below the "Rectify11Installer(x64)" is currently selected but doesn't visually show that it is selected.
![image](https://github.com/Rectify11/Installer/assets/90244703/2e538c66-2639-4f26-bb06-d50683e4ed34)

In this second image two files/folders are selected. Here only one of them appears selected even though both should have the rectangle around them.
![image](https://github.com/Rectify11/Installer/assets/90244703/eab981b1-dd09-4d00-8f40-2f310de6e03e)

### Steps To Reproduce

1. Install Rectify11 with all icons and the enhanced context menus and accent color colorizing extras.
2. Restart.
3. Open File Explorer and try selecting one or multiple files/folders.

### Rectify11 Version

3.2.63.4

### Windows Version

Windows 11 Home 23H2 22631.3593

### Logs

![image](https://github.com/Rectify11/Installer/assets/90244703/2e538c66-2639-4f26-bb06-d50683e4ed34)
![image](https://github.com/Rectify11/Installer/assets/90244703/eab981b1-dd09-4d00-8f40-2f310de6e03e)
[installer.log](https://github.com/Rectify11/Installer/files/15447451/installer.log)

**Comment by MishaProductions** [comment]
@WinExperiments

**Comment by WinExperiments** [comment]
You must use the Rectify11 themes as @DOOMsang said.
