### ISSUE TITLE
Problem with msstyle themes in the properties panel.

### ISSUE THREAD

**Issue by boromyr** [Rectify11/Installer#547]
### Description

The properties tab looks like this with the rectify theme:
![image](https://github.com/Rectify11/Installer/assets/52782032/11c25907-042b-4b97-8d21-5457fc80321d)

### Steps To Reproduce

Apply the theme rect

### Rectify11 Version

3

### Windows Version

Windows 11 22635.3646

### Logs

none

**Comment by MishaProductions** [comment]
are you applying it through the rectify11 control panel?

**Comment by boromyr** [comment]
yes, I tried them all, only the dark theme doesn't have this problem, I tested on two PCs

**Comment by WinExperiments** [comment]
StartAllBack interference. Please report it to the developer or uninstall it if you want to keep using Rectify11 themes.
