### ISSUE TITLE
Excel broken

### ISSUE THREAD

**Issue by portex7000** [Rectify11/Installer#551]
### Description

Excel is broken because of force dark theme (office 2021)

### Steps To Reproduce

1. Open excel with rectify11 installed

### Rectify11 Version

3.0.48.0

### Windows Version

Windows 11 23H2 insider 22635.3646

### Logs

![image](https://github.com/Rectify11/Installer/assets/150171265/9e962dbf-a503-4d19-9bc1-1eb8c634066a)

**Comment by ooTruffle** [comment]
Hi there

This is a bug on microsofts side as they do weird things with msstyles

Please install this community patch
https://github.com/matafokka/ExcelDarkThemeFix
