### ISSUE TITLE
Can not uninstall nor instal

### ISSUE THREAD

**Issue by ANDREW007CZ** [Rectify11/Installer#553]
### Description

Installed Rectify11, which did not work as expected. I have previous experience with installing it. Tried to unistall, it worked fine. After that I did a new installation which did got stuck. Closed the installation by force. Tried installation again which does not work and uninstallation either. Both throw unhandled expection pointing to log. Here it is.

═════════════════════════════
START: 05.06.2024 22:32:15
Rectify11 Version: 3.2.70.1
═════════════════════════════
Uninstalling themes
───────────────────
Themes.Uninstall() failed. Retrieving the COM class factory for component with CLSID {9CD66066-9784-4DA6-A27A-D322FC96D02E} failed due to the following error: 80040154 Třída není zaregistrována (0x80040154 (REGDB_E_CLASSNOTREG)).
   at Rectify11Installer.Win32.RectifyThemeUtil.Init() in D:\a\Installer\Installer\Rectify11Installer\Win32\RectifyUtil.cs:line 47
   at Rectify11Installer.Win32.RectifyThemeUtil.get_Utility() in D:\a\Installer\Installer\Rectify11Installer\Win32\RectifyUtil.cs:line 37
   at Rectify11Installer.Core.Themes.Uninstall() in D:\a\Installer\Installer\Rectify11Installer\Core\Backend\Themes.cs:line 114

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

### Steps To Reproduce

Installed Rectify11, which did not work as expected. I have previous experience with installing it. Tried to unistall, it worked fine. After that I did a new installation which did got stuck. Closed the installation by force. Tried installation again which does not work and uninstallation either. Both throw unhandled expection pointing to log. 

### Rectify11 Version

cant figure out, latest from web by now

### Windows Version

Win11 23H2 22631.3593

### Logs

it just says to throw log here

**Comment by ANDREW007CZ** [comment]
mkay, so I did clean install after all. Not going to install Rectify again anytime soon, this does not seems like a legit behaviour a program should do. After reading the log, if it's any help, feel free to close it.

**Comment by HaroleDev** [comment]
Same issue, even just after installing it, I can't uninstall it.

**Comment by MishaProductions** [comment]
closing as installation log when it got stuck is not provided
