### ISSUE TITLE
rectify11 broke my pc after uninstalling

### ISSUE THREAD

**Issue by aryanmaulana7636** [Rectify11/Installer#554]
### Description

after uninstalling rectify11, it broke my computer, reason for this, because uninstall removed explorer.exe

### Steps To Reproduce

1. uninstall rectify11
2. broke my computer because no explorer.exe
3. i had to use system scan, after uninstalling rectify11.

### Rectify11 Version

Rectify11 3.2 for latest actions build (Jun 5 2024)

### Windows Version

Windows 11 24H2 26100.712

### Logs

none

**Comment by ANDREW007CZ** [comment]
are rectify builds even being tested before releasing to public?

**Comment by ooTruffle** [comment]
> are rectify builds even being tested before releasing to public?

Action builds are beta

And 24h2 is also unreleased

**Comment by ANDREW007CZ** [comment]
> > are rectify builds even being tested before releasing to public?
> 
> Action builds are beta
> 
> And 24h2 is also unreleased

that I'd understand. But this was problem with installer downloaded from official rectify11 website. As I see it's not just me having problem this question came to my mind..

**Comment by ooTruffle** [comment]
> > > are rectify builds even being tested before releasing to public?
> > 
> > 
> > Action builds are beta
> > And 24h2 is also unreleased
> 
> that I'd understand. But this was problem with installer downloaded from official rectify11 website. As I see it's not just me having problem this question came to my mind..

what windows version

**Comment by ANDREW007CZ** [comment]
> > > > are rectify builds even being tested before releasing to public?
> > > 
> > > 
> > > Action builds are beta
> > > And 24h2 is also unreleased
> > 
> > 
> > that I'd understand. But this was problem with installer downloaded from official rectify11 website. As I see it's not just me having problem this question came to my mind..
> 
> what windows version

23H2 22631.3593

**Comment by aryanmaulana7636** [comment]
> > are rectify builds even being tested before releasing to public?
> 
> Action builds are beta
> 
> And 24h2 is also unreleased

24h2 is beta, but it can be found in release preview channel for insider preview

**Comment by aryanmaulana7636** [comment]
they fixed this issue: https://github.com/Rectify11/Installer/actions/runs/9486872849
