### ISSUE TITLE
I can't switch themes.

### ISSUE THREAD

**Issue by MaxLHy0424** [Rectify11/Installer#556]
### Description

After installing Rectify 11, after about 30 seconds of switching themes in the Rectify Control Center, the dashboard crashes and the theme is not switched.

### Steps To Reproduce

1. Open the Rectify 11 Control Center;
2. Switch themes.

### Rectify11 Version

Verson 3.2.70.1

### Windows Version

Windows 11 24H2 Insider Preview 26231.5000

### Logs

(None logs)

**Comment by ooTruffle** [comment]
This is insider....

Beta windows builds are knowen to break things

**Comment by MaxLHy0424** [comment]
Hmm... I found a solution: install the theme with the installer from v3.1 first, and then install the icon with the installer from v3.2.
