### ISSUE TITLE
Decently messed up explorer and other things

### ISSUE THREAD

**Issue by julianpoelmann** [Rectify11/Installer#559]
I'm having the same issue like this person https://github.com/Rectify11/Installer/issues/558

But I also got a few others now. The tabs and progress bars do not appear to have changed even after switching around the themes.

The background of the explorer keeps becoming transparent which I've fixed by removing the rule in Mica For Everyone.

The explorer background executable thing that Mica For Everyone has also breaks the text transparency. 
I've fixed that by removing EFamd64 from C:\Windows\MicaForEveryone

The tabs didn't get modified and have remained horribly inconsist.
![IMG20240608230604.jpg](https://github.com/Rectify11/Installer/assets/28513665/c9b46131-e4c4-40b0-898f-f3c38a3b2b03)

Can't really show proper screenshots as I basically tried this on my laptop to test and see if it'll work.

The laptop has defender turned off.
Its running tiny11 pro 23h2 (basically 22h2)

I can confirm rectify11 works on tiny11 22h2 (the actual one) since I've used that for a long long time but that was an older build

I couldn't find the reporting guidelines so I apologize if I missed something. The templates also refused to open on my phone since well.. I can't open it on my pc

**Comment by julianpoelmann** [comment]
Doesn't work on my end

**Comment by MishaProductions** [comment]
Try reapplying theme
