### ISSUE TITLE
Recycle Bin broken

### ISSUE THREAD

**Issue by OliverBorgmann** [Rectify11/Installer#560]
### Description

The command "Empty Recycle Bin" in the context menu of the recycle bin icon is grayed out after installing the latest Actions build and no longer works

### Steps To Reproduce

Install on latest Retail Windows 11 24H2 26100.712
Rectify Installer 3.2.70.1
Disabled Defender
Exclude Rectify11 in C://Windows

### Rectify11 Version

Rectify Installer 3.2.70.1

### Windows Version

Windows 11 24H2 26100.712

### Logs

No Log available

**Comment by Ianzb** [comment]
It only occurred when Nilesoft Shell styled menu is opened. So it's Rectify11's problem not related to Recycle Bin itself.

**Comment by Jank8** [comment]
Ive noticed that its broken on languages other than english.

**Comment by Jank8** [comment]
Heres the FIX. 
1. Download latest installer/portable from https://nilesoft.org/download
2. Extract files (DO NOT INSTALL)
3. Copy shell.exe and shell.dll from extracted directory to C:\Windows\nilesoft using live linux or other offline tool of choosing.
4. Reboot.

**Comment by MishaProductions** [comment]
Can you please check if this is fixed in the latest build?

**Comment by OliverBorgmann** [comment]
You need the Canary Build (Version 1.9.17.0). In the Installer is the Version 1.9.10.0. I tried it in Virtualbox and it worked. Only the translation is still a bit tricky.

**Comment by Jank8** [comment]
> You need the Canary Build (Version 1.9.17.0). I tried it in Virtualbox and it worked. Only the translation is still a bit tricky.

My version had 1.9.10, replaced with installer/portable 1.9.15, works fine.

**Comment by OliverBorgmann** [comment]
I had a problem with this version because the context menu from the taskbar did not display all words.There is a thread with more information here. Could be a Language Problem because i am using a German Windows.

**Comment by MishaProductions** [comment]
assuming that this got fixed
