### ISSUE TITLE
[FEATURE REQUEST] Allow in the Rectify 11 Control center to disable MFE on startup

### ISSUE THREAD

**Issue by EDM115** [Rectify11/Installer#563]
### Description

Rectify 11 now starts MicaForEveryone automatically along with the ExplorerFrame fix, which is good for most users and give them a clean experience out-of-the-box, but as an advanced user I prefer to keep control over things.  
  
So first MFE have been installed on `%systemroot%/MicaForEveryone`, despite me unchecking the auto-install option upon installing R11 multiple times, since I already installed it myself (`D:\EDM115\Programmes\Mica For Everyone` & `D:\EDM115\Programmes\ExplorerFrame` for the record)  
So when I saw both of them starting automatically I wanted to disable them, and it took me a hot minute to find (already disabled in the task manager/settings, not present in the registry, not registered as services, not in the startup folders, ...)  
For anyone wondering, they're labeled `mfe` and `mfefix` in the Task Scheduler (`taskschd.msc`) and that's where you can disable them  
  
So it would be nice if we could choose (maybe in the install options, but the Control Panel would be better) to enable them or not. Once again, having them as default is okay but we should be able to disable them. Also the fact that it installs despite us unchecking this option in the installer should be considered a bug (installer used : [action run #9372566326](https://github.com/Rectify11/Installer/actions/runs/9372566326/artifacts/1568136710))

### Steps To Reproduce

1. Install/Upgrade Rectify11
2. Restart
3. Notice that MFE starts on startup and there is no option to disable it in `Rectify11.SettingsCPL`

### Rectify11 Version

v3.2.70.1

### Windows Version

Windows 11 23H2 build 22635.3720

### Logs

:)

**Comment by Yoad1704** [comment]
You can disable MFE on startup from the app

**Comment by EDM115** [comment]
@Yoad1704 I believe that the Task Scheduler bypasses this. also it was already disabled in app

**Comment by ooTruffle** [comment]
> @Yoad1704 I believe that the Task Scheduler bypasses this. also it was already disabled in app

Correct Task Scheduler bypasses mfe normal startup task

**Comment by MishaProductions** [comment]
should be fixed, can you please try again?

**Comment by EDM115** [comment]
@MishaProductions I'm with my gf for 3 weeks and far from my computer, so can't try atm 🥹
