### ISSUE TITLE
Color issues with browser/apps

### ISSUE THREAD

**Issue by Jacinto27** [Rectify11/Installer#564]
### Description

Similar to other color issues with the Dark mode for Word, Excel, Powerpoint, and some apps, my browser (Firefox) defaults/forces pages to dark mode, some pages are not compatible with that and end up being a black background with black unreadable text. 

Windows11
Dark mode with Mica

I've seen some other open issues regarding Office apps facing similar issues, which means they are probably caused by the same bug.

### Steps To Reproduce

Dark mode with Mica
(Mica for Everyone) Default settings for explorer
Enter a webpage with such issue
Example: https://lifehacker.com/tech/seven-ways-you-can-make-the-windows-11-taskbar-even-more-useful

### Rectify11 Version

Version 3.2.7

### Windows Version

Windows11 Home 23H2

### Logs

NA

**Comment by Jacinto27** [comment]
Oh, also in some downloaders: 
![image](https://github.com/Rectify11/Installer/assets/90574028/d4c0cffd-ae43-45c9-ac3c-bfb256966e45)

**Comment by Yoad1704** [comment]
For your office, add every process as a rule to MicaForEveryone and put everything on default to disable all effects. As for the install, unless you always want to put another rule for each time you use another installer - there is no fix.

**Comment by Jacinto27** [comment]
So this is a Mica for Everyone issue? Or is it a color issue with rectify and how it interacts with Mica for Everyone ?

**Comment by ooTruffle** [comment]
Hey there

For firefox go into your settings -> manage colours and disable "use system colours" firefox unlike chromeium has this toggle ^^

**Comment by Jacinto27** [comment]
Thank you so much, do you know what's the root cause of the issue? People seem to solve it by adding exceptions to Mica for Everyone but i've found no issues in the Mica For Everyone repo

**Comment by ooTruffle** [comment]
> Thank you so much, do you know what's the root cause of the issue? People seem to solve it by adding exceptions to Mica for Everyone but i've found no issues in the Mica For Everyone repo

The colour issues in firefox is due to the Custom Theme R11 uses, some apps hard code colours and that causes issues

**Comment by tiagorangel2011** [comment]
bump

**Comment by ooTruffle** [comment]
> bump, happening with some websites on Firefox & the font selector on figma

Firefox
Untick this option
![image](https://github.com/Rectify11/Installer/assets/28374251/fcc59bbb-ff2a-44fe-bde5-72cb396d52c3)
Figma
Its just eletron app soooo just use the website

**Comment by tiagorangel2011** [comment]
yea but the problem is with other apps where the same happens...

Truffle ***@***.***> escreveu (sábado, 15/06/2024 à(s) 10:03):

**Comment by Jacinto27** [comment]
For the browser I did what @ooTruffle suggested and it worked fine, I don't use other browsers so I wont ask, for the other apps I simply followed the other closed issues and they seemed to work. I don't know if the developers are going to include these workarounds in future releases, but since the issue is solved I'll close this here 🤗

**Comment by ooTruffle** [comment]
Apps that use hardcoded colours cant be fixed by the r11 team sadly

**Comment by Jacinto27** [comment]
Yeah I figured, but some of these issues seem to be exclusively with the white and black background colors that are inverted somewhere (Mica or Dark theme) and apps call to that color instead of a hardcoded white or black? Maybe finding a way to exclude that color might avoid the issue altogether

**Comment by ooTruffle** [comment]
> Yeah I figured, but some of these issues seem to be exclusively with the white and black background colors that are inverted somewhere (Mica or Dark theme) and apps call to that color instead of a hardcoded white or black? Maybe finding a way to exclude those colors from bring inverted might avoid the issue altogether

What happens is they hardcode white for the background, Then take the font colour from the theme

Why partial dark was created

**Comment by Jacinto27** [comment]
Oh I get it. Yeah there's no way to work around that
