### ISSUE TITLE
tranclucient effect on unfocoused windows

### ISSUE THREAD

**Issue by SJK9906** [Rectify11/Installer#572]
### Description

can add support for trasparency effect on multiple windows
1 only i windows can be traslucient

### Steps To Reproduce

1. install
2. open 2 or more windows with mica / tabloed effect /acrylica effect
3. 3. you will see that 1 windows only can have translucient effects on any times

### Rectify11 Version

rectify 11 v3.2.70.1

### Windows Version

windows 11 23H2 22635.3790 (insider)

### Logs

![image](https://github.com/Rectify11/Installer/assets/129201282/95c8ba44-9801-4335-89e0-cd26a529519c)
![image](https://github.com/Rectify11/Installer/assets/129201282/d86b5daa-c901-455e-87f6-3ad4e8f371ac)
Used theme: [Giacomo Baiyu Cosner.deskthemepack.zip](https://github.com/user-attachments/files/15935954/Giacomo.Baiyu.Cosner.deskthemepack.zip)

**Comment by Talon125** [comment]
This is a limitation of Windows 11 and how it handles Mica. You can maybe look at MicaForEveryone's GitHub repo for help.  
https://github.com/MicaForEveryone/MicaForEveryone

Otherwise, try out DWMBlurGlass instead of MicaForEveryone:  
https://github.com/Maplespe/DWMBlurGlass
