### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by Andrew-Sor** [Rectify11/Installer#577]
### Description

I can’t uninstall Rectify11. It says that the uninstaller could not be found.
![image](https://github.com/Rectify11/Installer/assets/133566800/0eb5b7b4-e7e5-41b6-b9cb-bd4f8a616aa1)
How to fix it?

### Steps To Reproduce

1. Install Rectify11
2. Try to uninstall Rectify11

### Rectify11 Version

3.2.70.1

### Windows Version

Windows 11 22H2 22621.3296

### Logs

![image](https://github.com/Rectify11/Installer/assets/133566800/5629c419-78f5-4963-acfd-6722c3d49dc8)

**Comment by MishaProductions** [comment]
You should be able to uninstall by downloading the installer

**Comment by Andrew-Sor** [comment]
Yes, that's right. I completely forgot that you can uninstall Rectify11 in the installer. 

By the way, I decided to uninstall Rectify11 because the background in the Windows media player turned a very unpleasant color and it seemed to me that the sound also changed (although this is strange), and it also reset my configuration file MicaForEveryone

Well, thank you.
