### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by ross-watson** [Rectify11/Installer#578]
### Description

Can't uninstall using bundled uninstaller, gives error

### Steps To Reproduce

Used bundled uninstaller

### Rectify11 Version

3.1.0

### Windows Version

Windows 11 23H2 22631.3737

### Logs

═════════════════════════════
START: 07/07/2024 17:13:37
Rectify11 Version: 3.1.0.0
═════════════════════════════
Uninstalling themes
───────────────────
Wrote SecureUXHelper.exe
Wrote ThemeDll.dll
Themes.Uninstall() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.Uninstall()

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

**Comment by MishaProductions** [comment]
Please download the latest Rectify11 build at https://rectify11.net and use that to uninstall.
