### ISSUE TITLE
Is this supposed to be like this?

### ISSUE THREAD

**Issue by kameno22** [Rectify11/Installer#579]
### Description

The control panel icon is not changed to the new one but instead its a default explorer icon which is kind of weird cuz i remember it being the new icon not this one 

![image](https://github.com/Rectify11/Installer/assets/98833613/81a3985b-06f3-4236-8df9-36cb13dcc50f)

Tho right clicking shows the new icon
![image](https://github.com/Rectify11/Installer/assets/98833613/5a51893d-c857-4483-956e-6ec2315a38aa)
In properties window as well
![image](https://github.com/Rectify11/Installer/assets/98833613/1b871fd2-f63a-4170-9c15-166ea0f78ba7)

### Steps To Reproduce

Open control panel

### Rectify11 Version

v3.1 latest from action tabs

### Windows Version

Windows 11 23H2

### Logs

NULL

**Comment by ooTruffle** [comment]
Use winaero tweaker to clear your icon cache

**Comment by kameno22** [comment]
> Use winaero tweaker to clear your icon cache

nope still the same
