### ISSUE TITLE
Tofu (□) in file explorer

### ISSUE THREAD

**Issue by TK50P** [Rectify11/Installer#583]
### Description

Tofu (□) characters consistently appear in File Explorer across various views, including "This PC" and other directories.
It looks like some font or icon is missing and seems details view or icon view.
![Screenshot 2024-07-20 210142](https://github.com/user-attachments/assets/e64d39c9-d406-4bbc-be17-a462c7e93618)
![Screenshot 2024-07-20 205856](https://github.com/user-attachments/assets/58d8e4d4-3acd-4b80-b65e-145d1e1b7ad4)

### Steps To Reproduce

- Install Rectify11.
- Open the file explorer.
- Observe tofu (□) characters in the interface.

### Rectify11 Version

3.2.70.1

### Windows Version

Windows 11 24H2 Enterprise LTSC (26100.1000)

### Logs

None.

**Comment by MishaProductions** [comment]
See #586
