### ISSUE TITLE
font rendering problem in android studio with theme - dark theme with mica

### ISSUE THREAD

**Issue by suray-marag-pandit** [Rectify11/Installer#584]
### Description

font doesn't render well good .

### Steps To Reproduce

installer works fine but android studio looks ugly. work with rectify11 dark theme.
just installed the studio.

### Rectify11 Version

3.2.70.1

### Windows Version

Window 11 23H2 22631.3880

### Logs

![Screenshot 2024-07-21 063842](https://github.com/user-attachments/assets/bb72cd0f-c8ff-4ffe-9bf8-de2a53a3e35a)
![Screenshot 2024-07-21 063849](https://github.com/user-attachments/assets/41c47c82-94f8-4878-ae91-7bb339cf59d5)

**Comment by MishaProductions** [comment]
Exclude it from micaforeveryone.
