### ISSUE TITLE
Installer does not install all fonts properly

### ISSUE THREAD

**Issue by andreaxhearts** [Rectify11/Installer#586]
### Description

As noticed on the [Discord](https://discord.com/channels/1077324213142175744/1166858077975351376/1255839453185052722), these four fonts are not getting installed properly by Rectify11:
- Segoe UI Variable
- Segoe Fluent Icons
- Marlett
- Back Button Icons

Particularly in the case of #580 and #583, The **_Back Button Icons_** font missing results in file explorer and media flyout missing symbols.
Affects Windows 10 and Windows 11.

### Steps To Reproduce

Run and complete the installer for Rectify11. (default installer choices)
Open File Explorer window or control media playback to see missing glyphs.

### Rectify11 Version

3.2.70.1

### Windows Version

Windows 10 22H2 19045.4651

### Logs

<a href="https://discord.com/channels/1077324213142175744/1166858077975351376/1255839453185052722">
<img src="https://github.com/user-attachments/assets/7a256b53-d961-47ab-82d9-11e8528f16ca" width="400" alt="discord-faqs-06-27-2024">
</a>

fonts: [[1]](https://cdn.discordapp.com/attachments/1166858077975351376/1255839452001992755/SegUIVar.ttf?ex=66a186e1&is=66a03561&hm=1ac35404aca598b4664c4234869b9ae31a2e8a68842c16c6dffdf196c8a4e8d6&) [[2]](https://cdn.discordapp.com/attachments/1166858077975351376/1255839452325085257/SegoeIcons.ttf?ex=66a186e1&is=66a03561&hm=c2d7938a9c09404b7ae5da3b0db6e2901026b3470cda53454708326c64094465&) [[3]](https://cdn.discordapp.com/attachments/1166858077975351376/1255839452622884965/marlett.ttf?ex=66a186e1&is=66a03561&hm=eea00a4ef54effcced1f802d21c95b5c7dc6660f5ed3c8cded888f3bcc29c029&) [[4]](https://cdn.discordapp.com/attachments/1166858077975351376/1255839452895641600/BackIcons.ttf?ex=66a186e1&is=66a03561&hm=e2815c957f54a67d4ebb27f37c9504f880975dc231c1aabe72ecc69e7b85ec6a&)

![github-issue-tofu-583](https://github.com/user-attachments/assets/8752094f-ed0d-4d6f-9903-7386269c8553)
![github-issue-media-580](https://github.com/user-attachments/assets/7c6d9332-73f9-44ab-b925-6ec9673f2819)

**Comment by Niklas20114552** [comment]
For those who are now looking for the Discord invite because the direct download links have expired:
https://discord.gg/gsgu9GCtsk

**Comment by MishaProductions** [comment]
Fixed in latest commit
