### ISSUE TITLE
Mica doesn't work

### ISSUE THREAD

**Issue by Andrew-Sor** [Rectify11/Installer#587]
### Description

After turning on, rebooting or logging out of the system, mica stops working. It starts working again after receiving the User Account Control window when running any application as an administrator. (You don't have to accept it)

### Steps To Reproduce

1. Restart PC
2. See the absence of mica
3. Run any program as administrator
4. See that mica has appeared

https://github.com/user-attachments/assets/61ec1ce8-7f45-40d4-8c7d-da66e40ba92f

### Rectify11 Version

3.2.70.1

### Windows Version

Windows 11 24H2 26100.863

### Logs

None

**Comment by Mujtaba24** [comment]
Yea it happens to me too where it doesn't let you enable mica

**Comment by Andrew-Sor** [comment]
> Yea it happens to me too where it doesn't let you enable mica

Do you know how to fix it?...

**Comment by Niklas20114552** [comment]
For me the control center says mica and mica alt is enabled. When i disable mica alt it just gets turned on again. But mica doesn't work.

**Comment by Andrew-Sor** [comment]
> For me the control center says mica and mica alt is enabled. When i disable mica alt it just gets turned on again. But mica doesn't work.

![image](https://github.com/user-attachments/assets/78833cfc-df51-4e1b-befa-15a66b97a100)
Strange... I don't see Mica Alt...

**Comment by Andrew-Sor** [comment]
By the way, when changing wallpaper, in order for the mica to be from the new wallpaper, you need to do the same manipulation

**Comment by Niklas20114552** [comment]
For me the control center says mica and mica alt is enabled. When i disable mica alt it just gets turned on again. But mica doesn't work.

> > For me the control center says mica and mica alt is enabled. When i disable mica alt it just gets turned on again. But mica doesn't work.
> 
> ![image](https://private-user-images.githubusercontent.com/133566800/358537511-78833cfc-df51-4e1b-befa-15a66b97a100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTQxMjIsIm5iZiI6MTcyMzgxMzgyMiwicGF0aCI6Ii8xMzM1NjY4MDAvMzU4NTM3NTExLTc4ODMzY2ZjLWRmNTEtNGUxYi1iZWZhLTE1YTY2Yjk3YTEwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxMzEwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWVjNWEzMGNmNzI4NTZlYjI1ZGNkYTU2MmJiNmU1OWRjMDlkNDEzNDU1Zjg0ZjZmYmM2OGRhNjFjYjFlMjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x5C6dj_11tVMjlBHN7ozgoRBxrybKhZXracNwQ4LWW4) Strange... I don't see Mica Alt...

Maybe its Tabbed Mica in English

**Comment by Andrew-Sor** [comment]
> Maybe its Tabbed Mica in English

There are no other languages ​​there.

**Comment by Andrew-Sor** [comment]
I found that this only happens when the desktop background is set to a slideshow. Mica works fine if the background is a single image.

**Comment by Niklas20114552** [comment]
I managed to find a workaround.

Copy the file content from `C:\Windows\MicaForEveryone\CONF\DarkRectified.conf` to `C:\Users\Niklas\AppData\Local\Mica For Everyone\MicaForEveryone.conf`  
MicaForEveryone should reload the config automatically, if not try logging out and in again.

**Comment by Andrew-Sor** [comment]
> I managed to find a workaround.
> 
> Copy the file content from `C:\Windows\MicaForEveryone\CONF\DarkRectified.conf` to `C:\Users\Niklas\AppData\Local\Mica For Everyone\MicaForEveryone.conf` MicaForEveryone should reload the config automatically, if not try logging out and in again.

Thanks! I'll try it.
