### ISSUE TITLE
I meet a problem during installing

### ISSUE THREAD

**Issue by Alankeji** [Rectify11/Installer#595]
> This is log

═════════════════════════════
START: 2024/8/6 20:39:06
Rectify11 Version: 3.2.70.1
═════════════════════════════
Preparing Installation
──────────────────────
Wrote RectifyStart.exe
Wrote 7za.exe
Wrote files.7z
Wrote extras.7z
Wrote ResourceHacker.exe
WriteFiles() succeeded.
Extracting vcredist.exe from extras.7z
Extracting core31.exe from extras.7z
Executing vcredist.exe with arguments /install /quiet /norestart
vcredist.exe exited with error code 1638
Executing core31.exe with arguments /install /quiet /norestart
core31.exe exited with error code 1638
InstallRuntimes() succeeded.
══════════════════════════════════════════════
Wrote files.7z
Extracted files.7z
Wrote ThemeDLL.dll
Installr11cpl() succeeded.
Installing Themes
─────────────────
Wrote RectifyStart.exe
Wrote themes.7z
WriteFiles() succeeded.
Extracted files.7z
Deleted old wallpapers.
Copied wallpapers to C:\WINDOWS\web\wallpaper\Rectified
Copied Themetool.
Deleted old wallpapers.
InstallThemes() failed as SecureUXHelper is missing (most likely deleted by antivirus. Please exclude the C:\Windows\Rectify11 folder from your anti-virus.
Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

**Comment by MishaProductions** [comment]
> Please exclude the C:\Windows\Rectify11 folder from your anti-virus.
