### ISSUE TITLE
Installer Gray

### ISSUE THREAD

**Issue by MashibaKoto0370** [Rectify11/Installer#596]
### Description

All Text and Options in Installer Are Gray. Cant see any Options

### Steps To Reproduce

installer

### Rectify11 Version

3.2.70.1

### Windows Version

Windows 11 LTSC 24h2

### Logs

![Untitled](https://github.com/user-attachments/assets/05316ec7-42d5-4714-9dca-456081f5e600)

**Comment by MashibaKoto0370** [comment]
for some reason the screenshot looks normal..But on my screen is completly gray. Sorry if that was confusing

**Comment by MishaProductions** [comment]
Try disabling HDR.
