### ISSUE TITLE
可以把rectify11安装的文件给我吗？需要帮助

### ISSUE THREAD

**Issue by WRMYX** [Rectify11/Installer#601]
我需要做一个东西，需要用到Rectify11的安装文件，就是那个替换和添加的文件，可以把他们打包给我吗？谢谢，但是有一个要求就是安装到哪里的文件就要创建哪里的文件夹，比如像windows/system32安装了一个叫sys.sys的文件，就要把windows和system32的文件夹创建好！就像这样了，麻烦你们能帮忙一下！

**Comment by alovelydoge** [comment]
制作东西时请尊重GPL许可证！
另外，请去官网上下载安装包自己搞！

**Comment by WRMYX** [comment]
> ** 制作东西时请尊重GPL许可证！**
> 
> 请去官网上下载安装包自己搞！不要在这里做伸手党！

我也想啊！但是真的不好弄，我也没有太好的方法可以提取出来，所以我才来的。你们的开源文件并没有那些文件！

**Comment by WRMYX** [comment]
> ** 制作东西时请尊重GPL许可证！**
> 
> 请去官网上下载安装包自己搞！不要在这里做伸手党！

I want to too!But it's really difficult to do, and I don't have a good way to extract it. That's why I came here.Your open source files do not have those files!

**Comment by WRMYX** [comment]
> ** 制作东西时请尊重GPL许可证！**
> 
> 请去官网上下载安装包自己搞！不要在这里做伸手党！

I was really going crazy trying to extract them one by one😢

**Comment by MishaProductions** [comment]
Please create a new issue in English.

**Comment by MishaProductions** [comment]
Everything that you need is located in https://github.com/Rectify11/Installer/tree/legacy-installer/Resources.
