### ISSUE TITLE
[BUG] Can't install updates from commits semver

### ISSUE THREAD

**Issue by EDM115** [Rectify11/Installer#603]
### Description

Apparently, to know if the ran installer can Upgrade or just Edit/Uninstall, it bases itself on the semver (ex `3.2.70.1`).  
But if I want to try the latest installer (here `3.2.70.1+c57eb635250343e507af6c95c853d194223fc44b`), I can't because I have a version with the same semver installed, even if the commit is different (taking a rough guess I should have `3.2.70.1+cb23e433b83c203045de9cddcd2efc8912eafec7` since my Rectify11TrayTool.exe is still 1.5.0)  
We should be able to upgrade even from commits semver, because for example I can't check if an issue I opened have actually been fixed (https://github.com/Rectify11/Installer/issues/563#issuecomment-2194363545).  
Either you should make a way to make this possible, or bump the last digit at every commit

### Steps To Reproduce

1. Install from https://github.com/Rectify11/Installer/actions/runs/9486872849/artifacts/1594856872
2. Try to upgrade from https://github.com/Rectify11/Installer/actions/runs/10361044260/artifacts/1804282960
3. Despite the 2nd being more recent, the upgrade won't be allowed. The only way currently is to fully uninstall Rectify11 and reinstall it, which isn't user-friendly

### Rectify11 Version

v3.2.70.1

### Windows Version

Windows 11 23H2 build 22635.4076

### Logs

![same semver, different commit](https://github.com/user-attachments/assets/d546bbfe-1659-4cfd-b6cf-b55b860c74c6)

**Comment by ooTruffle** [comment]
you just click modify and that should update the files iirc

**Comment by EDM115** [comment]
@ooTruffle nope, because the same boxes are ticked so it considers nothing has changed and I can't go any further

**Comment by MishaProductions** [comment]
intentional
