### ISSUE TITLE
control panel has white parts

### ISSUE THREAD

**Issue by MooseZM** [Rectify11/Installer#604]
### Description

as the tile says, the side bar is white and when you first open it the top bar is also white. Oddly enough it worked fine for a few days after installing 3.2 but it stopped working randomly 
![image](https://github.com/user-attachments/assets/047bd0fc-397f-4af0-93f6-059d0c4d1eb7)
![image](https://github.com/user-attachments/assets/d5d66bd7-cda6-4c89-b606-e9799355f6b9)

### Steps To Reproduce

open control panel

### Rectify11 Version

3.2

### Windows Version

win 11 23H2

### Logs

none

**Comment by mina354** [comment]
Yeah, happens to me too

**Comment by MishaProductions** [comment]
Please read the FAQ, patch shell32 icon in the installer.

**Comment by Plasman888** [comment]
How do you path shell 32 icon

> Please read the FAQ, patch shell32 icon in the installer.

**Comment by Plasman888** [comment]
i cant seem to find shell 32
