### ISSUE TITLE
Internet connection issues/broken post rectify11 

### ISSUE THREAD

**Issue by nthings-cmd** [Rectify11/Installer#605]
### Description

Following my installation of Rectify11 v3.2, my connection to the internet just stopped working. I’ve tried a network reset, checking proxy settings, vpns, and firewall rules and NOTHING seems to change it. Attempts to uninstall Rectify tell me that the uninstall.exe file simply doesn’t exist, and after checking, this is proven true. Attempts to connect through Firefox, Librewolf and Chrome have failed, and a network disgnostic states that microsoft.com’s server IS up, yet a connection failed. I have personal files dating back 3 years on this device (thank god they aren’t corrupted) and need a solution, or at this point i might just install Linux.

### Steps To Reproduce

Install rectify11 on a lenovo IdeaPad 17IIL05 running Windows 11 Home 23H2 with the os build 22631.3593 and the Windows Feature Experience Pack 1000.22700.1003.0 

### Rectify11 Version

3.2

### Windows Version

Windows 11 Home 23H2

### Logs

![IMG_7347](https://github.com/user-attachments/assets/ca88604e-3e38-4932-9930-cee404b767c9)
![IMG_7348](https://github.com/user-attachments/assets/53c93158-d7de-428b-8081-f28da4703338)

**Comment by MishaProductions** [comment]
This is probably a random windows issue as Rectify11 does not mess with the network stack. You can try running the installer and uninstalling r11 through there, or using the restore point.

**Comment by nthings-cmd** [comment]
Honestly weirdest thing here is that system restore does not work at all.
