### ISSUE TITLE
[FYI] Windows will remove at some point the Control Panel

### ISSUE THREAD

**Issue by EDM115** [Rectify11/Installer#606]
Apparently Windows have updated their [support page](https://support.microsoft.com/en-us/windows/system-configuration-tools-in-windows-f8a49657-b038-43b8-82d3-28bea0c5666b) : the Control Panel section now reads  
> The Control Panel is in the process of being deprecated in favor of the Settings app  
  
although they didn't gave any clear date, it may sparkle some questions around "should Rectify11 settings really be implemented in the Control Panel ?" (`C:\Windows\System32\control.exe /name Rectify11.SettingsCPL`)  
  
further reading :
- https://www.neowin.net/news/microsoft-finally-officially-confirms-its-killing-windows-control-panel-sometime-soon/
- https://www.bleepingcomputer.com/news/microsoft/microsoft-confirms-august-updates-break-linux-boot-in-dual-boot-systems/

**Comment by MishaProductions** [comment]
Microsoft has been saying that for the last 10 years, and I highly doubt that they will remove the underlying code for control panel (the rectify11 control panel only uses the CLayoutFolder class). Currently, there isn't any public api for integrating things into the settings app, so we will continue using the control panel applet for now.

**Comment by EDM115** [comment]
perfectly understandable, I was just pointing this out  
also it's perfect because we can go straight to the rectify settings from the Run dialog
