### ISSUE TITLE
So i have been using rectify 11 for few days 

### ISSUE THREAD

**Issue by coderzawad** [Rectify11/Installer#607]
### Description

I am having some inconsistencies in rectify11
To be honest it pisses me off and also i am "new" to rectify11

Issue screenshot :-

![image](https://github.com/user-attachments/assets/e1d1a885-5082-4e96-8d47-4e9eb5e692d0)

That gray toolbar pisses me off every time i open the file explorer
and also is it natural?

![image](https://github.com/user-attachments/assets/4a97dea1-9582-431b-9140-20828f7676e7)

Does this looks like it naturally?

Version :- Windows 11
Rectify11 version :- v3.2

### Steps To Reproduce

I am actually not pretty sure about this

### Rectify11 Version

Rectify v3.2

### Windows Version

Windows 11

### Logs

![image](https://github.com/user-attachments/assets/ae125662-6846-4dee-b133-a6fec4767cd2)
![image](https://github.com/user-attachments/assets/1859bbcb-f54c-4175-a452-c98c85288ea7)

**Comment by MuscularPuky** [comment]
You saying "New" "Cut" "Paste" "Sort" "View" Bar? Then you sholud use this: https://github.com/Maplespe/ExplorerBlurMica

**Comment by coderzawad** [comment]
Yeah

**Comment by coderzawad** [comment]
I'll try

**Comment by MuscularPuky** [comment]
> I'll try

and you don't need to uninstall Rectify11 they work together well

**Comment by coderzawad** [comment]
![image](https://github.com/user-attachments/assets/f91e1b8e-b56e-4a0f-a39a-47e8b90dd634)
And sorry for disturbing but this looks new after installing that software it looks like this

**Comment by coderzawad** [comment]
> > I'll try
> 
> and you don't need to uninstall Rectify11 they work together well

It wasn't like this before

**Comment by MuscularPuky** [comment]
> > > I'll try
> > 
> > 
> > and you don't need to uninstall Rectify11 they work together well
> 
> It wasn't like this before

Unfortunately that's randomly occures in ExplorerBlurMica. so I expand the address bar and type anything until become looks good
![image](https://github.com/user-attachments/assets/c043ca73-fe9b-42e2-89d1-8d4e1bd4372f)

![image](https://github.com/user-attachments/assets/6c05a5a4-bc94-4172-8a23-8aea872c2bb3)

or you can add the class "CabinetWClass" in MicaForEveryone to exclude mica effect of control panel. Try various options in MFE, like "Extend Frame into Client Area", "Blur Behind", etc.

**Comment by coderzawad** [comment]
> > > > I'll try
> > > 
> > > 
> > > and you don't need to uninstall Rectify11 they work together well
> > 
> > 
> > It wasn't like this before
> 
> Unfortunately that's randomly occures in ExplorerBlurMica. so I expand the address bar and type anything until become looks good ![image](https://private-user-images.githubusercontent.com/93962018/361609187-c043ca73-fe9b-42e2-89d1-8d4e1bd4372f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjc2NzEsIm5iZiI6MTcyNDcyNzM3MSwicGF0aCI6Ii85Mzk2MjAxOC8zNjE2MDkxODctYzA0M2NhNzMtZmU5Yi00MmUyLTg5ZDEtOGQ0ZTFiZDQzNzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZjM1ZjVjODg2NmM3NjFmODBmMzVmOGQ5NDFmZDg5M2E1MjhjZTAxYjU5NDJmMWVkMGUyZDBlOTNkMTlkMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gSTPXA7jg8EK1F3Q4kRLsJzC0E5zjiuS6UYnPUL7bHY)
> 
> ![image](https://private-user-images.githubusercontent.com/93962018/361609222-6c05a5a4-bc94-4172-8a23-8aea872c2bb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjc2NzEsIm5iZiI6MTcyNDcyNzM3MSwicGF0aCI6Ii85Mzk2MjAxOC8zNjE2MDkyMjItNmMwNWE1YTQtYmM5NC00MTcyLThhMjMtOGFlYTg3MmMyYmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3OTMwZDhhNTc4NWUzOTJlMGZlNmJjODk2YTViNGE5MDAzZWE0NjI1NzI2NDgyOTY2ZjFkOTUzOGRkODYxM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2QxTbe0fjEtoXCF7PCFvMmwj_8Us0Ty32apXqsyol40)
> 
> or you can add the class "CabinetWClass" in MicaForEveryone to exclude mica effect of control panel. Try various options in MFE, like "Extend Frame into Client Area", "Blur Behind", etc.
> 
> (+edit: Note the DirectUIHWND and NativeHWNDHost class too. They're used in various explorer elements, like File Transfer dialog, Shortcut Create Wizard, etc)

But mica doesn't even work on my control panel

**Comment by MuscularPuky** [comment]
> > > > > > I'll try
> > > > > 
> > > > > 
> > > > > and you don't need to uninstall Rectify11 they work together well
> > > > 
> > > > 
> > > > It wasn't like this before
> > > 
> > > 
> > > Unfortunately that's randomly occures in ExplorerBlurMica. so I expand the address bar and type anything until become looks good ![image](https://private-user-images.githubusercontent.com/93962018/361609187-c043ca73-fe9b-42e2-89d1-8d4e1bd4372f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjc2NzEsIm5iZiI6MTcyNDcyNzM3MSwicGF0aCI6Ii85Mzk2MjAxOC8zNjE2MDkxODctYzA0M2NhNzMtZmU5Yi00MmUyLTg5ZDEtOGQ0ZTFiZDQzNzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZjM1ZjVjODg2NmM3NjFmODBmMzVmOGQ5NDFmZDg5M2E1MjhjZTAxYjU5NDJmMWVkMGUyZDBlOTNkMTlkMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gSTPXA7jg8EK1F3Q4kRLsJzC0E5zjiuS6UYnPUL7bHY)
> > > ![image](https://private-user-images.githubusercontent.com/93962018/361609222-6c05a5a4-bc94-4172-8a23-8aea872c2bb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjc2NzEsIm5iZiI6MTcyNDcyNzM3MSwicGF0aCI6Ii85Mzk2MjAxOC8zNjE2MDkyMjItNmMwNWE1YTQtYmM5NC00MTcyLThhMjMtOGFlYTg3MmMyYmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3OTMwZDhhNTc4NWUzOTJlMGZlNmJjODk2YTViNGE5MDAzZWE0NjI1NzI2NDgyOTY2ZjFkOTUzOGRkODYxM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2QxTbe0fjEtoXCF7PCFvMmwj_8Us0Ty32apXqsyol40)
> > > or you can add the class "CabinetWClass" in MicaForEveryone to exclude mica effect of control panel. Try various options in MFE, like "Extend Frame into Client Area", "Blur Behind", etc.
> > > (+edit: Note the DirectUIHWND and NativeHWNDHost class too. They're used in various explorer elements, like File Transfer dialog, Shortcut Create Wizard, etc)
> > 
> > 
> > But mica doesn't even work on my control panel
> 
> strange
> 
> you extend into Explorer client area in MicaForEveryone?

Yes I did I just cheked
