### ISSUE TITLE
I may need all the installation files for Rectify11! Could you please check this out? Thank you.

### ISSUE THREAD

**Issue by WRMYX** [Rectify11/Installer#619]
Could you provide me with all the installation files for Rectify11? I want to create a non-commercial small software. Your released installation package only contains some basic files, but not files like .dll. It's quite troublesome that they are not easy to extract after installation. Could you please help with this?

**Comment by MishaProductions** [comment]
The icons are located at https://github.com/Rectify11/Installer/tree/legacy-installer/Resources/Files which can be imported to a dll file.

**Comment by WRMYX** [comment]
> 图标位于 https://github.com/Rectify11/Installer/tree/legacy-installer/Resources/Files 可以导入到 dll 文件中。图标位于https://github.com/Rectify11/Installer/tree/legacy-installer/Resources/Files可以导入到 dll 文件中。

Should i directly remove the .res suffix?
