### ISSUE TITLE
The Gadgets are very buggy and old

### ISSUE THREAD

**Issue by issacs-tech** [Rectify11/Installer#622]
### Description

I replaced by 8gadgetpack tools which replaced it on the 3.2 install perfect !

### Steps To Reproduce

Replaced 

### Rectify11 Version

3.2

### Windows Version

23h2

### Logs

No log

**Comment by MishaProductions** [comment]
Known issue, will not be fixed.

**Comment by issacs-tech** [comment]
Thanks can't wait for Ver 4 very exited!
