### ISSUE TITLE
Does not seem to work fine on Tiny 11

### ISSUE THREAD

**Issue by AntoineLaLune** [Rectify11/Installer#631]
### Description

I could never get the dark mode to work, and my ESET antivirus seemed to stop working.

- I deactivated my antivirus before installation.
- I tried an installation again after using a restore point, with no result.

_I saw that there would be a version 4 of the Rectify11 installer, so I'll wait for that to come out, that way I'll try to see if I run into the same problem with dark mode, or even if I could select the minimum number of options to keep my ESET antivirus intact since version 4 of the Rectify11 installer should offer more settings._

### Steps To Reproduce

Have Tiny 11, but that's just a guess because I didn't really insist on solving the problem.

### Rectify11 Version

Rectify11 v3.2

### Windows Version

Windows 11 23H2 22631.4169 (Tiny 11) 

### Logs

None

**Comment by AntoineLaLune** [comment]
News:

I installed the dark mode on an unmodified Windows 11 by installing secureuxtheme and applying the Rectify11 .theme extracted from the source code, and I must say that it works fine, except for the control panel which was broken, something normal, the theme being only compatible with the Rectify11 installation.

All this to say that the problem comes from secureuxtheme, so I'll probably go and open an issue with them.

On the other hand, I still don't know why my anti-virus breaks when I install Rectify11.

**Comment by MishaProductions** [comment]
eset antivirus should work if you don't install msi.dll icons in the installer.
