### ISSUE TITLE
broken context menus on taskbar Windows 11 24h2

### ISSUE THREAD

**Issue by BezCommentariev** [Rectify11/Installer#634]
### Description

after installing rectify11, context menus on the taskbar break. I install only the mod for the context menu (new extended context menu from rectify11 with all menu items). Version rectify 11 3.1 and 3.2 break the taskbar menu in the same way. Is it possible to set an alternative context menu for Explorer, but not for the taskbar (so that the native context menu of Windows 11 is used on the taskbar)? Or, is it possible to return the native context menu only to the taskbar?For me, this would solve the problem.

![Снимок экрана 2024-10-03 100316](https://github.com/user-attachments/assets/27778c6f-71c7-4b12-9c47-0ea9a25d67b8)
![Снимок экрана 2024-10-03 100355](https://github.com/user-attachments/assets/d609c3f0-6595-4176-a946-2559e2dbe32b)

### Steps To Reproduce

after installing alternative context menus (extended with all menu items), you need to right-click on the taskbar to open the taskbar context menu. It looks broken, and some menu items are not labeled. The problem only appears on windows 24h2

### Rectify11 Version

3.2

### Windows Version

Windows 11 24h2 26100.1742

### Logs

![Снимок экрана 2024-10-03 100316](https://github.com/user-attachments/assets/74029525-d683-4727-8fef-92515180cf6a)
![Снимок экрана 2024-10-03 100355](https://github.com/user-attachments/assets/28a70a91-a019-4c10-8ddd-c725e69e7166)

**Comment by AquaSimulacra** [comment]
Same issue here

**Comment by BezCommentariev** [comment]
The problem was completely solved in another way. Remove rectify11, or do not install it at all! If we only need the menu, then rectify 11 is not needed. Download the latest version of the Nilesoft Shell installer from nilesoft.org. And download the Canary version archive. Install nilesoft (precisely install, not the portable version). After that, change the Files in the Program Files in the "Nilesoft Shell" folder to the files from the Canary version archive. This way you can use it, but I deleted the unnecessary menu items in the taskbar (maybe someone needs them)). If you are too lazy to download everything from the official site, I will attach the installer archives, and the archive with the Canary version, with the modified taskbar menu.

[Nilesoft Shell MODYFY.zip](https://github.com/user-attachments/files/17255764/Nilesoft.Shell.MODYFY.zip)
[setup 1.9.15.zip](https://github.com/user-attachments/files/17255765/setup.1.9.15.zip)
[shell-canary ORIGINAL.zip](https://github.com/user-attachments/files/17255766/shell-canary.ORIGINAL.zip)

**Comment by MishaProductions** [comment]
should be fixed by 60ba41941bee153d658b7a087783177a50fa213b
