### ISSUE TITLE
使用翻译软件截屏翻译时出现黑屏/When using translation software to take screenshots for translation, a black screen appears

### ISSUE THREAD

**Issue by dajuzi2011** [Rectify11/Installer#635]
### Description

使用翻译软件截屏翻译时出现黑屏
When using translation software to take screenshots for translation, a black screen appears
![PixPin_2024-10-03_21-37-49](https://github.com/user-attachments/assets/bd9b0157-6296-4fbe-8c17-989c78c22e78)

### Steps To Reproduce

在“百度翻译”软件中使用截图翻译时软件读取的屏幕为纯黑（如图一），而没有安装Rectify11的系统没用此bug
When using screenshot translation in the "Baidu Translation" software, the screen read by the software is pure black (as shown in Figure 1), and the system without Rectify11 installed does not use this bug
![PixPin_2024-10-03_21-37-49](https://github.com/user-attachments/assets/4c3c4aa2-479c-40a3-abe5-13b2e216403d)
![PixPin_2024-10-03_21-41-16](https://github.com/user-attachments/assets/11c526c9-905c-46b7-9fa8-afe59f0789f2)

### Rectify11 Version

3.2.70.2

### Windows Version

Windows11 23h2

### Logs

![PixPin_2024-10-03_21-41-16](https://github.com/user-attachments/assets/39d36c55-49a3-431a-8fbb-7661e355acd7)
![PixPin_2024-10-03_21-37-49](https://github.com/user-attachments/assets/5664465e-e420-460e-8412-7f293a47e8ee)

**Comment by dajuzi2011** [comment]
英文为机器翻译，请见谅
English is machine translated, please forgive me

**Comment by kameno22** [comment]
1. Go into micaforeveryone
![image](https://github.com/user-attachments/assets/692f5e0b-3f34-4e14-ae39-c61ef3ea2380)
2. Add the add from plus icon and select process rule
![image](https://github.com/user-attachments/assets/fe284538-d3eb-43f1-8cec-6193ac1ca730)
3. Then type the name of application u want to fix the issue for,
![image](https://github.com/user-attachments/assets/45d0bd4b-4ee1-4d8e-992e-fe9821fb338e)
4. Then hit ok 
5. Now under backdrop type change it to none,
![image](https://github.com/user-attachments/assets/6bd9b47b-1f1e-4b95-9520-c20d29036fa9)
6. Restart the application and you are done!
