### ISSUE TITLE
Add a setting to prevent Rectify11 from interfering with websites

### ISSUE THREAD

**Issue by willyblah** [Rectify11/Installer#638]
### Description

Rectify11 will modify some parts of light websites to make them dark - this might produce weird effects. I hope that there can be a setting to turn this off

### Steps To Reproduce

1. Open web browser
2. Go to some light-background website
3. There might be text boxes or other elements that are strangely made black

### Rectify11 Version

3.2.70.2

### Windows Version

Windows 11 24H2

### Logs

None

**Comment by MishaProductions** [comment]
Read the FAQ or use partial dark theme.
