### ISSUE TITLE
context menu is white on dark mode nothing in the task manager

### ISSUE THREAD

**Issue by MahdiSh81** [Rectify11/Installer#642]
### Description

my context menu is white in dark mode while selected nilesoft shell or nilesoft shell all items in root
![Screenshot 2024-10-13 113500](https://github.com/user-attachments/assets/27c204c5-32ba-4eaa-93f2-9e31ea661a6e)
![Screenshot 2024-10-13 113345](https://github.com/user-attachments/assets/50aefb30-eb10-4743-8793-26bf09097fef)
no process show in the task manager either after installing
![image](https://github.com/user-attachments/assets/dc631cda-147f-457b-97a2-90921cdd7f08)

### Steps To Reproduce

i just uninstalled the previous version
restarted
installed the newer version
restarted again

### Rectify11 Version

3.2.70.2

### Windows Version

Windows 11 Pro 23H2 OS build 22631.4317

### Logs

no log

**Comment by MishaProductions** [comment]
not a rectify11 issue
