### ISSUE TITLE
class question, editing msstyle with msstyleEditor

### ISSUE THREAD

**Issue by KrazyDeinos** [Rectify11/Installer#644]
### Description

Anyone know the class for changing the progress bars under This PC? It looks like it should be images under Progress , such as in CHUNK, CHUNKVERT, FILL, FILLVERT. 
But after replacing the pngs and saving the theme, I see no changes.

The same with selected items in light mode , I want to change the themes to the default light blue and black border fo selected items. I though it should be ItemsView::ListView.

I have succefully edited msstyles with msstyleEditor before, but this time I am at a loss, and there is no online info on this sadly.

Any ideas?

### Steps To Reproduce

no

### Rectify11 Version

v1-3

### Windows Version

Win 24h2

### Logs

no logs

**Comment by MishaProductions** [comment]
Not sure, but you can try asking in the discord.
