### ISSUE TITLE
Color issues with R11 Dark Theme and MS Office

### ISSUE THREAD

**Issue by steveji2021** [Rectify11/Installer#652]
![image](https://github.com/user-attachments/assets/3e7e7907-3616-4c05-8146-b938bd0dae6e)
![image](https://github.com/user-attachments/assets/ee7dc3b4-dc79-4901-9243-25fdfd648e08)

The pages are always black in MS Word. I have turned on the "Don't change the color of document pages" option. Normally the pages should be white in both dark and light themes, but it seemed that Rectify11 dark theme broke that option. Even when I changed office theme to "White", the document pages are still black.

Same issue in Excel. In PowerPoint, this doesn't happen.

Big problem for me. Please fix it at your convenience. Thanks

_Originally posted by @steveji2021 in https://github.com/Rectify11/Installer/issues/472#issuecomment-2439990071_

**Comment by NotAsea** [comment]
i recommend switch to partial theme or light theme and office will act normal again, when done work with office switch back to dark theme, that how i'm able to get it work whether you use MS Office, WPS Office, LibreOffice.... rectif11 heavily patch some dll that these office depend in dark theme so the best option for us now is switch theme

**Comment by steveji2021** [comment]
> i recommend switch to partial theme or light theme and office will act normal again, when done work with office switch back to dark theme, that how i'm able to get it work whether you use MS Office, WPS Office, LibreOffice.... rectif11 heavily patch some dll that these office depend in dark theme so the best option for us now is switch theme

will partial dark theme break micaforeveryone effect?

**Comment by NotAsea** [comment]
> > i recommend switch to partial theme or light theme and office will act normal again, when done work with office switch back to dark theme, that how i'm able to get it work whether you use MS Office, WPS Office, LibreOffice.... rectif11 heavily patch some dll that these office depend in dark theme so the best option for us now is switch theme
> 
> will partial dark theme break micaforeveryone effect?

No, it work fine

**Comment by steveji2021** [comment]
ok. thanks
