### ISSUE TITLE
Rectify 11 breaks reWASD

### ISSUE THREAD

**Issue by Vehlore** [Rectify11/Installer#653]
### Description

After installing Rectify 11 the reWASD program will stop working or won't install at all because of an issue with the Game Controller Mapping Service that reWASD needs to function. Somehow, some of the modifications made to the system prevent this service from executing. After running SFC/DISM commands some of the Rectify 11 modifications will be forfeited but the service will be able to start running and reWASD will function correctly again.

### Steps To Reproduce

1. Install Rectify 11 with any configuration and reboot to complete.
2. Install reWASD and reboot to complete. If it's already installed, try to open it.
3. reWASD will show error -1 due to the Game Controller Mapping service not running.
4. Trying to run Game Controller Mapping service will throw error 1053.
5. Running SFC/DISM Windows will detect corrupt files (related to Rectify 11).
6. Windows will restore those files and after a restart, reWASD will work again (some Rectify 11 stuff will be broken, like the control panel skin).

### Rectify11 Version

3.2.70.2

### Windows Version

Windows 11 Pro 24H2 26100.2033

### Logs

Not applicable.

**Comment by Vehlore** [comment]
[CBS.log](https://github.com/user-attachments/files/17539218/CBS.log)

**Comment by MishaProductions** [comment]
known issue, see #504 and the faq. No clue what causes this.
