### ISSUE TITLE
Unable to uninstall Rectify11 

### ISSUE THREAD

**Issue by BenLaneUK2004** [Rectify11/Installer#662]
### Description

I want to uninstall Rectify11, as apps such as MS Word Desktop display the page as pitch black, and text selection highlight is invisible. However, when I attempt to uninstall Rectify11 using the link in the control panel page, I get the following error:

`Windows cannot find 'C:\Windows\Rectify11\Uninstall.exe'. Make sure you've typed the name correctly, then try again.`

### Steps To Reproduce

1. Open the Rectify11 settings page of control panel
2. Click the "Uninstall Rectify11" link

### Rectify11 Version

Version: 3.7.70.2

### Windows Version

Microsoft Windows 11 Home 24H2 26100.2161

### Logs

Unselected:
![image](https://github.com/user-attachments/assets/a331b01f-bd0e-4ec9-947d-f55e8481a37d)

Selected:
![image](https://github.com/user-attachments/assets/ac4d0c3e-313e-43fc-8ceb-599bba8cc373)

Error:
![image](https://github.com/user-attachments/assets/bfbebcf9-72cc-458a-873b-416866c06f58)

**Comment by Senkanoko** [comment]
You can uninstall Rectify11 via the installer[
![Screenshot 2024-11-22 194223](https://github.com/user-attachments/assets/fea97122-3def-44a8-b4a7-bde5348c5661)
](url)
