### ISSUE TITLE
When opening the mica theme, the font is black and unreadable in dark mode, this bug also appears on the interface of installing Rectify11 in dark mode and it will not appear in the normal dark theme.

### ISSUE THREAD

**Issue by zhcn000000** [Rectify11/Installer#667]
### Description

When opening the mica theme, the font is black and unreadable in dark mode, this bug also appears on the interface of installing Rectify11 in dark mode and it will not appear in the normal dark theme.</br>
![image](https://github.com/user-attachments/assets/3083f623-a5b4-4da8-80a7-cff8560f4536)
![image](https://github.com/user-attachments/assets/ca00b08a-e407-4082-a9ae-6493e640b4bc)</br>
Font colors return to normal when using system printscreen tools
![image](https://github.com/user-attachments/assets/38e31b92-9b47-4c8f-a904-c6ed42897f74)

### Steps To Reproduce

After updating the driver and config system, it suddenly becomes like this and cannot be restored

### Rectify11 Version

3.2

### Windows Version

Windows11 24H2

### Logs

Picture In Description

**Comment by MuscularPuky** [comment]
you're using HDR? if so, it's known Win32 issue, so we can't fix

**Comment by zhcn000000** [comment]
Yes,I use hdr
