### ISSUE TITLE
Uninstaller

### ISSUE THREAD

**Issue by rounk-ctrl** [Rectify11/Installer#99]
Uninstaller implementation in Rectify11.Phase2 to copy files from Backup to the respective locations of those files. We get their respective locations with the help of the Rectify11.xml file.

- [x] Uninstallation of icons (dll, exe)
- [x] Uninstallation of DiagPackage files (troubleshooter files)
- [x] Uninstallation of msc files
- [x] Uninstallation of themes
- [x] Uninstallation of extras

**Comment by PwrSrg** [comment]
I am also unable to uninstall using RP3.  Clicking the uninstall button does **NOTHING**.

**Comment by fytuf** [comment]
yeah thats why this is thread exists

> I am also unable to uninstall using RP3. Clicking the uninstall button does **NOTHING**.

**Comment by Zingzy** [comment]
So how to uninstall it?

**Comment by CuibapKhuong** [comment]
> There are three options to uninstall Rectify11 (for now):
> 
> * System Restore (only if you made one before the Rectify11 install)
> * sfc /scannow (restores only icons, doesn't remove registry entries, nor any other options choosed)
> * Reinstall Windows 11

I used System Restore but it said System Restore Did Not Complete Successfully.
Sfc /scannow: I don't want it.
Reinstall: I don't want to lose all my datas.

- Sorry for bad English.

**Comment by HolyNetworkAdapter** [comment]
You can select clean install but keep your documents/pictures/whatever (in your user folder) intact. For other data you can put on a USB thumb drive or external hard disk.

**Comment by CuibapKhuong** [comment]
> You can select clean install but keep your documents/pictures/whatever (in your user folder) intact. For other data you can put on a USB thumb drive or external hard disk.

Is Rectify 11's team working to fix it?

**Comment by CuibapKhuong** [comment]
> > Sfc /scannow: I don't want it.
> 
> What's the problem with sfc?
> 
> 
> > Is Rectify 11's team working to fix it?
> 
> It will be included in v3 final, so yes they are working on it.

**What's the problem with sfc?**
- Because I don't want to scan. It's only restores the icons.

**It will be included in v3 final, so yes they are working on it."
- So I am using Release Preview 3. Can I uninstall it in Release Preview 4?

**Comment by CuibapKhuong** [comment]
> > > Sfc /scannow: I don't want it.
> > 
> > 
> > What's the problem with sfc?
> > > Is Rectify 11's team working to fix it?
> > 
> > 
> > It will be included in v3 final, so yes they are working on it.
> 
> **What's the problem with sfc?**
> 
> * Because I don't want to scan. It's only restores the icons.
> 
> **It will be included in v3 final, so yes they are working on it."**
> 
> * So I am using Release Preview 3. Can I uninstall it in Release Preview 4?

**Comment by CuibapKhuong** [comment]
> > > > Sfc /scannow: I don't want it.
> > > 
> > > 
> > > What's the problem with sfc?
> > > > Is Rectify 11's team working to fix it?
> > > 
> > > 
> > > It will be included in v3 final, so yes they are working on it.
> > 
> > 
> > **What's the problem with sfc?**
> > 
> > * Because I don't want to scan. It's only restores the icons.
> > 
> > **It will be included in v3 final, so yes they are working on it.**
> > 
> > * So I am using Release Preview 3. Can I uninstall it in Release Preview 4?

**Comment by rounk-ctrl** [comment]
this issue is for tracking the uninstaller progress, not for your damn issues.
